// Code generated by zigo. DO NOT EDIT.

package input

import (
	"io"
	"runtime/cgo"
	"sync/atomic"
	"unsafe"

	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

type zigoHandle = lifecycle.Handle

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return lifecycle.CheckedPointer(operation, value)
}
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	return lifecycle.PoisonAfterPanic(err, handles...)
}

func zigoBoolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var zigoActiveCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func zigoNewWriterStreamHandle(value io.Writer) zigoCallbackHandle {
	handle := cgo.NewHandle(&raw.CallbackState{Writer: value})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoDeleteCallbackHandle(handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	handle.Delete()
	zigoActiveCallbackHandles.Add(-1)
}

func zigoActiveCallbackHandleCount() int64 { return zigoActiveCallbackHandles.Load() }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}

// zigoStreamError reports the error the Go stream behind handle returned
// inside the native call that has just finished, wrapped so the caller can
// match it with errors.Is.
func zigoStreamError(operation string, parameter string, handle zigoCallbackHandle) error {
	if err, ok := raw.TakeStreamError(handle); ok {
		return &StreamError{Operation: operation, Parameter: parameter, Err: err}
	}
	return nil
}
