// Code generated by zigo. DO NOT EDIT.

// Package input encodes key, mouse, focus and paste events into the bytes a program reading the pty expects.
package input

import (
	"io"

	zigo_default "github.com/ironpark/gostty"
	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

// Codepoint: Returns the codepoint representing this key, or null if the key is not
// printable
func (k Key) Codepoint() (rune, bool) {
	zigoResult, zigoHas := raw.KeyCodepoint(int32(k))
	return rune(zigoResult), zigoHas
}

// Printable: True if this key represents a printable character.
func (k Key) Printable() bool {
	return raw.KeyPrintable(int32(k)) != 0
}

// Modifier: True if this key is a modifier.
func (k Key) Modifier() bool {
	return raw.KeyModifier(int32(k)) != 0
}

// Keypad: Returns true if this is a keypad key.
func (k Key) Keypad() bool {
	return raw.KeyKeypad(int32(k)) != 0
}

// LeftOrRightShift true if this key is either left or right shift.
func (k Key) LeftOrRightShift() bool {
	return raw.KeyLeftOrRightShift(int32(k)) != 0
}

// LeftOrRightAlt true if this key is either left or right alt.
func (k Key) LeftOrRightAlt() bool {
	return raw.KeyLeftOrRightAlt(int32(k)) != 0
}

// CtrlOrSuper true if this key is one of the left or right versions of super (MacOS)
// or ctrl.
func (k Key) CtrlOrSuper() bool {
	return raw.KeyCtrlOrSuper(int32(k)) != 0
}

// ShouldBeRemappable: Whether this key should be remappable by the operating system.
//
// On certain OSes (namely Linux and the BSDs) certain keys like the
// functional keys are expected to be remappable by the user, such as
// in the very common use case of swapping the Caps Lock key with the
// Escape key with the XKB option `caps:swapescape`.
//
// However, the way XKB implements this is by essentially acting as a
// software key remapper that destroys all information about the original
// physical key, leading to very annoying bugs like #7309 where the
// physical key `XKB_KEY_c` gets remapped into `XKB_KEY_Cyrillic_tse`,
// which causes all of our physical key handling to completely break down.
// _Very naughty._
//
// As a compromise, given that writing system keys (§3.1.1) comprise the
// majority of keys that "change meaning [...] based on the current locale
// and keyboard layout", we allow all other keys to be remapped by default
// since they should be fairly harmless. We might consider making this
// configurable, but for now this should at least placate most people.
func (k Key) ShouldBeRemappable() bool {
	return raw.KeyShouldBeRemappable(int32(k)) != 0
}

// W3C: Converts a Ghostty key enum value to a W3C key code.
func (k Key) W3C() string {
	return raw.KeyW3C(int32(k))
}

// EncodeKey: Encode a key event for `terminal`, whose modes decide the encoding. `utf8`
// is the text the key produced, empty when it produced none.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeKey(writer io.Writer, terminal *zigo_default.Terminal, event KeyEvent, utf8 string) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeKey", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodeKey parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodeKey(uintptr(writerHandle), terminalPtr, zigoKeyEventToRaw(event), utf8)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeKey", writerHandle)
	}
	if err := zigoStreamError("EncodeKey", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodeKey", code), terminal)
	}
	return nil
}

// EncodeMouse: Encode a mouse event for `terminal`, whose reporting mode and format decide
// whether anything is written at all.
//
// `any_button_pressed` should include this event, so a press reports true.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeMouse(writer io.Writer, terminal *zigo_default.Terminal, event MouseEvent, size RenderSize, anyButtonPressed bool) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeMouse", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodeMouse parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodeMouse(uintptr(writerHandle), terminalPtr, zigoMouseEventToRaw(event), zigoRenderSizeToRaw(size), zigoBoolToUint8(anyButtonPressed))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeMouse", writerHandle)
	}
	if err := zigoStreamError("EncodeMouse", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodeMouse", code), terminal)
	}
	return nil
}

// KeyFromAscii: Converts an ASCII character to a key, if possible. This returns
// null if the character is unknown.
//
// Note that this can't distinguish between physical keys, i.e. '0'
// may be from the number row or the keypad, but it always maps
// to '.zero'.
//
// This is what we want, we want people to create keybindings that
// are independent of the physical key.
func KeyFromAscii(ch uint8) (Key, bool) {
	zigoResult, zigoHas := raw.KeyKeyFromAscii(ch)
	return Key(zigoResult), zigoHas
}

// KeyFromW3C: Converts a W3C key code to a Ghostty key enum value.
//
// All required W3C key codes are supported, but there are a number of
// non-standard key codes that are not supported. In the case the value is
// invalid or unsupported, this function will return null.
func KeyFromW3C(w3cCode string) (Key, bool) {
	zigoResult, zigoHas := raw.KeyKeyFromW3C(w3cCode)
	return Key(zigoResult), zigoHas
}

// EncodeFocus calls the Zig function encodeFocus.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeFocus(writer io.Writer, event FocusEvent) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeFocus", Parameter: "writer", Err: ErrNilStream}
	}
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.InputEncodeFocus(uintptr(writerHandle), uint8(event))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeFocus", writerHandle)
	}
	if err := zigoStreamError("EncodeFocus", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoErrorForCode("EncodeFocus", code)
	}
	return nil
}

// IsSafePaste: Returns true if the data looks safe to paste. Data is considered
// unsafe if it contains any of the following:
//
// - `\n`: Newlines can be used to inject commands.
// - `\x1b[201~`: This is the end of a bracketed paste. This cane be used
// to exit a bracketed paste and inject commands.
//
// We consider any scenario unsafe regardless of current terminal state.
// For example, even if bracketed paste mode is not active, we still
// consider `\x1b[201~` unsafe. The existence of these types of bytes
// should raise suspicion that the producer of the paste data is
// acting strangely.
func IsSafePaste(data []byte) bool {
	return raw.InputIsSafePaste(data) != 0
}

// EncodePaste: Encode `data` for pasting into `terminal`, respecting bracketed paste mode.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodePaste(writer io.Writer, terminal *zigo_default.Terminal, data []byte) error {
	if writer == nil {
		return &StreamError{Operation: "EncodePaste", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodePaste parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodePaste(uintptr(writerHandle), terminalPtr, data)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodePaste", writerHandle)
	}
	if err := zigoStreamError("EncodePaste", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodePaste", code), terminal)
	}
	return nil
}
