// Code generated by zigo. DO NOT EDIT.

// Package input encodes key, mouse, focus and paste events into the bytes a program reading the pty expects.
package input

import (
	"io"

	zigo_default "github.com/ironpark/gostty"
	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

// EncodeKey: Encode a key event for `terminal`, whose modes decide the encoding. `utf8`
// is the text the key produced, empty when it produced none.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeKey(writer io.Writer, terminal *zigo_default.Terminal, event KeyEvent, utf8 string) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeKey", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodeKey parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodeKey(uintptr(writerHandle), terminalPtr, zigoKeyEventToRaw(event), utf8)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeKey", writerHandle)
	}
	if err := zigoStreamError("EncodeKey", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodeKey", code), terminal)
	}
	return nil
}

// EncodeMouse: Encode a mouse event for `terminal`, whose reporting mode and format decide
// whether anything is written at all.
//
// `any_button_pressed` should include this event, so a press reports true.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeMouse(writer io.Writer, terminal *zigo_default.Terminal, event MouseEvent, size RenderSize, anyButtonPressed bool) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeMouse", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodeMouse parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodeMouse(uintptr(writerHandle), terminalPtr, zigoMouseEventToRaw(event), zigoRenderSizeToRaw(size), zigoBoolToUint8(anyButtonPressed))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeMouse", writerHandle)
	}
	if err := zigoStreamError("EncodeMouse", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodeMouse", code), terminal)
	}
	return nil
}

// KeyFromAscii: The key for a printable ASCII byte, or null if none maps to it.
func KeyFromAscii(ch uint8) (Key, bool) {
	zigoResult, zigoHas := raw.KeyFromAscii(ch)
	return Key(zigoResult), zigoHas
}

// KeyCodepoint: The Unicode codepoint the key produces on a US layout, if it has one.
func KeyCodepoint(key Key) (rune, bool) {
	zigoResult, zigoHas := raw.KeyCodepoint(int32(key))
	return rune(zigoResult), zigoHas
}

// KeyPrintable: True for keys that produce text on a US layout.
func KeyPrintable(key Key) bool {
	return raw.KeyPrintable(int32(key)) != 0
}

// KeyModifier: True for modifier keys such as shift, control and alt.
func KeyModifier(key Key) bool {
	return raw.KeyModifier(int32(key)) != 0
}

// KeyKeypad: True for keys on the numeric keypad.
func KeyKeypad(key Key) bool {
	return raw.KeyKeypad(int32(key)) != 0
}

// KeyLeftOrRightShift: True for shift on either side.
func KeyLeftOrRightShift(key Key) bool {
	return raw.KeyLeftOrRightShift(int32(key)) != 0
}

// KeyLeftOrRightAlt: True for alt on either side.
func KeyLeftOrRightAlt(key Key) bool {
	return raw.KeyLeftOrRightAlt(int32(key)) != 0
}

// EncodeFocus calls the Zig function encodeFocus.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodeFocus(writer io.Writer, event FocusEvent) error {
	if writer == nil {
		return &StreamError{Operation: "EncodeFocus", Parameter: "writer", Err: ErrNilStream}
	}
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.InputEncodeFocus(uintptr(writerHandle), uint8(event))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodeFocus", writerHandle)
	}
	if err := zigoStreamError("EncodeFocus", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoErrorForCode("EncodeFocus", code)
	}
	return nil
}

// IsSafePaste calls the Zig function isSafePaste.
func IsSafePaste(data []byte) bool {
	return raw.InputIsSafePaste(data) != 0
}

// EncodePaste: Encode `data` for pasting into `terminal`, respecting bracketed paste mode.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func EncodePaste(writer io.Writer, terminal *zigo_default.Terminal, data []byte) error {
	if writer == nil {
		return &StreamError{Operation: "EncodePaste", Parameter: "writer", Err: ErrNilStream}
	}
	terminalPtr, err := zigoCheckedPointer("EncodePaste parameter terminal", terminal)
	if err != nil {
		return err
	}
	defer lifecycle.Release(terminal)
	writerHandle := zigoNewWriterStreamHandle(writer)
	defer zigoDeleteCallbackHandle(writerHandle)
	code := raw.EncodePaste(uintptr(writerHandle), terminalPtr, data)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("EncodePaste", writerHandle)
	}
	if err := zigoStreamError("EncodePaste", "writer", writerHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("EncodePaste", code), terminal)
	}
	return nil
}
