// Code generated by zigo. DO NOT EDIT.

package input

import "strconv"

// EnumParseError reports text that names no value of a generated enum.
type EnumParseError struct {
	// Type is the Go enum type name.
	Type string
	// Text is the rejected input.
	Text string
}

// Error implements error.
func (err *EnumParseError) Error() string {
	return "zigo: " + err.Type + ": unknown value " + strconv.Quote(err.Text)
}

// Key represents the corresponding Zig enum.
type Key int32

const (
	// KeyUnidentified corresponds to the Zig tag unidentified.
	KeyUnidentified Key = 0
	// KeyBackquote corresponds to the Zig tag backquote.
	KeyBackquote Key = 1
	// KeyBackslash corresponds to the Zig tag backslash.
	KeyBackslash Key = 2
	// KeyBracketLeft corresponds to the Zig tag bracket_left.
	KeyBracketLeft Key = 3
	// KeyBracketRight corresponds to the Zig tag bracket_right.
	KeyBracketRight Key = 4
	// KeyComma corresponds to the Zig tag comma.
	KeyComma Key = 5
	// KeyDigit0 corresponds to the Zig tag digit_0.
	KeyDigit0 Key = 6
	// KeyDigit1 corresponds to the Zig tag digit_1.
	KeyDigit1 Key = 7
	// KeyDigit2 corresponds to the Zig tag digit_2.
	KeyDigit2 Key = 8
	// KeyDigit3 corresponds to the Zig tag digit_3.
	KeyDigit3 Key = 9
	// KeyDigit4 corresponds to the Zig tag digit_4.
	KeyDigit4 Key = 10
	// KeyDigit5 corresponds to the Zig tag digit_5.
	KeyDigit5 Key = 11
	// KeyDigit6 corresponds to the Zig tag digit_6.
	KeyDigit6 Key = 12
	// KeyDigit7 corresponds to the Zig tag digit_7.
	KeyDigit7 Key = 13
	// KeyDigit8 corresponds to the Zig tag digit_8.
	KeyDigit8 Key = 14
	// KeyDigit9 corresponds to the Zig tag digit_9.
	KeyDigit9 Key = 15
	// KeyEqual corresponds to the Zig tag equal.
	KeyEqual Key = 16
	// KeyIntlBackslash corresponds to the Zig tag intl_backslash.
	KeyIntlBackslash Key = 17
	// KeyIntlRo corresponds to the Zig tag intl_ro.
	KeyIntlRo Key = 18
	// KeyIntlYen corresponds to the Zig tag intl_yen.
	KeyIntlYen Key = 19
	// KeyKeyA corresponds to the Zig tag key_a.
	KeyKeyA Key = 20
	// KeyKeyB corresponds to the Zig tag key_b.
	KeyKeyB Key = 21
	// KeyKeyC corresponds to the Zig tag key_c.
	KeyKeyC Key = 22
	// KeyKeyD corresponds to the Zig tag key_d.
	KeyKeyD Key = 23
	// KeyKeyE corresponds to the Zig tag key_e.
	KeyKeyE Key = 24
	// KeyKeyF corresponds to the Zig tag key_f.
	KeyKeyF Key = 25
	// KeyKeyG corresponds to the Zig tag key_g.
	KeyKeyG Key = 26
	// KeyKeyH corresponds to the Zig tag key_h.
	KeyKeyH Key = 27
	// KeyKeyI corresponds to the Zig tag key_i.
	KeyKeyI Key = 28
	// KeyKeyJ corresponds to the Zig tag key_j.
	KeyKeyJ Key = 29
	// KeyKeyK corresponds to the Zig tag key_k.
	KeyKeyK Key = 30
	// KeyKeyL corresponds to the Zig tag key_l.
	KeyKeyL Key = 31
	// KeyKeyM corresponds to the Zig tag key_m.
	KeyKeyM Key = 32
	// KeyKeyN corresponds to the Zig tag key_n.
	KeyKeyN Key = 33
	// KeyKeyO corresponds to the Zig tag key_o.
	KeyKeyO Key = 34
	// KeyKeyP corresponds to the Zig tag key_p.
	KeyKeyP Key = 35
	// KeyKeyQ corresponds to the Zig tag key_q.
	KeyKeyQ Key = 36
	// KeyKeyR corresponds to the Zig tag key_r.
	KeyKeyR Key = 37
	// KeyKeyS corresponds to the Zig tag key_s.
	KeyKeyS Key = 38
	// KeyKeyT corresponds to the Zig tag key_t.
	KeyKeyT Key = 39
	// KeyKeyU corresponds to the Zig tag key_u.
	KeyKeyU Key = 40
	// KeyKeyV corresponds to the Zig tag key_v.
	KeyKeyV Key = 41
	// KeyKeyW corresponds to the Zig tag key_w.
	KeyKeyW Key = 42
	// KeyKeyX corresponds to the Zig tag key_x.
	KeyKeyX Key = 43
	// KeyKeyY corresponds to the Zig tag key_y.
	KeyKeyY Key = 44
	// KeyKeyZ corresponds to the Zig tag key_z.
	KeyKeyZ Key = 45
	// KeyMinus corresponds to the Zig tag minus.
	KeyMinus Key = 46
	// KeyPeriod corresponds to the Zig tag period.
	KeyPeriod Key = 47
	// KeyQuote corresponds to the Zig tag quote.
	KeyQuote Key = 48
	// KeySemicolon corresponds to the Zig tag semicolon.
	KeySemicolon Key = 49
	// KeySlash corresponds to the Zig tag slash.
	KeySlash Key = 50
	// KeyAltLeft corresponds to the Zig tag alt_left.
	KeyAltLeft Key = 51
	// KeyAltRight corresponds to the Zig tag alt_right.
	KeyAltRight Key = 52
	// KeyBackspace corresponds to the Zig tag backspace.
	KeyBackspace Key = 53
	// KeyCapsLock corresponds to the Zig tag caps_lock.
	KeyCapsLock Key = 54
	// KeyContextMenu corresponds to the Zig tag context_menu.
	KeyContextMenu Key = 55
	// KeyControlLeft corresponds to the Zig tag control_left.
	KeyControlLeft Key = 56
	// KeyControlRight corresponds to the Zig tag control_right.
	KeyControlRight Key = 57
	// KeyEnter corresponds to the Zig tag enter.
	KeyEnter Key = 58
	// KeyMetaLeft corresponds to the Zig tag meta_left.
	KeyMetaLeft Key = 59
	// KeyMetaRight corresponds to the Zig tag meta_right.
	KeyMetaRight Key = 60
	// KeyShiftLeft corresponds to the Zig tag shift_left.
	KeyShiftLeft Key = 61
	// KeyShiftRight corresponds to the Zig tag shift_right.
	KeyShiftRight Key = 62
	// KeySpace corresponds to the Zig tag space.
	KeySpace Key = 63
	// KeyTab corresponds to the Zig tag tab.
	KeyTab Key = 64
	// KeyConvert corresponds to the Zig tag convert.
	KeyConvert Key = 65
	// KeyKanaMode corresponds to the Zig tag kana_mode.
	KeyKanaMode Key = 66
	// KeyNonConvert corresponds to the Zig tag non_convert.
	KeyNonConvert Key = 67
	// KeyDelete corresponds to the Zig tag delete.
	KeyDelete Key = 68
	// KeyEnd corresponds to the Zig tag end.
	KeyEnd Key = 69
	// KeyHelp corresponds to the Zig tag help.
	KeyHelp Key = 70
	// KeyHome corresponds to the Zig tag home.
	KeyHome Key = 71
	// KeyInsert corresponds to the Zig tag insert.
	KeyInsert Key = 72
	// KeyPageDown corresponds to the Zig tag page_down.
	KeyPageDown Key = 73
	// KeyPageUp corresponds to the Zig tag page_up.
	KeyPageUp Key = 74
	// KeyArrowDown corresponds to the Zig tag arrow_down.
	KeyArrowDown Key = 75
	// KeyArrowLeft corresponds to the Zig tag arrow_left.
	KeyArrowLeft Key = 76
	// KeyArrowRight corresponds to the Zig tag arrow_right.
	KeyArrowRight Key = 77
	// KeyArrowUp corresponds to the Zig tag arrow_up.
	KeyArrowUp Key = 78
	// KeyNumLock corresponds to the Zig tag num_lock.
	KeyNumLock Key = 79
	// KeyNumpad0 corresponds to the Zig tag numpad_0.
	KeyNumpad0 Key = 80
	// KeyNumpad1 corresponds to the Zig tag numpad_1.
	KeyNumpad1 Key = 81
	// KeyNumpad2 corresponds to the Zig tag numpad_2.
	KeyNumpad2 Key = 82
	// KeyNumpad3 corresponds to the Zig tag numpad_3.
	KeyNumpad3 Key = 83
	// KeyNumpad4 corresponds to the Zig tag numpad_4.
	KeyNumpad4 Key = 84
	// KeyNumpad5 corresponds to the Zig tag numpad_5.
	KeyNumpad5 Key = 85
	// KeyNumpad6 corresponds to the Zig tag numpad_6.
	KeyNumpad6 Key = 86
	// KeyNumpad7 corresponds to the Zig tag numpad_7.
	KeyNumpad7 Key = 87
	// KeyNumpad8 corresponds to the Zig tag numpad_8.
	KeyNumpad8 Key = 88
	// KeyNumpad9 corresponds to the Zig tag numpad_9.
	KeyNumpad9 Key = 89
	// KeyNumpadAdd corresponds to the Zig tag numpad_add.
	KeyNumpadAdd Key = 90
	// KeyNumpadBackspace corresponds to the Zig tag numpad_backspace.
	KeyNumpadBackspace Key = 91
	// KeyNumpadClear corresponds to the Zig tag numpad_clear.
	KeyNumpadClear Key = 92
	// KeyNumpadClearEntry corresponds to the Zig tag numpad_clear_entry.
	KeyNumpadClearEntry Key = 93
	// KeyNumpadComma corresponds to the Zig tag numpad_comma.
	KeyNumpadComma Key = 94
	// KeyNumpadDecimal corresponds to the Zig tag numpad_decimal.
	KeyNumpadDecimal Key = 95
	// KeyNumpadDivide corresponds to the Zig tag numpad_divide.
	KeyNumpadDivide Key = 96
	// KeyNumpadEnter corresponds to the Zig tag numpad_enter.
	KeyNumpadEnter Key = 97
	// KeyNumpadEqual corresponds to the Zig tag numpad_equal.
	KeyNumpadEqual Key = 98
	// KeyNumpadMemoryAdd corresponds to the Zig tag numpad_memory_add.
	KeyNumpadMemoryAdd Key = 99
	// KeyNumpadMemoryClear corresponds to the Zig tag numpad_memory_clear.
	KeyNumpadMemoryClear Key = 100
	// KeyNumpadMemoryRecall corresponds to the Zig tag numpad_memory_recall.
	KeyNumpadMemoryRecall Key = 101
	// KeyNumpadMemoryStore corresponds to the Zig tag numpad_memory_store.
	KeyNumpadMemoryStore Key = 102
	// KeyNumpadMemorySubtract corresponds to the Zig tag numpad_memory_subtract.
	KeyNumpadMemorySubtract Key = 103
	// KeyNumpadMultiply corresponds to the Zig tag numpad_multiply.
	KeyNumpadMultiply Key = 104
	// KeyNumpadParenLeft corresponds to the Zig tag numpad_paren_left.
	KeyNumpadParenLeft Key = 105
	// KeyNumpadParenRight corresponds to the Zig tag numpad_paren_right.
	KeyNumpadParenRight Key = 106
	// KeyNumpadSubtract corresponds to the Zig tag numpad_subtract.
	KeyNumpadSubtract Key = 107
	// KeyNumpadSeparator corresponds to the Zig tag numpad_separator.
	KeyNumpadSeparator Key = 108
	// KeyNumpadUp corresponds to the Zig tag numpad_up.
	KeyNumpadUp Key = 109
	// KeyNumpadDown corresponds to the Zig tag numpad_down.
	KeyNumpadDown Key = 110
	// KeyNumpadRight corresponds to the Zig tag numpad_right.
	KeyNumpadRight Key = 111
	// KeyNumpadLeft corresponds to the Zig tag numpad_left.
	KeyNumpadLeft Key = 112
	// KeyNumpadBegin corresponds to the Zig tag numpad_begin.
	KeyNumpadBegin Key = 113
	// KeyNumpadHome corresponds to the Zig tag numpad_home.
	KeyNumpadHome Key = 114
	// KeyNumpadEnd corresponds to the Zig tag numpad_end.
	KeyNumpadEnd Key = 115
	// KeyNumpadInsert corresponds to the Zig tag numpad_insert.
	KeyNumpadInsert Key = 116
	// KeyNumpadDelete corresponds to the Zig tag numpad_delete.
	KeyNumpadDelete Key = 117
	// KeyNumpadPageUp corresponds to the Zig tag numpad_page_up.
	KeyNumpadPageUp Key = 118
	// KeyNumpadPageDown corresponds to the Zig tag numpad_page_down.
	KeyNumpadPageDown Key = 119
	// KeyEscape corresponds to the Zig tag escape.
	KeyEscape Key = 120
	// KeyF1 corresponds to the Zig tag f1.
	KeyF1 Key = 121
	// KeyF2 corresponds to the Zig tag f2.
	KeyF2 Key = 122
	// KeyF3 corresponds to the Zig tag f3.
	KeyF3 Key = 123
	// KeyF4 corresponds to the Zig tag f4.
	KeyF4 Key = 124
	// KeyF5 corresponds to the Zig tag f5.
	KeyF5 Key = 125
	// KeyF6 corresponds to the Zig tag f6.
	KeyF6 Key = 126
	// KeyF7 corresponds to the Zig tag f7.
	KeyF7 Key = 127
	// KeyF8 corresponds to the Zig tag f8.
	KeyF8 Key = 128
	// KeyF9 corresponds to the Zig tag f9.
	KeyF9 Key = 129
	// KeyF10 corresponds to the Zig tag f10.
	KeyF10 Key = 130
	// KeyF11 corresponds to the Zig tag f11.
	KeyF11 Key = 131
	// KeyF12 corresponds to the Zig tag f12.
	KeyF12 Key = 132
	// KeyF13 corresponds to the Zig tag f13.
	KeyF13 Key = 133
	// KeyF14 corresponds to the Zig tag f14.
	KeyF14 Key = 134
	// KeyF15 corresponds to the Zig tag f15.
	KeyF15 Key = 135
	// KeyF16 corresponds to the Zig tag f16.
	KeyF16 Key = 136
	// KeyF17 corresponds to the Zig tag f17.
	KeyF17 Key = 137
	// KeyF18 corresponds to the Zig tag f18.
	KeyF18 Key = 138
	// KeyF19 corresponds to the Zig tag f19.
	KeyF19 Key = 139
	// KeyF20 corresponds to the Zig tag f20.
	KeyF20 Key = 140
	// KeyF21 corresponds to the Zig tag f21.
	KeyF21 Key = 141
	// KeyF22 corresponds to the Zig tag f22.
	KeyF22 Key = 142
	// KeyF23 corresponds to the Zig tag f23.
	KeyF23 Key = 143
	// KeyF24 corresponds to the Zig tag f24.
	KeyF24 Key = 144
	// KeyF25 corresponds to the Zig tag f25.
	KeyF25 Key = 145
	// KeyFn corresponds to the Zig tag fn.
	KeyFn Key = 146
	// KeyFnLock corresponds to the Zig tag fn_lock.
	KeyFnLock Key = 147
	// KeyPrintScreen corresponds to the Zig tag print_screen.
	KeyPrintScreen Key = 148
	// KeyScrollLock corresponds to the Zig tag scroll_lock.
	KeyScrollLock Key = 149
	// KeyPause corresponds to the Zig tag pause.
	KeyPause Key = 150
	// KeyBrowserBack corresponds to the Zig tag browser_back.
	KeyBrowserBack Key = 151
	// KeyBrowserFavorites corresponds to the Zig tag browser_favorites.
	KeyBrowserFavorites Key = 152
	// KeyBrowserForward corresponds to the Zig tag browser_forward.
	KeyBrowserForward Key = 153
	// KeyBrowserHome corresponds to the Zig tag browser_home.
	KeyBrowserHome Key = 154
	// KeyBrowserRefresh corresponds to the Zig tag browser_refresh.
	KeyBrowserRefresh Key = 155
	// KeyBrowserSearch corresponds to the Zig tag browser_search.
	KeyBrowserSearch Key = 156
	// KeyBrowserStop corresponds to the Zig tag browser_stop.
	KeyBrowserStop Key = 157
	// KeyEject corresponds to the Zig tag eject.
	KeyEject Key = 158
	// KeyLaunchApp1 corresponds to the Zig tag launch_app_1.
	KeyLaunchApp1 Key = 159
	// KeyLaunchApp2 corresponds to the Zig tag launch_app_2.
	KeyLaunchApp2 Key = 160
	// KeyLaunchMail corresponds to the Zig tag launch_mail.
	KeyLaunchMail Key = 161
	// KeyMediaPlayPause corresponds to the Zig tag media_play_pause.
	KeyMediaPlayPause Key = 162
	// KeyMediaSelect corresponds to the Zig tag media_select.
	KeyMediaSelect Key = 163
	// KeyMediaStop corresponds to the Zig tag media_stop.
	KeyMediaStop Key = 164
	// KeyMediaTrackNext corresponds to the Zig tag media_track_next.
	KeyMediaTrackNext Key = 165
	// KeyMediaTrackPrevious corresponds to the Zig tag media_track_previous.
	KeyMediaTrackPrevious Key = 166
	// KeyPower corresponds to the Zig tag power.
	KeyPower Key = 167
	// KeySleep corresponds to the Zig tag sleep.
	KeySleep Key = 168
	// KeyAudioVolumeDown corresponds to the Zig tag audio_volume_down.
	KeyAudioVolumeDown Key = 169
	// KeyAudioVolumeMute corresponds to the Zig tag audio_volume_mute.
	KeyAudioVolumeMute Key = 170
	// KeyAudioVolumeUp corresponds to the Zig tag audio_volume_up.
	KeyAudioVolumeUp Key = 171
	// KeyWakeUp corresponds to the Zig tag wake_up.
	KeyWakeUp Key = 172
	// KeyCopy corresponds to the Zig tag copy.
	KeyCopy Key = 173
	// KeyCut corresponds to the Zig tag cut.
	KeyCut Key = 174
	// KeyPaste corresponds to the Zig tag paste.
	KeyPaste Key = 175
)

var zigoKeyNames = [176]string{
	0:   "unidentified",
	1:   "backquote",
	2:   "backslash",
	3:   "bracket_left",
	4:   "bracket_right",
	5:   "comma",
	6:   "digit_0",
	7:   "digit_1",
	8:   "digit_2",
	9:   "digit_3",
	10:  "digit_4",
	11:  "digit_5",
	12:  "digit_6",
	13:  "digit_7",
	14:  "digit_8",
	15:  "digit_9",
	16:  "equal",
	17:  "intl_backslash",
	18:  "intl_ro",
	19:  "intl_yen",
	20:  "key_a",
	21:  "key_b",
	22:  "key_c",
	23:  "key_d",
	24:  "key_e",
	25:  "key_f",
	26:  "key_g",
	27:  "key_h",
	28:  "key_i",
	29:  "key_j",
	30:  "key_k",
	31:  "key_l",
	32:  "key_m",
	33:  "key_n",
	34:  "key_o",
	35:  "key_p",
	36:  "key_q",
	37:  "key_r",
	38:  "key_s",
	39:  "key_t",
	40:  "key_u",
	41:  "key_v",
	42:  "key_w",
	43:  "key_x",
	44:  "key_y",
	45:  "key_z",
	46:  "minus",
	47:  "period",
	48:  "quote",
	49:  "semicolon",
	50:  "slash",
	51:  "alt_left",
	52:  "alt_right",
	53:  "backspace",
	54:  "caps_lock",
	55:  "context_menu",
	56:  "control_left",
	57:  "control_right",
	58:  "enter",
	59:  "meta_left",
	60:  "meta_right",
	61:  "shift_left",
	62:  "shift_right",
	63:  "space",
	64:  "tab",
	65:  "convert",
	66:  "kana_mode",
	67:  "non_convert",
	68:  "delete",
	69:  "end",
	70:  "help",
	71:  "home",
	72:  "insert",
	73:  "page_down",
	74:  "page_up",
	75:  "arrow_down",
	76:  "arrow_left",
	77:  "arrow_right",
	78:  "arrow_up",
	79:  "num_lock",
	80:  "numpad_0",
	81:  "numpad_1",
	82:  "numpad_2",
	83:  "numpad_3",
	84:  "numpad_4",
	85:  "numpad_5",
	86:  "numpad_6",
	87:  "numpad_7",
	88:  "numpad_8",
	89:  "numpad_9",
	90:  "numpad_add",
	91:  "numpad_backspace",
	92:  "numpad_clear",
	93:  "numpad_clear_entry",
	94:  "numpad_comma",
	95:  "numpad_decimal",
	96:  "numpad_divide",
	97:  "numpad_enter",
	98:  "numpad_equal",
	99:  "numpad_memory_add",
	100: "numpad_memory_clear",
	101: "numpad_memory_recall",
	102: "numpad_memory_store",
	103: "numpad_memory_subtract",
	104: "numpad_multiply",
	105: "numpad_paren_left",
	106: "numpad_paren_right",
	107: "numpad_subtract",
	108: "numpad_separator",
	109: "numpad_up",
	110: "numpad_down",
	111: "numpad_right",
	112: "numpad_left",
	113: "numpad_begin",
	114: "numpad_home",
	115: "numpad_end",
	116: "numpad_insert",
	117: "numpad_delete",
	118: "numpad_page_up",
	119: "numpad_page_down",
	120: "escape",
	121: "f1",
	122: "f2",
	123: "f3",
	124: "f4",
	125: "f5",
	126: "f6",
	127: "f7",
	128: "f8",
	129: "f9",
	130: "f10",
	131: "f11",
	132: "f12",
	133: "f13",
	134: "f14",
	135: "f15",
	136: "f16",
	137: "f17",
	138: "f18",
	139: "f19",
	140: "f20",
	141: "f21",
	142: "f22",
	143: "f23",
	144: "f24",
	145: "f25",
	146: "fn",
	147: "fn_lock",
	148: "print_screen",
	149: "scroll_lock",
	150: "pause",
	151: "browser_back",
	152: "browser_favorites",
	153: "browser_forward",
	154: "browser_home",
	155: "browser_refresh",
	156: "browser_search",
	157: "browser_stop",
	158: "eject",
	159: "launch_app_1",
	160: "launch_app_2",
	161: "launch_mail",
	162: "media_play_pause",
	163: "media_select",
	164: "media_stop",
	165: "media_track_next",
	166: "media_track_previous",
	167: "power",
	168: "sleep",
	169: "audio_volume_down",
	170: "audio_volume_mute",
	171: "audio_volume_up",
	172: "wake_up",
	173: "copy",
	174: "cut",
	175: "paste",
}

// String returns the Zig tag name.
func (value Key) String() string {
	if value >= 0 && value <= 175 {
		return zigoKeyNames[uint64(value)]
	}
	return "Key(" + strconv.Itoa(int(value)) + ")"
}

// ParseKey returns the Key named by text, which is a Zig tag name.
func ParseKey(text string) (Key, error) {
	switch text {
	case "unidentified":
		return KeyUnidentified, nil
	case "backquote":
		return KeyBackquote, nil
	case "backslash":
		return KeyBackslash, nil
	case "bracket_left":
		return KeyBracketLeft, nil
	case "bracket_right":
		return KeyBracketRight, nil
	case "comma":
		return KeyComma, nil
	case "digit_0":
		return KeyDigit0, nil
	case "digit_1":
		return KeyDigit1, nil
	case "digit_2":
		return KeyDigit2, nil
	case "digit_3":
		return KeyDigit3, nil
	case "digit_4":
		return KeyDigit4, nil
	case "digit_5":
		return KeyDigit5, nil
	case "digit_6":
		return KeyDigit6, nil
	case "digit_7":
		return KeyDigit7, nil
	case "digit_8":
		return KeyDigit8, nil
	case "digit_9":
		return KeyDigit9, nil
	case "equal":
		return KeyEqual, nil
	case "intl_backslash":
		return KeyIntlBackslash, nil
	case "intl_ro":
		return KeyIntlRo, nil
	case "intl_yen":
		return KeyIntlYen, nil
	case "key_a":
		return KeyKeyA, nil
	case "key_b":
		return KeyKeyB, nil
	case "key_c":
		return KeyKeyC, nil
	case "key_d":
		return KeyKeyD, nil
	case "key_e":
		return KeyKeyE, nil
	case "key_f":
		return KeyKeyF, nil
	case "key_g":
		return KeyKeyG, nil
	case "key_h":
		return KeyKeyH, nil
	case "key_i":
		return KeyKeyI, nil
	case "key_j":
		return KeyKeyJ, nil
	case "key_k":
		return KeyKeyK, nil
	case "key_l":
		return KeyKeyL, nil
	case "key_m":
		return KeyKeyM, nil
	case "key_n":
		return KeyKeyN, nil
	case "key_o":
		return KeyKeyO, nil
	case "key_p":
		return KeyKeyP, nil
	case "key_q":
		return KeyKeyQ, nil
	case "key_r":
		return KeyKeyR, nil
	case "key_s":
		return KeyKeyS, nil
	case "key_t":
		return KeyKeyT, nil
	case "key_u":
		return KeyKeyU, nil
	case "key_v":
		return KeyKeyV, nil
	case "key_w":
		return KeyKeyW, nil
	case "key_x":
		return KeyKeyX, nil
	case "key_y":
		return KeyKeyY, nil
	case "key_z":
		return KeyKeyZ, nil
	case "minus":
		return KeyMinus, nil
	case "period":
		return KeyPeriod, nil
	case "quote":
		return KeyQuote, nil
	case "semicolon":
		return KeySemicolon, nil
	case "slash":
		return KeySlash, nil
	case "alt_left":
		return KeyAltLeft, nil
	case "alt_right":
		return KeyAltRight, nil
	case "backspace":
		return KeyBackspace, nil
	case "caps_lock":
		return KeyCapsLock, nil
	case "context_menu":
		return KeyContextMenu, nil
	case "control_left":
		return KeyControlLeft, nil
	case "control_right":
		return KeyControlRight, nil
	case "enter":
		return KeyEnter, nil
	case "meta_left":
		return KeyMetaLeft, nil
	case "meta_right":
		return KeyMetaRight, nil
	case "shift_left":
		return KeyShiftLeft, nil
	case "shift_right":
		return KeyShiftRight, nil
	case "space":
		return KeySpace, nil
	case "tab":
		return KeyTab, nil
	case "convert":
		return KeyConvert, nil
	case "kana_mode":
		return KeyKanaMode, nil
	case "non_convert":
		return KeyNonConvert, nil
	case "delete":
		return KeyDelete, nil
	case "end":
		return KeyEnd, nil
	case "help":
		return KeyHelp, nil
	case "home":
		return KeyHome, nil
	case "insert":
		return KeyInsert, nil
	case "page_down":
		return KeyPageDown, nil
	case "page_up":
		return KeyPageUp, nil
	case "arrow_down":
		return KeyArrowDown, nil
	case "arrow_left":
		return KeyArrowLeft, nil
	case "arrow_right":
		return KeyArrowRight, nil
	case "arrow_up":
		return KeyArrowUp, nil
	case "num_lock":
		return KeyNumLock, nil
	case "numpad_0":
		return KeyNumpad0, nil
	case "numpad_1":
		return KeyNumpad1, nil
	case "numpad_2":
		return KeyNumpad2, nil
	case "numpad_3":
		return KeyNumpad3, nil
	case "numpad_4":
		return KeyNumpad4, nil
	case "numpad_5":
		return KeyNumpad5, nil
	case "numpad_6":
		return KeyNumpad6, nil
	case "numpad_7":
		return KeyNumpad7, nil
	case "numpad_8":
		return KeyNumpad8, nil
	case "numpad_9":
		return KeyNumpad9, nil
	case "numpad_add":
		return KeyNumpadAdd, nil
	case "numpad_backspace":
		return KeyNumpadBackspace, nil
	case "numpad_clear":
		return KeyNumpadClear, nil
	case "numpad_clear_entry":
		return KeyNumpadClearEntry, nil
	case "numpad_comma":
		return KeyNumpadComma, nil
	case "numpad_decimal":
		return KeyNumpadDecimal, nil
	case "numpad_divide":
		return KeyNumpadDivide, nil
	case "numpad_enter":
		return KeyNumpadEnter, nil
	case "numpad_equal":
		return KeyNumpadEqual, nil
	case "numpad_memory_add":
		return KeyNumpadMemoryAdd, nil
	case "numpad_memory_clear":
		return KeyNumpadMemoryClear, nil
	case "numpad_memory_recall":
		return KeyNumpadMemoryRecall, nil
	case "numpad_memory_store":
		return KeyNumpadMemoryStore, nil
	case "numpad_memory_subtract":
		return KeyNumpadMemorySubtract, nil
	case "numpad_multiply":
		return KeyNumpadMultiply, nil
	case "numpad_paren_left":
		return KeyNumpadParenLeft, nil
	case "numpad_paren_right":
		return KeyNumpadParenRight, nil
	case "numpad_subtract":
		return KeyNumpadSubtract, nil
	case "numpad_separator":
		return KeyNumpadSeparator, nil
	case "numpad_up":
		return KeyNumpadUp, nil
	case "numpad_down":
		return KeyNumpadDown, nil
	case "numpad_right":
		return KeyNumpadRight, nil
	case "numpad_left":
		return KeyNumpadLeft, nil
	case "numpad_begin":
		return KeyNumpadBegin, nil
	case "numpad_home":
		return KeyNumpadHome, nil
	case "numpad_end":
		return KeyNumpadEnd, nil
	case "numpad_insert":
		return KeyNumpadInsert, nil
	case "numpad_delete":
		return KeyNumpadDelete, nil
	case "numpad_page_up":
		return KeyNumpadPageUp, nil
	case "numpad_page_down":
		return KeyNumpadPageDown, nil
	case "escape":
		return KeyEscape, nil
	case "f1":
		return KeyF1, nil
	case "f2":
		return KeyF2, nil
	case "f3":
		return KeyF3, nil
	case "f4":
		return KeyF4, nil
	case "f5":
		return KeyF5, nil
	case "f6":
		return KeyF6, nil
	case "f7":
		return KeyF7, nil
	case "f8":
		return KeyF8, nil
	case "f9":
		return KeyF9, nil
	case "f10":
		return KeyF10, nil
	case "f11":
		return KeyF11, nil
	case "f12":
		return KeyF12, nil
	case "f13":
		return KeyF13, nil
	case "f14":
		return KeyF14, nil
	case "f15":
		return KeyF15, nil
	case "f16":
		return KeyF16, nil
	case "f17":
		return KeyF17, nil
	case "f18":
		return KeyF18, nil
	case "f19":
		return KeyF19, nil
	case "f20":
		return KeyF20, nil
	case "f21":
		return KeyF21, nil
	case "f22":
		return KeyF22, nil
	case "f23":
		return KeyF23, nil
	case "f24":
		return KeyF24, nil
	case "f25":
		return KeyF25, nil
	case "fn":
		return KeyFn, nil
	case "fn_lock":
		return KeyFnLock, nil
	case "print_screen":
		return KeyPrintScreen, nil
	case "scroll_lock":
		return KeyScrollLock, nil
	case "pause":
		return KeyPause, nil
	case "browser_back":
		return KeyBrowserBack, nil
	case "browser_favorites":
		return KeyBrowserFavorites, nil
	case "browser_forward":
		return KeyBrowserForward, nil
	case "browser_home":
		return KeyBrowserHome, nil
	case "browser_refresh":
		return KeyBrowserRefresh, nil
	case "browser_search":
		return KeyBrowserSearch, nil
	case "browser_stop":
		return KeyBrowserStop, nil
	case "eject":
		return KeyEject, nil
	case "launch_app_1":
		return KeyLaunchApp1, nil
	case "launch_app_2":
		return KeyLaunchApp2, nil
	case "launch_mail":
		return KeyLaunchMail, nil
	case "media_play_pause":
		return KeyMediaPlayPause, nil
	case "media_select":
		return KeyMediaSelect, nil
	case "media_stop":
		return KeyMediaStop, nil
	case "media_track_next":
		return KeyMediaTrackNext, nil
	case "media_track_previous":
		return KeyMediaTrackPrevious, nil
	case "power":
		return KeyPower, nil
	case "sleep":
		return KeySleep, nil
	case "audio_volume_down":
		return KeyAudioVolumeDown, nil
	case "audio_volume_mute":
		return KeyAudioVolumeMute, nil
	case "audio_volume_up":
		return KeyAudioVolumeUp, nil
	case "wake_up":
		return KeyWakeUp, nil
	case "copy":
		return KeyCopy, nil
	case "cut":
		return KeyCut, nil
	case "paste":
		return KeyPaste, nil
	}
	return 0, &EnumParseError{Type: "Key", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value Key) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseKey.
func (value *Key) UnmarshalText(text []byte) error {
	parsed, err := ParseKey(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// KeyValues returns a fresh slice of known values in declaration order.
func KeyValues() []Key {
	return []Key{
		KeyUnidentified,
		KeyBackquote,
		KeyBackslash,
		KeyBracketLeft,
		KeyBracketRight,
		KeyComma,
		KeyDigit0,
		KeyDigit1,
		KeyDigit2,
		KeyDigit3,
		KeyDigit4,
		KeyDigit5,
		KeyDigit6,
		KeyDigit7,
		KeyDigit8,
		KeyDigit9,
		KeyEqual,
		KeyIntlBackslash,
		KeyIntlRo,
		KeyIntlYen,
		KeyKeyA,
		KeyKeyB,
		KeyKeyC,
		KeyKeyD,
		KeyKeyE,
		KeyKeyF,
		KeyKeyG,
		KeyKeyH,
		KeyKeyI,
		KeyKeyJ,
		KeyKeyK,
		KeyKeyL,
		KeyKeyM,
		KeyKeyN,
		KeyKeyO,
		KeyKeyP,
		KeyKeyQ,
		KeyKeyR,
		KeyKeyS,
		KeyKeyT,
		KeyKeyU,
		KeyKeyV,
		KeyKeyW,
		KeyKeyX,
		KeyKeyY,
		KeyKeyZ,
		KeyMinus,
		KeyPeriod,
		KeyQuote,
		KeySemicolon,
		KeySlash,
		KeyAltLeft,
		KeyAltRight,
		KeyBackspace,
		KeyCapsLock,
		KeyContextMenu,
		KeyControlLeft,
		KeyControlRight,
		KeyEnter,
		KeyMetaLeft,
		KeyMetaRight,
		KeyShiftLeft,
		KeyShiftRight,
		KeySpace,
		KeyTab,
		KeyConvert,
		KeyKanaMode,
		KeyNonConvert,
		KeyDelete,
		KeyEnd,
		KeyHelp,
		KeyHome,
		KeyInsert,
		KeyPageDown,
		KeyPageUp,
		KeyArrowDown,
		KeyArrowLeft,
		KeyArrowRight,
		KeyArrowUp,
		KeyNumLock,
		KeyNumpad0,
		KeyNumpad1,
		KeyNumpad2,
		KeyNumpad3,
		KeyNumpad4,
		KeyNumpad5,
		KeyNumpad6,
		KeyNumpad7,
		KeyNumpad8,
		KeyNumpad9,
		KeyNumpadAdd,
		KeyNumpadBackspace,
		KeyNumpadClear,
		KeyNumpadClearEntry,
		KeyNumpadComma,
		KeyNumpadDecimal,
		KeyNumpadDivide,
		KeyNumpadEnter,
		KeyNumpadEqual,
		KeyNumpadMemoryAdd,
		KeyNumpadMemoryClear,
		KeyNumpadMemoryRecall,
		KeyNumpadMemoryStore,
		KeyNumpadMemorySubtract,
		KeyNumpadMultiply,
		KeyNumpadParenLeft,
		KeyNumpadParenRight,
		KeyNumpadSubtract,
		KeyNumpadSeparator,
		KeyNumpadUp,
		KeyNumpadDown,
		KeyNumpadRight,
		KeyNumpadLeft,
		KeyNumpadBegin,
		KeyNumpadHome,
		KeyNumpadEnd,
		KeyNumpadInsert,
		KeyNumpadDelete,
		KeyNumpadPageUp,
		KeyNumpadPageDown,
		KeyEscape,
		KeyF1,
		KeyF2,
		KeyF3,
		KeyF4,
		KeyF5,
		KeyF6,
		KeyF7,
		KeyF8,
		KeyF9,
		KeyF10,
		KeyF11,
		KeyF12,
		KeyF13,
		KeyF14,
		KeyF15,
		KeyF16,
		KeyF17,
		KeyF18,
		KeyF19,
		KeyF20,
		KeyF21,
		KeyF22,
		KeyF23,
		KeyF24,
		KeyF25,
		KeyFn,
		KeyFnLock,
		KeyPrintScreen,
		KeyScrollLock,
		KeyPause,
		KeyBrowserBack,
		KeyBrowserFavorites,
		KeyBrowserForward,
		KeyBrowserHome,
		KeyBrowserRefresh,
		KeyBrowserSearch,
		KeyBrowserStop,
		KeyEject,
		KeyLaunchApp1,
		KeyLaunchApp2,
		KeyLaunchMail,
		KeyMediaPlayPause,
		KeyMediaSelect,
		KeyMediaStop,
		KeyMediaTrackNext,
		KeyMediaTrackPrevious,
		KeyPower,
		KeySleep,
		KeyAudioVolumeDown,
		KeyAudioVolumeMute,
		KeyAudioVolumeUp,
		KeyWakeUp,
		KeyCopy,
		KeyCut,
		KeyPaste,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value Key) IsKnown() bool {
	return value >= 0 && value <= 175
}

// KeyAction represents the corresponding Zig enum.
type KeyAction uint8

const (
	// KeyActionPress corresponds to the Zig tag press.
	KeyActionPress KeyAction = 0
	// KeyActionRelease corresponds to the Zig tag release.
	KeyActionRelease KeyAction = 1
	// KeyActionRepeat corresponds to the Zig tag repeat.
	KeyActionRepeat KeyAction = 2
)

var zigoKeyActionNames = [3]string{
	0: "press",
	1: "release",
	2: "repeat",
}

// String returns the Zig tag name.
func (value KeyAction) String() string {
	if value >= 0 && value <= 2 {
		return zigoKeyActionNames[uint64(value)]
	}
	return "KeyAction(" + strconv.Itoa(int(value)) + ")"
}

// ParseKeyAction returns the KeyAction named by text, which is a Zig tag name.
func ParseKeyAction(text string) (KeyAction, error) {
	switch text {
	case "press":
		return KeyActionPress, nil
	case "release":
		return KeyActionRelease, nil
	case "repeat":
		return KeyActionRepeat, nil
	}
	return 0, &EnumParseError{Type: "KeyAction", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value KeyAction) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseKeyAction.
func (value *KeyAction) UnmarshalText(text []byte) error {
	parsed, err := ParseKeyAction(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// FocusEvent represents the corresponding Zig enum.
type FocusEvent uint8

const (
	// FocusEventGained corresponds to the Zig tag gained.
	FocusEventGained FocusEvent = 0
	// FocusEventLost corresponds to the Zig tag lost.
	FocusEventLost FocusEvent = 1
)

var zigoFocusEventNames = [2]string{
	0: "gained",
	1: "lost",
}

// String returns the Zig tag name.
func (value FocusEvent) String() string {
	if value >= 0 && value <= 1 {
		return zigoFocusEventNames[uint64(value)]
	}
	return "FocusEvent(" + strconv.Itoa(int(value)) + ")"
}

// ParseFocusEvent returns the FocusEvent named by text, which is a Zig tag name.
func ParseFocusEvent(text string) (FocusEvent, error) {
	switch text {
	case "gained":
		return FocusEventGained, nil
	case "lost":
		return FocusEventLost, nil
	}
	return 0, &EnumParseError{Type: "FocusEvent", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value FocusEvent) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseFocusEvent.
func (value *FocusEvent) UnmarshalText(text []byte) error {
	parsed, err := ParseFocusEvent(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// MouseAction represents the corresponding Zig enum.
type MouseAction int32

const (
	// MouseActionPress corresponds to the Zig tag press.
	MouseActionPress MouseAction = 0
	// MouseActionRelease corresponds to the Zig tag release.
	MouseActionRelease MouseAction = 1
	// MouseActionMotion corresponds to the Zig tag motion.
	MouseActionMotion MouseAction = 2
)

var zigoMouseActionNames = [3]string{
	0: "press",
	1: "release",
	2: "motion",
}

// String returns the Zig tag name.
func (value MouseAction) String() string {
	if value >= 0 && value <= 2 {
		return zigoMouseActionNames[uint64(value)]
	}
	return "MouseAction(" + strconv.Itoa(int(value)) + ")"
}

// ParseMouseAction returns the MouseAction named by text, which is a Zig tag name.
func ParseMouseAction(text string) (MouseAction, error) {
	switch text {
	case "press":
		return MouseActionPress, nil
	case "release":
		return MouseActionRelease, nil
	case "motion":
		return MouseActionMotion, nil
	}
	return 0, &EnumParseError{Type: "MouseAction", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value MouseAction) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseMouseAction.
func (value *MouseAction) UnmarshalText(text []byte) error {
	parsed, err := ParseMouseAction(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// MouseButton represents the corresponding Zig enum.
type MouseButton int32

const (
	// MouseButtonUnknown corresponds to the Zig tag unknown.
	MouseButtonUnknown MouseButton = 0
	// MouseButtonLeft corresponds to the Zig tag left.
	MouseButtonLeft MouseButton = 1
	// MouseButtonRight corresponds to the Zig tag right.
	MouseButtonRight MouseButton = 2
	// MouseButtonMiddle corresponds to the Zig tag middle.
	MouseButtonMiddle MouseButton = 3
	// MouseButtonFour corresponds to the Zig tag four.
	MouseButtonFour MouseButton = 4
	// MouseButtonFive corresponds to the Zig tag five.
	MouseButtonFive MouseButton = 5
	// MouseButtonSix corresponds to the Zig tag six.
	MouseButtonSix MouseButton = 6
	// MouseButtonSeven corresponds to the Zig tag seven.
	MouseButtonSeven MouseButton = 7
	// MouseButtonEight corresponds to the Zig tag eight.
	MouseButtonEight MouseButton = 8
	// MouseButtonNine corresponds to the Zig tag nine.
	MouseButtonNine MouseButton = 9
	// MouseButtonTen corresponds to the Zig tag ten.
	MouseButtonTen MouseButton = 10
	// MouseButtonEleven corresponds to the Zig tag eleven.
	MouseButtonEleven MouseButton = 11
)

var zigoMouseButtonNames = [12]string{
	0:  "unknown",
	1:  "left",
	2:  "right",
	3:  "middle",
	4:  "four",
	5:  "five",
	6:  "six",
	7:  "seven",
	8:  "eight",
	9:  "nine",
	10: "ten",
	11: "eleven",
}

// String returns the Zig tag name.
func (value MouseButton) String() string {
	if value >= 0 && value <= 11 {
		return zigoMouseButtonNames[uint64(value)]
	}
	return "MouseButton(" + strconv.Itoa(int(value)) + ")"
}

// ParseMouseButton returns the MouseButton named by text, which is a Zig tag name.
func ParseMouseButton(text string) (MouseButton, error) {
	switch text {
	case "unknown":
		return MouseButtonUnknown, nil
	case "left":
		return MouseButtonLeft, nil
	case "right":
		return MouseButtonRight, nil
	case "middle":
		return MouseButtonMiddle, nil
	case "four":
		return MouseButtonFour, nil
	case "five":
		return MouseButtonFive, nil
	case "six":
		return MouseButtonSix, nil
	case "seven":
		return MouseButtonSeven, nil
	case "eight":
		return MouseButtonEight, nil
	case "nine":
		return MouseButtonNine, nil
	case "ten":
		return MouseButtonTen, nil
	case "eleven":
		return MouseButtonEleven, nil
	}
	return 0, &EnumParseError{Type: "MouseButton", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value MouseButton) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseMouseButton.
func (value *MouseButton) UnmarshalText(text []byte) error {
	parsed, err := ParseMouseButton(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}
