//! Go bindings for libghostty-vt, generated by zigo.
const zigo = @import("zigo");
const gostty = @import("gostty");

pub const bindings = zigo.define(.{
    .root = gostty,
    .allocator = .smp_allocator,
    .io = "io",
    // ghostty spells codepoints as `u21`; every such parameter and return is
    // a Go `rune`. The `u32` ones that are also codepoints opt in below.
    .codepoints = .infer_u21,
    // Key and mouse encoding is over half the public surface -- the `Key` enum
    // alone is 176 constants -- and nothing on the terminal side names it, so it
    // gets its own package. The dependency runs one way: `input` names
    // `*Terminal`, the root package names nothing from `input`.
    .packages = .{
        // Process-global hooks ghostty needs the embedder for. Their own
        // package so that `sys.Clear` reads as what it is, and because a
        // renderer that never shows images or a program that trusts the
        // platform's entropy never needs to name them.
        .{
            .path = "sys",
            .doc = "Package sys installs the process-global hooks libghostty-vt cannot provide in a library build: a PNG decoder for Kitty graphics and a secure entropy source for Kitty clipboard grants.",
            .types = .{"Handler"},
            .namespaces = .{"sys"},
        },
        .{
            .path = "input",
            .doc = "Package input encodes key, mouse, focus and paste events into the bytes a program reading the pty expects.",
            // A trailing `*` is a prefix pattern: `Key*` covers every key
            // type, and nothing outside this package is named that way. The
            // mouse types are listed instead, because the terminal's own
            // `MouseTracking` and `MouseReportFormat` are state reads that
            // belong to the root package -- pulling them in here would make
            // the two packages import each other.
            .types = .{ "Key*", "MouseAction", "MouseButton", "MouseEvent", "FocusEvent", "RenderSize" },
            .functions = .{
                "root.encodeKey",
                "root.encodeMouse",
                "root.input.encodeFocus",
                "root.input.isSafePaste",
                "root.encodePaste",
                "root.keyFromASCII",
                "root.keyCodepoint",
                "root.keyPrintable",
                "root.keyModifier",
                "root.keyKeypad",
                "root.keyLeftOrRightShift",
                "root.keyLeftOrRightAlt",
                "root.keyCtrlOrSuper",
                "root.keyShouldBeRemappable",
                "root.keyW3C",
                "root.keyFromW3C",
            },
        },
    },

    .types = .{
        .{
            .type = gostty.Terminal,
            .repr = .@"opaque",
            .fields = .{
                .{ .path = "cols" },
                .{ .path = "rows" },
                .{ .path = "screens.active.cursor.x", .name = "cursorX" },
                .{ .path = "screens.active.cursor.y", .name = "cursorY" },
                .{ .path = "screens.active.cursor.cursor_style", .name = "cursorStyle" },
                .{ .path = "screens.active_key", .name = "activeScreenKey" },
                // The LCF: set once printing has filled the last column, so the
                // next print soft-wraps instead of overwriting.
                .{ .path = "screens.active.cursor.pending_wrap", .name = "cursorPendingWrap" },
                .{ .path = "screens.active.cursor.protected", .name = "cursorProtected" },
                .{ .path = "width_px", .name = "widthPx" },
                .{ .path = "height_px", .name = "heightPx" },
                .{ .path = "flags.focused", .name = "focused" },
                .{ .path = "flags.visible", .name = "visible" },
                .{ .path = "flags.password_input", .name = "passwordInput" },
            },
        },
        .{ .type = gostty.Stream, .repr = .@"opaque", .fields = .{
            .{ .path = "inner.handler.semantic_failure", .name = "failed", .doc = "True once a sequence failed in a way the terminal could not absorb, such as an allocation failure. Streams are best-effort and keep going." },
        } },
        .{ .type = gostty.Screen, .repr = .@"opaque" },
        .{ .type = gostty.Search, .repr = .@"opaque" },
        .{ .type = gostty.Snapshot, .repr = .@"opaque", .name = "Snapshot" },
        .{ .type = gostty.SnapshotDecoder, .repr = .@"opaque" },
        .{ .type = gostty.SnapshotProgress, .repr = .value },
        .{ .type = gostty.KeyEvent, .repr = .value, .field_meta = .{ .unshifted_codepoint = .{ .semantic = .codepoint } } },
        .{ .type = gostty.MouseEvent, .repr = .value },
        .{ .type = gostty.KeyMods, .repr = .value },
        .{ .type = gostty.RenderSize, .repr = .value },
        // `.text` gives an enum `Parse<Enum>`, `MarshalText` and `UnmarshalText`,
        // so it can live in a config file or a flag. Enabled for the enums a
        // consumer is likely to name in text: keybinding and mouse input, and
        // the display state an emulator shows or persists.
        .{ .type = gostty.CursorStyle, .repr = .enumeration, .name = "CursorStyle", .text = true },
        .{ .type = gostty.CursorStyleReq, .repr = .enumeration, .name = "CursorStyleReq" },
        .{ .type = gostty.EraseDisplay, .repr = .enumeration, .name = "EraseDisplay" },
        // ghostty leaves these two non-exhaustive so a number from a pty never
        // fails `@enumFromInt`; carry that through to Go rather than closing it.
        .{ .type = gostty.EraseLine, .repr = .enumeration, .name = "EraseLine", .text = true, .exhaustive = false },
        .{ .type = gostty.TabClear, .repr = .enumeration, .name = "TabClear", .text = true, .exhaustive = false },
        .{ .type = gostty.ProtectedMode, .repr = .enumeration, .name = "ProtectedMode" },
        .{ .type = gostty.ScreenKey, .repr = .enumeration, .name = "ScreenKey" },
        .{ .type = gostty.SwitchScreenMode, .repr = .enumeration, .name = "SwitchScreenMode" },
        .{ .type = gostty.Mode, .repr = .enumeration, .name = "Mode", .text = true },
        .{ .type = gostty.Selection, .repr = .value },
        .{ .type = gostty.FormatterFormat, .repr = .enumeration, .name = "FormatterFormat", .text = true },
        .{ .type = gostty.FormatOptions, .repr = .value },
        .{ .type = gostty.SelectionAdjustment, .repr = .enumeration, .name = "SelectionAdjustment", .text = true },
        .{ .type = gostty.StreamEvent, .repr = .enumeration, .name = "StreamEvent", .text = true },
        .{ .type = gostty.ProgressState, .repr = .enumeration, .name = "ProgressState", .text = true },
        .{ .type = gostty.ColorScheme, .repr = .enumeration, .name = "ColorScheme", .text = true },
        .{ .type = gostty.DragEvent, .repr = .enumeration, .name = "DragEvent", .text = true },
        .{ .type = gostty.DragOperation, .repr = .enumeration, .name = "DragOperation", .text = true },
        .{ .type = gostty.DragOperations, .repr = .value },
        .{ .type = gostty.DragMove, .repr = .value },
        .{ .type = gostty.DragFn, .repr = .callback, .name = "DragHandler" },
        .{ .type = gostty.ClipboardLocation, .repr = .enumeration, .name = "ClipboardLocation", .text = true, .exhaustive = false },
        .{ .type = gostty.ClipboardDenial, .repr = .enumeration, .name = "ClipboardDenial" },
        .{ .type = gostty.ClipboardFn, .repr = .callback, .name = "ClipboardHandler" },
        .{ .type = gostty.SysFn, .repr = .callback, .name = "Handler" },
        .{ .type = gostty.Underline, .repr = .enumeration, .name = "Underline" },
        .{ .type = gostty.ColorName, .repr = .enumeration, .name = "ColorName", .text = true, .exhaustive = false },
        .{ .type = gostty.Attribute, .repr = .tagged_union },
        .{ .type = gostty.SearchDirection, .repr = .enumeration, .name = "SearchDirection" },
        .{ .type = gostty.SearchScroll, .repr = .enumeration, .name = "SearchScroll" },
        .{ .type = gostty.SearchState, .repr = .enumeration, .name = "SearchState" },
        .{ .type = gostty.SearchProgress, .repr = .enumeration, .name = "SearchProgress" },
        .{ .type = gostty.Scrollbar, .repr = .value },
        .{ .type = gostty.Key, .repr = .enumeration, .name = "Key", .text = true },
        .{ .type = gostty.KeyAction, .repr = .enumeration, .name = "KeyAction", .text = true },
        .{ .type = gostty.FocusEvent, .repr = .enumeration, .name = "FocusEvent", .text = true },
        .{ .type = gostty.MouseAction, .repr = .enumeration, .name = "MouseAction", .text = true },
        .{ .type = gostty.MouseButton, .repr = .enumeration, .name = "MouseButton", .text = true },
        .{ .type = gostty.Charset, .repr = .enumeration, .name = "Charset" },
        .{ .type = gostty.CharsetSlot, .repr = .enumeration, .name = "CharsetSlot" },
        .{ .type = gostty.CharsetActiveSlot, .repr = .enumeration, .name = "CharsetActiveSlot" },
        .{ .type = gostty.DeccolmMode, .repr = .enumeration, .name = "DeccolmMode" },
        .{ .type = gostty.ScrollViewport, .repr = .tagged_union },
        .{ .type = gostty.RenderState, .repr = .@"opaque", .fields = .{
            .{ .path = "rows" },
            .{ .path = "cols" },
            .{ .path = "cursor.visible", .name = "cursorVisible" },
            .{ .path = "cursor.visual_style", .name = "cursorStyle" },
            .{ .path = "cursor.blinking", .name = "cursorBlinking" },
            .{ .path = "cursor.password_input", .name = "cursorPasswordInput" },
        } },
        .{ .type = gostty.RenderCell, .repr = .value, .field_meta = .{ .codepoint = .{ .semantic = .codepoint } } },
        // An integer-backed packed struct: Go sees named fields, the C ABI sees
        // one u32.
        .{ .type = gostty.CellFlags, .repr = .value },
        .{ .type = gostty.CellWidth, .repr = .enumeration, .name = "CellWidth" },
        .{ .type = gostty.RenderDirty, .repr = .enumeration, .name = "RenderDirty" },
        .{ .type = gostty.KittyImages, .repr = .@"opaque", .fields = .{
            .{ .path = "generation" },
        } },
        .{ .type = gostty.KittyLayer, .repr = .enumeration, .name = "KittyLayer", .text = true },
        .{ .type = gostty.KittyPlacement, .repr = .value },
        .{ .type = gostty.KittyImage, .repr = .value },
        .{ .type = gostty.KittyFormat, .repr = .enumeration, .name = "KittyFormat" },
        .{ .type = gostty.KittyCompression, .repr = .enumeration, .name = "KittyCompression" },

        // Terminal configuration and state reads.
        .{ .type = gostty.ScrollRegion, .repr = .value },
        .{ .type = gostty.MouseTracking, .repr = .enumeration, .name = "MouseTracking", .text = true },
        .{ .type = gostty.MouseReportFormat, .repr = .enumeration, .name = "MouseReportFormat", .text = true },
        .{ .type = gostty.ModeReport, .repr = .enumeration, .name = "ModeReport", .text = true },

        // Selection gestures.
        .{ .type = gostty.Gesture, .repr = .@"opaque" },
        .{ .type = gostty.GestureBehavior, .repr = .enumeration, .name = "GestureBehavior", .text = true },
        .{ .type = gostty.GestureAutoscroll, .repr = .enumeration, .name = "GestureAutoscrollDirection", .text = true },
        .{ .type = gostty.GestureGeometry, .repr = .value },
        .{ .type = gostty.GesturePressEvent, .repr = .value },
        .{ .type = gostty.GestureDragEvent, .repr = .value },

        // The standalone parsers.
        .{ .type = gostty.OSCParser, .repr = .@"opaque", .name = "OSCParser" },
        .{ .type = gostty.OSCCommand, .repr = .enumeration, .name = "OSCCommand", .text = true },
        .{ .type = gostty.OSCTerminator, .repr = .enumeration, .name = "OSCTerminator", .text = true },
        .{ .type = gostty.SemanticPromptAction, .repr = .enumeration, .name = "SemanticPromptAction", .text = true },
        .{ .type = gostty.SgrAttributeTag, .repr = .enumeration, .name = "SgrAttributeTag", .text = true },
        .{ .type = gostty.SgrAttribute, .repr = .value },
    },
    .functions = .{
        .{ .path = "root.unicode.codepointWidth" },
        .{ .path = "root.graphemeWidth", .params = .{"cps"}, .param_meta = .{ .cps = .{ .semantic = .codepoint } } },

        // Input encoding.
        .{ .path = "root.encodeKey", .params = .{ "writer", "terminal", "event", "utf8" }, .param_meta = .{ .utf8 = .{ .semantic = .utf8_string } } },
        .{ .path = "root.encodeMouse", .params = .{ "writer", "terminal", "event", "size", "any_button_pressed" } },
        // What a key is, for a caller mapping platform key codes onto ghostty's
        // enum or deciding whether a press can carry text. Wrappers: `Key` is
        // an enum, and zigo binds functions on structs and opaque types only.
        .{ .path = "root.keyFromASCII", .params = .{"ch"}, .covers = "Key.fromASCII" },
        .{ .path = "root.keyCodepoint", .params = .{"key"}, .covers = "Key.codepoint" },
        .{ .path = "root.keyPrintable", .params = .{"key"}, .covers = "Key.printable" },
        .{ .path = "root.keyModifier", .params = .{"key"}, .covers = "Key.modifier" },
        .{ .path = "root.keyKeypad", .params = .{"key"}, .covers = "Key.keypad" },
        .{ .path = "root.keyLeftOrRightShift", .params = .{"key"}, .covers = "Key.leftOrRightShift" },
        .{ .path = "root.keyLeftOrRightAlt", .params = .{"key"}, .covers = "Key.leftOrRightAlt" },
        .{ .path = "root.keyCtrlOrSuper", .params = .{"key"}, .covers = "Key.ctrlOrSuper" },
        .{ .path = "root.keyShouldBeRemappable", .params = .{"key"}, .covers = "Key.shouldBeRemappable" },
        .{ .path = "root.keyW3C", .params = .{"key"}, .semantic = .utf8_string, .covers = "Key.w3c" },
        .{ .path = "root.keyFromW3C", .params = .{"w3c_code"}, .param_meta = .{ .w3c_code = .{ .semantic = .utf8_string } }, .covers = "Key.fromW3C" },
        // ghostty's own encoders, reached through the `input` namespace.
        .{ .path = "root.input.encodeFocus", .params = .{ "writer", "event" } },
        .{ .path = "root.input.isSafePaste", .params = .{"data"} },
        .{ .path = "root.encodePaste", .params = .{ "writer", "terminal", "data" } },

        // Lifecycle. `Terminal.init` returns by value and takes an `Options`
        // whose `colors` field holds optionals that cannot cross the C ABI.
        // `.flatten` picks the two fields that can and leaves the rest at their
        // Zig defaults, so ghostty's own constructor is bound without a wrapper.
        .{
            .path = "Terminal.init",
            .constructs = "Terminal",
            .name = "newTerminal",
            .params = .{"opts"},
            .param_meta = .{ .opts = .{ .flatten = .{ "cols", "rows" } } },
        },
        .{ .path = "Terminal.deinit", .destroys = "Terminal" },
        .{ .path = "root.freeString", .params = .{"str"} },
        // A stream borrows its terminal: ghostty's handler reaches through it for
        // an allocator when it tears down, so the terminal must outlive it.
        .{ .path = "root.newStream", .constructs = "Stream", .child_of_receiver = true, .params = .{"continuation_max_bytes"} },
        .{ .path = "root.freeStream", .destroys = "Stream" },
        .{ .path = "Stream.feed", .params = .{"bytes"} },
        // `Events` is the range-over-func form: `for event, err := range s.Events()`.
        .{ .path = "Stream.nextEvent", .iterator = .{ .name = "Events" } },
        .{ .path = "Stream.eventTitle", .semantic = .utf8_string },
        .{ .path = "Stream.eventBody", .semantic = .utf8_string },
        .{ .path = "Stream.eventProgressState" },
        .{ .path = "Stream.eventProgress" },
        .{ .path = "Stream.eventSequence" },
        .{ .path = "Stream.setUnknownMaxBytes", .params = .{"max"} },
        .{ .path = "Stream.setVersionReport", .params = .{ "name", "version" }, .param_meta = .{ .name = .{ .semantic = .utf8_string }, .version = .{ .semantic = .utf8_string } } },
        .{ .path = "Stream.setEnquiryResponse", .params = .{"reply"}, .param_meta = .{ .reply = .{ .semantic = .utf8_string } } },
        .{ .path = "Stream.colorSchemeChanged", .params = .{"scheme"} },
        .{ .path = "Stream.clearColorScheme" },

        // Kitty drag and drop. The handler takes its whole payload as
        // arguments: everything is a scalar, so the signature carries it and
        // there is nothing to read back afterwards -- which also means the
        // acceptance is the one being reported rather than whatever a later
        // event in the same feed replaced it with.
        .{
            .path = "root.onDrag",
            .params = .{ "callback", "userdata" },
            .param_meta = .{ .callback = .{
                .retention = .retained,
                .reentrancy = .allowed,
                .thread = .caller,
            } },
        },
        .{ .path = "root.dragEvent" },
        .{ .path = "root.dragAccepted" },
        .{ .path = "root.dragActive" },
        .{ .path = "root.dragRegisteredMimes", .semantic = .utf8_string },
        .{ .path = "root.dragClientAccepted" },
        .{ .path = "root.dragMove", .params = .{ "ev", "mimes" }, .param_meta = .{ .mimes = .{ .semantic = .utf8_string } } },
        .{ .path = "root.dragLeave" },
        .{ .path = "root.dragAddItem", .params = .{ "mime", "data" }, .param_meta = .{ .mime = .{ .semantic = .utf8_string } } },
        .{ .path = "root.dragDrop", .params = .{"ev"} },
        .{ .path = "root.dragClearItems" },
        // A clipboard request runs while `feed` is on the stack, on the thread
        // that called it, and the callback is expected to answer it by calling
        // back into the same stream. Both facts are contracts a caller has to
        // know, so they are declared rather than left to the prose.
        .{
            .path = "Stream.onClipboardWriteRequest",
            .params = .{ "callback", "userdata" },
            .param_meta = .{ .callback = .{
                .retention = .retained,
                .reentrancy = .allowed,
                .thread = .caller,
            } },
        },
        .{
            .path = "Stream.onClipboardReadRequest",
            .params = .{ "callback", "userdata" },
            .param_meta = .{ .callback = .{
                .retention = .retained,
                .reentrancy = .allowed,
                .thread = .caller,
            } },
        },
        .{ .path = "Stream.clipboardLocation" },
        .{ .path = "Stream.clipboardName", .semantic = .utf8_string },
        .{ .path = "Stream.clipboardGranted" },
        .{ .path = "Stream.clipboardCanRemember" },
        .{ .path = "Stream.clipboardContentCount" },
        .{ .path = "Stream.clipboardContentMime", .params = .{"index"}, .semantic = .utf8_string },
        .{ .path = "Stream.clipboardContentData", .params = .{"index"} },
        .{ .path = "Stream.clipboardMimeCount" },
        .{ .path = "Stream.clipboardMime", .params = .{"index"}, .semantic = .utf8_string },
        .{ .path = "Stream.allowClipboard", .params = .{"remember"} },
        .{ .path = "Stream.replyClipboardText", .params = .{ "text", "remember" }, .param_meta = .{ .text = .{ .semantic = .utf8_string } } },
        .{ .path = "Stream.denyClipboard", .params = .{"reason"} },
        .{ .path = "Stream.writeContinuation", .params = .{"writer"} },
        .{ .path = "Stream.hasReplies" },
        .{ .path = "Stream.writeSnapshot", .params = .{"writer"} },
        .{ .path = "Stream.writeReplies", .params = .{"writer"} },

        // ghostty's own methods, bound directly.
        .{ .path = "Terminal.printString", .params = .{"str"}, .param_meta = .{ .str = .{ .semantic = .utf8_string } } },
        .{ .path = "Terminal.plainString", .returns = .caller, .release = "root.freeString", .semantic = .utf8_string },
        .{ .path = "Terminal.setCursorStyle", .params = .{"value"} },
        .{ .path = "Terminal.setCursorPos", .params = .{ "row_req", "col_req" } },
        .{ .path = "Terminal.carriageReturn" },
        .{ .path = "Terminal.linefeed" },
        .{ .path = "Terminal.backspace" },
        .{ .path = "Terminal.cursorIsAtPrompt" },
        .{ .path = "Terminal.fullReset" },
        // Returns the screen being left, borrowed, or absent when `key` was
        // already active.
        .{ .path = "Terminal.switchScreen", .params = .{"key"}, .returns = .borrowed },
        .{ .path = "Terminal.switchScreenMode", .params = .{ "mode", "enabled" } },
        .{ .path = "root.activeScreen", .returns = .borrowed },
        .{ .path = "root.screen", .returns = .borrowed, .params = .{"key"} },
        // Screen is ghostty's own type, so these cannot be written as methods
        // on it; the group attaches them and drops the shared `screen` prefix.
        .{
            .receiver = "Screen",
            .strip_prefix = "screen",
            .functions = .{
                .{ .path = "root.screenSelectAll", .covers = "Screen.selectAll" },
                "root.screenHasSelection",
                .{ .path = "root.screenSelectRange", .params = .{ "x1", "y1", "x2", "y2", "rectangle" }, .covers = "Screen.select" },

                .{ .path = "root.screenSelectWord", .params = .{ "x", "y", "boundaries" }, .covers = "Screen.selectWord" },
                .{ .path = "root.screenSelectLine", .params = .{ "x", "y" }, .covers = "Screen.selectLine" },
                .{ .path = "root.screenSelectOutput", .params = .{ "x", "y" }, .covers = "Screen.selectOutput" },
                .{ .path = "root.screenSelectionString", .returns = .caller, .release = "root.freeString", .semantic = .utf8_string, .covers = "Screen.selectionString" },
                "root.screenSelection",
                .{ .path = "root.screenSetSelection", .params = .{"sel"} },
                "root.screenViewportTop",
                "root.screenScrollbar",
                .{ .path = "root.screenFormat", .params = .{ "opts", "writer" } },
                .{ .path = "root.screenFormatSelection", .params = .{ "opts", "sel", "writer" } },
                .{ .path = "root.screenSelectionContains", .params = .{ "sel", "x", "y" } },
                .{ .path = "root.screenSelectionAdjust", .params = .{ "sel", "adjustment" } },
                .{ .path = "root.screenStartHyperlink", .params = .{ "uri", "id" }, .param_meta = .{ .uri = .{ .semantic = .utf8_string }, .id = .{ .semantic = .utf8_string } }, .covers = "Screen.startHyperlink" },
            },
        },
        // ghostty takes the screen by value here; zigo 0.8.0 passes the handle and
        // the shim copies, so no wrapper is needed.
        .{ .path = "Screen.viewportIsBottom" },
        .{ .path = "Screen.clearSelection" },
        .{ .path = "Screen.endHyperlink" },
        // `newSearch` returns by value, like `Terminal.init`: zigo boxes the
        // result and frees the box in `close`.
        .{ .path = "root.newSearch", .constructs = "Search", .child_of_receiver = true, .params = .{"needle_unowned"}, .param_meta = .{ .needle_unowned = .{ .semantic = .utf8_string } } },
        .{ .path = "root.searchClose", .destroys = "Search" },
        .{
            .receiver = "Search",
            .strip_prefix = "search",
            .functions = .{
                .{ .path = "root.searchNeedle", .semantic = .utf8_string },
                "root.searchStatus",
                "root.searchTick",
                .{ .path = "root.searchFeed", .params = .{"active_dirty"} },
                "root.searchAll",
                .{ .path = "root.searchSelect", .params = .{ "to", "scroll" } },
                .{ .path = "root.searchMatchCount" },
                .{
                    .path = "root.searchMatches",
                    .params = .{"dst"},
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
                .{
                    .path = "root.searchViewportMatches",
                    .params = .{"dst"},
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
                "root.searchSelectedMatch",
                "root.searchSelectedIndex",
            },
        },
        .{
            .path = "root.printAttributesInto",
            .params = .{"dst"},
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
            .covers = "Terminal.printAttributes",
        },
        .{ .path = "root.historyString", .returns = .caller, .release = "root.freeString", .semantic = .utf8_string, .covers = "Screen.dumpStringAlloc" },

        // Cursor movement.
        .{ .path = "Terminal.cursorUp", .params = .{"count_req"} },
        .{ .path = "Terminal.cursorDown", .params = .{"count_req"} },
        .{ .path = "Terminal.cursorLeft", .params = .{"count_req"} },
        .{ .path = "Terminal.cursorRight", .params = .{"count_req"} },
        .{ .path = "Terminal.saveCursor" },
        .{ .path = "Terminal.restoreCursor" },
        .{ .path = "Terminal.index" },
        .{ .path = "Terminal.reverseIndex" },

        // Tab stops.
        .{ .path = "Terminal.horizontalTab" },
        .{ .path = "Terminal.horizontalTabBack" },
        .{ .path = "Terminal.tabSet" },
        .{ .path = "Terminal.tabReset" },
        .{ .path = "Terminal.tabClear", .params = .{"cmd"} },

        // Scrolling and margins.
        .{ .path = "Terminal.scrollUp", .params = .{"count"} },
        .{ .path = "Terminal.scrollDown", .params = .{"count"} },
        .{ .path = "Terminal.setTopAndBottomMargin", .params = .{ "top_req", "bottom_req" } },
        .{ .path = "Terminal.setLeftAndRightMargin", .params = .{ "left_req", "right_req" } },
        .{ .path = "root.setScrollbackMaxBytes", .params = .{"max"}, .covers = "Terminal.setScrollbackMaxBytes" },
        .{ .path = "root.clearScrollbackMaxBytes" },
        .{ .path = "root.setScrollbackMaxLines", .params = .{"max"}, .covers = "Terminal.setScrollbackMaxLines" },
        .{ .path = "root.clearScrollbackMaxLines" },

        // Editing.
        .{ .path = "Terminal.insertLines", .params = .{"count"} },
        .{ .path = "Terminal.deleteLines", .params = .{"count"} },
        .{ .path = "Terminal.insertBlanks", .params = .{"count"} },
        .{ .path = "Terminal.deleteChars", .params = .{"count_req"} },
        .{ .path = "Terminal.eraseChars", .params = .{"count_req"} },
        .{ .path = "Terminal.eraseLine", .params = .{ "mode", "protected_req" } },
        .{ .path = "Terminal.eraseDisplay", .params = .{ "mode", "protected_req" } },
        .{ .path = "Terminal.decaln" },

        // Printing.
        .{ .path = "Terminal.print", .params = .{"c"} },
        .{ .path = "Terminal.printRepeat", .params = .{"count_req"} },
        .{ .path = "Terminal.printSlice", .params = .{"cps"}, .param_meta = .{ .cps = .{ .semantic = .codepoint } } },

        // Metadata the terminal tracks for the shell.
        .{ .path = "root.formatTerminal", .name = "Format", .params = .{ "opts", "writer" } },
        // Snapshots.
        .{ .path = "root.decodeSnapshot", .name = "DecodeSnapshot", .constructs = "Snapshot", .params = .{ "reader", "max_continuation_bytes" } },
        .{ .path = "Snapshot.deinit", .destroys = "Snapshot" },
        // The incremental form: `ready` hands over a drawable terminal, then
        // `next` prepends the scrollback a page at a time.
        .{ .path = "root.newSnapshotDecoder", .constructs = "SnapshotDecoder", .params = .{"data"} },
        .{ .path = "root.freeSnapshotDecoder", .destroys = "SnapshotDecoder" },
        .{
            .receiver = "SnapshotDecoder",
            .strip_prefix = "snapshotDecoder",
            .functions = .{
                .{ .path = "root.snapshotDecoderReady", .params = .{"max_continuation_bytes"} },
                .{ .path = "root.snapshotDecoderRestoreInto", .params = .{"term"} },
                .{ .path = "root.snapshotDecoderContinuation" },
                .{ .path = "root.snapshotDecoderNext", .params = .{"term"} },
            },
        },
        .{
            .receiver = "Snapshot",
            .strip_prefix = "snapshot",
            .functions = .{
                .{ .path = "root.snapshotRestoreInto", .params = .{"term"} },
                "root.snapshotContinuation",
            },
        },
        // Colors and modes.
        .{ .path = "root.backgroundColor" },
        .{ .path = "root.foregroundColor" },
        .{ .path = "root.cursorColor" },
        .{
            .path = "root.paletteColors",
            .params = .{"dst"},
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },
        .{ .path = "root.setDefaultBackgroundColor", .params = .{"rgb"} },
        .{ .path = "root.setDefaultForegroundColor", .params = .{"rgb"} },
        .{ .path = "root.setDefaultCursorColor", .params = .{"rgb"} },
        .{ .path = "root.colorNameDefault", .params = .{"name"}, .covers = "ColorName.default" },
        .{ .path = "root.modeEnabled", .params = .{"mode"} },
        .{ .path = "root.setMode", .params = .{ "mode", "value" } },
        .{ .path = "Terminal.setPwd", .params = .{"pwd"}, .param_meta = .{ .pwd = .{ .semantic = .utf8_string } } },
        .{ .path = "Terminal.getPwd", .semantic = .utf8_string },
        .{ .path = "Terminal.getTitle", .semantic = .utf8_string },
        .{ .path = "Terminal.setTitle", .params = .{"t"}, .param_meta = .{ .t = .{ .semantic = .utf8_string } } },
        .{ .path = "root.setAttribute", .params = .{"attr"}, .covers = "Terminal.setAttribute" },
        .{ .path = "Terminal.setProtectedMode", .params = .{"mode"} },
        .{ .path = "Terminal.setDefaultCursorStyle", .params = .{"configured_style"} },
        .{ .path = "root.setDefaultCursorBlink", .params = .{"blink"}, .covers = "Terminal.setDefaultCursorBlink" },
        .{ .path = "root.resetDefaultCursorBlink" },
        .{ .path = "Terminal.configureCharset", .params = .{ "slot", "set" } },
        .{ .path = "Terminal.invokeCharset", .params = .{ "active", "slot", "single" } },
        .{ .path = "Terminal.deccolm", .params = .{"mode"} },
        .{ .path = "Terminal.scrollViewport", .params = .{"behavior"} },
        .{ .path = "Terminal.compressionActivity" },
        .{ .path = "root.resize", .params = .{ "width", "height" }, .covers = "Terminal.resize" },
        .{ .path = "root.resizeCells", .params = .{ "width", "height", "cell_width", "cell_height" } },

        // Rendering. `RenderState` is ghostty's own renderer-facing snapshot;
        // a frame is one `update` plus one `cells` crossing.
        .{ .path = "root.newRenderState", .constructs = "RenderState" },
        .{ .path = "RenderState.update", .params = .{"t"}, .covers = .{ "RenderState.beginUpdate", "RenderState.endUpdate" } },
        .{ .path = "RenderState.clean" },
        .{ .path = "RenderState.deinit", .destroys = "RenderState" },
        .{
            .receiver = "RenderState",
            .strip_prefix = "render",
            .functions = .{
                "root.renderCellCount",
                .{
                    .path = "root.renderCells",
                    .params = .{"dst"},
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
                "root.renderBackground",
                "root.renderForeground",
                "root.renderCursorX",
                "root.renderCursorY",
                "root.renderCursorWideTail",
                "root.renderCursorColor",
                // Partial redraw: which rows changed, one row's cells, and
                // marking them drawn.
                "root.renderDirty",
                .{
                    .path = "root.renderDirtyRows",
                    .params = .{"dst"},
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
                .{
                    .path = "root.renderRowCells",
                    .params = .{ "y", "dst" },
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
                .{
                    .path = "root.renderGraphemes",
                    .params = .{ "x", "y", "dst" },
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return", .semantic = .codepoint } },
                },
                .{ .path = "root.renderHyperlinkAt", .params = .{ "x", "y" }, .returns = .caller, .release = "root.freeString", .semantic = .utf8_string, .covers = "RenderState.linkCells" },
            },
        },

        // Kitty graphics. `KittyImages` is the same kind of snapshot as
        // `RenderState`, for the images rather than the cells: one `update` and
        // one `placements` crossing per frame, with the pixels fetched by id
        // only when their generation says they changed.
        .{ .path = "root.newKittyImages", .constructs = "KittyImages" },
        .{ .path = "root.freeKittyImages", .destroys = "KittyImages" },
        .{
            .receiver = "KittyImages",
            .strip_prefix = "kitty",
            .functions = .{
                .{ .path = "root.kittyUpdate", .params = .{"term"} },
                "root.kittyPlacementCount",
                .{
                    .path = "root.kittyPlacements",
                    .params = .{"dst"},
                    .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
                },
            },
        },
        .{ .path = "Terminal.setKittyGraphicsSizeLimit", .params = .{"limit"} },
        .{
            .path = "root.setKittyGraphicsLoadingLimits",
            .params = .{ "file", "temp_dir", "shared_memory" },
            .param_meta = .{ .temp_dir = .{ .semantic = .utf8_string } },
            .covers = "Terminal.setKittyGraphicsLoadingLimits",
        },
        .{ .path = "root.kittyImage", .params = .{"image_id"} },
        .{
            .path = "root.kittyImageData",
            .params = .{ "image_id", "dst" },
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },

        // System hooks: process-global, answered from inside the callback the
        // same way a clipboard request is. They live in a namespace so that one
        // `clear` is the release zigo requires for the retained callbacks.
        .{
            .path = "root.sys.onPngDecodeRequest",
            .params = .{ "callback", "userdata" },
            .param_meta = .{ .callback = .{
                .retention = .retained,
                .reentrancy = .allowed,
                .thread = .caller,
            } },
        },
        .{
            .path = "root.sys.pngRequestData",
            .params = .{"dst"},
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },
        .{ .path = "root.sys.replyPngImage", .params = .{ "width", "height", "rgba" } },
        .{
            .path = "root.sys.onSecureRandomRequest",
            .params = .{ "callback", "userdata" },
            .param_meta = .{ .callback = .{
                .retention = .retained,
                .reentrancy = .allowed,
                .thread = .caller,
            } },
        },
        .{ .path = "root.sys.clear" },
        .{ .path = "root.sys.replySecureRandom", .params = .{"bytes"} },

        // Terminal configuration: what the embedder sets underneath whatever
        // a program on the pty asks for.
        .{ .path = "root.paletteColor", .params = .{"idx"} },
        .{ .path = "root.setPaletteColor", .params = .{ "idx", "rgb" } },
        .{ .path = "root.resetPaletteColor", .params = .{"idx"} },
        .{ .path = "root.resetPalette" },
        .{ .path = "root.setDefaultPaletteColor", .params = .{ "idx", "rgb" } },
        .{ .path = "root.resetDefaultPalette" },
        .{ .path = "root.setDefaultMode", .params = .{ "mode", "value" } },
        .{ .path = "root.resetModes" },
        .{ .path = "root.saveMode", .params = .{"mode"} },
        .{ .path = "root.restoreMode", .params = .{"mode"} },
        .{ .path = "root.setTabstop", .params = .{"col"} },
        .{ .path = "root.unsetTabstop", .params = .{"col"} },
        .{ .path = "root.resetTabstops", .params = .{"interval"} },

        // Terminal state reads: the gets for state the bindings could already
        // set, plus the resolved values no single mode flag reports.
        .{ .path = "root.scrollRegion" },
        .{ .path = "root.charset", .params = .{"slot"} },
        .{ .path = "root.charsetGL" },
        .{ .path = "root.charsetGR" },
        .{ .path = "root.charsetSingleShift" },
        .{ .path = "root.protectedMode" },
        .{ .path = "root.mouseTracking" },
        .{ .path = "root.mouseTrackingSendsMotion" },
        .{ .path = "root.mouseReportFormat" },
        .{ .path = "root.modeReport", .params = .{ "mode", "ansi" } },

        // Selection gestures. Like `Search`, a gesture borrows its terminal --
        // it holds a tracked pin inside it and hands it back on every call --
        // so it is a child handle and closes first.
        .{ .path = "root.newGesture", .constructs = "Gesture", .child_of_receiver = true },
        .{ .path = "root.gestureClose", .destroys = "Gesture" },
        .{
            .receiver = "Gesture",
            .strip_prefix = "gesture",
            .functions = .{
                .{ .path = "root.gestureSetBehaviors", .params = .{ "single_click", "double_click", "triple_click" } },
                .{ .path = "root.gestureSetWordBoundaries", .params = .{"boundaries"} },
                .{ .path = "root.gestureSetGeometry", .params = .{"geometry"} },
                .{ .path = "root.gesturePress", .params = .{"p"} },
                .{ .path = "root.gestureDrag", .params = .{"d"} },
                "root.gestureAutoscroll",
                .{ .path = "root.gestureAutoscrollTick", .params = .{"d"} },
                .{ .path = "root.gestureDeepPress" },
                .{ .path = "root.gestureRelease", .params = .{ "x", "y" } },
                .{ .path = "root.gestureReset" },
                "root.gestureClickCount",
                "root.gestureDragged",
            },
        },

        // The standalone parsers. `Stream` needs a `Terminal` behind it; these
        // two parse a sequence and hand back what it said, with no terminal
        // state involved at all.
        .{ .path = "root.newOSCParser", .constructs = "OSCParser" },
        .{ .path = "root.freeOSCParser", .destroys = "OSCParser" },
        .{
            .receiver = "OSCParser",
            .strip_prefix = "",
            .functions = .{
                .{ .path = "root.OSCParser.feed", .params = .{"bytes"} },
                .{ .path = "root.OSCParser.end", .params = .{"terminator"} },
                "root.OSCParser.reset",
                "root.OSCParser.command",
                // The strings below are borrowed from the parser and stay valid
                // only until the next feed, end or reset, which is why none of
                // them declare a release function.
                .{ .path = "root.OSCParser.windowTitle", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.icon", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.pwd", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.hyperlinkURI", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.hyperlinkID", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.notificationTitle", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.notificationBody", .semantic = .utf8_string },
                .{ .path = "root.OSCParser.clipboardData", .semantic = .utf8_string },
                "root.OSCParser.clipboardSelection",
                .{ .path = "root.OSCParser.mouseShape", .semantic = .utf8_string },
                "root.OSCParser.semanticPromptAction",
                .{ .path = "root.OSCParser.semanticPromptOptions", .semantic = .utf8_string },
                "root.OSCParser.progressState",
                "root.OSCParser.progressValue",
            },
        },
        .{ .path = "root.sgrAttributeCount", .params = .{ "params", "colon_mask" } },
        .{
            .path = "root.sgrAttributes",
            .params = .{ "params", "colon_mask", "dst" },
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },
    },
});
