//! Go bindings for libghostty-vt, generated by zigo.
const zigo = @import("zigo");
const gostty = @import("gostty");

/// One Go enum, named once.
///
/// Every enum here spells its Go name rather than letting zigo derive one:
/// ghostty builds most of them through `lib.Enum`, whose `@typeName` is a
/// generic instantiation with no usable short name. Taking the declaration by
/// name means the Go name and the declaration it comes from cannot drift.
///
/// `.text` asks for `Parse<Enum>`, `MarshalText` and `UnmarshalText`, so the
/// enum can live in a config file or a flag; it is on for the enums a consumer
/// is likely to name in text. `.open` carries through an enum ghostty leaves
/// non-exhaustive so that a number arriving from a pty never fails
/// `@enumFromInt`.
fn enumeration(comptime name: []const u8, comptime opts: struct {
    text: bool = false,
    open: bool = false,
}) zigo.Type {
    return .{ .enumeration = .{
        .type = @field(gostty, name),
        .name = name,
        .text = opts.text,
        .exhaustive = !opts.open,
    } };
}

/// One Go callback type. Every callback here is retained by the stream that
/// takes it, may re-enter the bindings, and runs on the thread that fed the
/// bytes; the name is required because a function-pointer alias has none of
/// its own to derive.
fn callback(comptime decl: []const u8, comptime go_name: []const u8) zigo.Type {
    return .{ .callback = .{
        .type = @field(gostty, decl),
        .name = go_name,
        .retention = .retained,
        .reentrancy = .allowed,
        .thread = .caller,
    } };
}

/// A caller-provided buffer the function fills and reports the length of.
const out: zigo.Param = .{ .direction = .out, .written = .result };
/// A parameter or result that is bytes rather than text, which inference
/// cannot tell apart on its own.
const bytes: zigo.Param = .{ .semantic = .opaque_bytes };
/// A parameter zigo names and shapes from the source, kept to hold a position.
const any: zigo.Param = .{};

pub const bindings = zigo.define(.{
    .root = gostty,
    .allocator = .smp_allocator,
    .io = .{ .path = "io" },
    // ghostty spells codepoints as `u21`; every such parameter and return is
    // a Go `rune`. The `u32` ones that are also codepoints opt in below.
    .codepoints = .infer_u21,
    // Every plain `[]const u8` this library hands over or takes back is text:
    // titles, URIs, needles, VT sequences. Inferring it keeps the spelling out
    // of every entry below; `.semantic = .opaque_bytes` opts a byte buffer out.
    .strings = .infer_utf8,
    // Every caller-owned string here is allocator memory `freeString` hands
    // back, so it is the default rather than a spelling per entry.
    .string_release = "root.freeString",
    // Key and mouse encoding is over half the public surface -- the `Key` enum
    // alone is 176 constants -- and nothing on the terminal side names it, so it
    // gets its own package. The dependency runs one way: `input` names
    // `*Terminal`, the root package names nothing from `input`.
    .packages = &.{
        // Process-global hooks ghostty needs the embedder for. Their own
        // package so that `sys.Clear` reads as what it is, and because a
        // renderer that never shows images or a program that trusts the
        // platform's entropy never needs to name them.
        .{
            .path = "sys",
            .doc = "Package sys installs the process-global hooks libghostty-vt cannot provide in a library build: a PNG decoder for Kitty graphics and a secure entropy source for Kitty clipboard grants.",
            .types = &.{ "PngDecodeHandler", "SecureRandomHandler" },
            .namespaces = &.{"sys"},
        },
        .{
            .path = "input",
            .doc = "Package input encodes key, mouse, focus and paste events into the bytes a program reading the pty expects.",
            // A trailing `*` is a prefix pattern: `Key*` covers every key
            // type, and nothing outside this package is named that way. The
            // mouse types are listed instead, because the terminal's own
            // `MouseTracking` and `MouseReportFormat` are state reads that
            // belong to the root package -- pulling them in here would make
            // the two packages import each other.
            .types = &.{ "Key*", "MouseAction", "MouseButton", "MouseEvent", "FocusEvent", "RenderSize" },
            // Paths of functions declared below, selecting which move here.
            .functions = &.{
                "root.encodeKey",
                "root.encodeMouse",
                "root.input.encodeFocus",
                "root.input.isSafePaste",
                "root.encodePaste",
                "root.keyFromASCII",
                "root.keyFromW3C",
            },
        },
    },

    .types = &.{
        .{
            .handle = .{
                .type = gostty.Terminal,
                .fields = &.{
                    .{ .path = "cols" },
                    .{ .path = "rows" },
                    .{ .path = "screens.active.cursor.x", .name = "cursorX" },
                    .{ .path = "screens.active.cursor.y", .name = "cursorY" },
                    .{ .path = "screens.active.cursor.cursor_style", .name = "cursorStyle" },
                    .{ .path = "screens.active_key", .name = "activeScreenKey" },
                    // The LCF: set once printing has filled the last column, so the
                    // next print soft-wraps instead of overwriting.
                    .{ .path = "screens.active.cursor.pending_wrap", .name = "cursorPendingWrap" },
                    .{ .path = "screens.active.cursor.protected", .name = "cursorProtected" },
                    .{ .path = "width_px", .name = "widthPx" },
                    .{ .path = "height_px", .name = "heightPx" },
                    .{ .path = "flags.focused", .name = "focused" },
                    .{ .path = "flags.visible", .name = "visible" },
                    .{ .path = "flags.password_input", .name = "passwordInput" },
                },
            },
        },
        .{ .handle = .{ .type = gostty.Stream, .fields = &.{
            .{ .path = "inner.handler.semantic_failure", .name = "failed", .doc = "True once a sequence failed in a way the terminal could not absorb, such as an allocation failure. Streams are best-effort and keep going." },
        } } },
        .{ .handle = .{ .type = gostty.Screen } },
        .{ .handle = .{ .type = gostty.Search } },
        .{ .handle = .{ .type = gostty.Snapshot, .name = "Snapshot" } },
        .{ .handle = .{ .type = gostty.SnapshotDecoder } },
        .{ .value = .{ .type = gostty.SnapshotProgress } },
        .{ .value = .{ .type = gostty.KeyEvent, .fields = &.{.{ .name = "unshifted_codepoint", .semantic = .codepoint }} } },
        .{ .value = .{ .type = gostty.MouseEvent } },
        .{ .value = .{ .type = gostty.KeyMods } },
        .{ .value = .{ .type = gostty.RenderSize } },
        enumeration("CursorStyle", .{ .text = true }),
        enumeration("CursorStyleReq", .{}),
        enumeration("EraseDisplay", .{}),
        enumeration("EraseLine", .{ .text = true, .open = true }),
        enumeration("TabClear", .{ .text = true, .open = true }),
        enumeration("ProtectedMode", .{}),
        enumeration("ScreenKey", .{}),
        enumeration("SwitchScreenMode", .{}),
        enumeration("Mode", .{ .text = true }),
        .{ .value = .{ .type = gostty.Selection } },
        enumeration("FormatterFormat", .{ .text = true }),
        .{ .value = .{ .type = gostty.FormatOptions } },
        enumeration("SelectionAdjustment", .{ .text = true }),
        enumeration("StreamEvent", .{ .text = true }),
        enumeration("ProgressState", .{ .text = true }),
        enumeration("ColorScheme", .{ .text = true }),
        enumeration("DragEvent", .{ .text = true }),
        enumeration("DragOperation", .{ .text = true }),
        .{ .value = .{ .type = gostty.DragOperations } },
        .{ .value = .{ .type = gostty.DragMove } },
        .{ .value = .{ .type = gostty.DragNotice } },
        callback("DragFn", "DragHandler"),
        enumeration("ClipboardLocation", .{ .text = true, .open = true }),
        enumeration("ClipboardDenial", .{}),
        callback("ClipboardFn", "ClipboardHandler"),
        .{ .handle = .{ .type = gostty.ClipboardRequest } },
        // The PNG bytes are copied into Go before the callback runs, so the
        // decoder may keep them.
        .{ .callback = .{
            .type = gostty.PngDecodeFn,
            .name = "PngDecodeHandler",
            .params = &.{.{ .semantic = .opaque_bytes }},
            .retention = .retained,
            .reentrancy = .allowed,
            .thread = .caller,
        } },
        callback("SecureRandomFn", "SecureRandomHandler"),
        enumeration("Underline", .{}),
        enumeration("ColorName", .{ .text = true, .open = true }),
        .{ .tagged_union = .{ .type = gostty.Attribute } },
        enumeration("SearchDirection", .{}),
        enumeration("SearchScroll", .{}),
        enumeration("SearchState", .{}),
        enumeration("SearchProgress", .{}),
        .{ .value = .{ .type = gostty.Scrollbar } },
        enumeration("Key", .{ .text = true }),
        enumeration("KeyAction", .{ .text = true }),
        enumeration("FocusEvent", .{ .text = true }),
        enumeration("MouseAction", .{ .text = true }),
        enumeration("MouseButton", .{ .text = true }),
        enumeration("Charset", .{}),
        enumeration("CharsetSlot", .{}),
        enumeration("CharsetActiveSlot", .{}),
        enumeration("DeccolmMode", .{}),
        .{ .tagged_union = .{ .type = gostty.ScrollViewport } },
        .{ .handle = .{ .type = gostty.RenderState, .fields = &.{
            .{ .path = "rows" },
            .{ .path = "cols" },
            .{ .path = "cursor.visible", .name = "cursorVisible" },
            .{ .path = "cursor.visual_style", .name = "cursorStyle" },
            .{ .path = "cursor.blinking", .name = "cursorBlinking" },
            .{ .path = "cursor.password_input", .name = "cursorPasswordInput" },
        } } },
        .{ .value = .{ .type = gostty.RenderCell, .fields = &.{.{ .name = "codepoint", .semantic = .codepoint }} } },
        // An integer-backed packed struct: Go sees named fields, the C ABI sees
        // one u32.
        .{ .value = .{ .type = gostty.CellFlags } },
        enumeration("CellWidth", .{}),
        enumeration("RenderDirty", .{}),
        .{ .handle = .{ .type = gostty.KittyImages, .fields = &.{
            .{ .path = "generation" },
        } } },
        enumeration("KittyLayer", .{ .text = true }),
        .{ .value = .{ .type = gostty.KittyPlacement } },
        .{ .value = .{ .type = gostty.KittyImage } },
        enumeration("KittyFormat", .{}),
        enumeration("KittyCompression", .{}),

        // Terminal configuration and state reads.
        .{ .value = .{ .type = gostty.ScrollRegion } },
        enumeration("MouseTracking", .{ .text = true }),
        enumeration("MouseReportFormat", .{ .text = true }),
        enumeration("ModeReport", .{ .text = true }),

        // Selection gestures.
        .{ .handle = .{ .type = gostty.Gesture } },
        enumeration("GestureBehavior", .{ .text = true }),
        enumeration("GestureAutoscrollDirection", .{ .text = true }),
        .{ .value = .{ .type = gostty.GestureGeometry } },
        .{ .value = .{ .type = gostty.GesturePressEvent } },
        .{ .value = .{ .type = gostty.GestureDragEvent } },

        // The standalone parsers.
        .{ .handle = .{ .type = gostty.OSCParser, .name = "OSCParser" } },
        enumeration("OSCCommand", .{ .text = true }),
        enumeration("OSCTerminator", .{ .text = true }),
        enumeration("SemanticPromptAction", .{ .text = true }),
    },
    .functions = &.{
        .{ .path = "root.unicode.codepointWidth" },
        .{ .path = "root.graphemeWidth", .params = &.{.{ .semantic = .codepoint }} },

        // Input encoding.
        .{ .path = "root.encodeKey" },
        .{ .path = "root.encodeMouse" },
        // The two that map onto a key rather than off one, so they take no
        // receiver; the rest are methods, in `.methods` below.
        .{ .path = "root.keyFromASCII", .covers = &.{"Key.fromASCII"} },
        .{ .path = "root.keyFromW3C", .covers = &.{"Key.fromW3C"} },
        // ghostty's own encoders, reached through the `input` namespace.
        .{ .path = "root.input.encodeFocus", .params = &.{ .{ .name = "writer" }, .{ .name = "event" } } },
        .{ .path = "root.input.isSafePaste", .params = &.{.{ .name = "data", .semantic = .opaque_bytes }} },
        .{ .path = "root.encodePaste", .params = &.{ any, any, bytes } },

        // Lifecycle. `Terminal.init` returns by value and takes an `Options`
        // whose `colors` field holds optionals that cannot cross the C ABI.
        // `.flatten` picks the two fields that can and leaves the rest at their
        // Zig defaults, so ghostty's own constructor is bound without a wrapper.
        .{
            .path = "Terminal.init",
            .name = "newTerminal",
            .constructs = gostty.Terminal,
            .params = &.{.{ .flatten = &.{ "cols", "rows" } }},
        },
        .{ .path = "Terminal.deinit", .destroys = gostty.Terminal },
        .{ .path = "root.freeString" },
        // A stream borrows its terminal: ghostty's handler reaches through it for
        // an allocator when it tears down, so the terminal must outlive it.
        .{ .path = "root.newStream", .constructs = gostty.Stream, .child_of_receiver = true },
        .{ .path = "root.freeStream", .destroys = gostty.Stream },
        // `.implements = .writer` adds `Write`, so `fmt.Fprintf(stream, ...)` feeds.
        .{ .path = "Stream.feed", .params = &.{bytes}, .implements = .writer },
        // `Events` is the range-over-func form: `for event, err := range s.Events()`.
        .{ .path = "Stream.nextEvent", .iterator = .{ .name = "Events" } },
        .{ .path = "Stream.eventTitle" },
        .{ .path = "Stream.eventBody" },
        .{ .path = "Stream.eventProgressState" },
        .{ .path = "Stream.eventProgress" },
        .{ .path = "Stream.eventSequence", .returns = .{ .semantic = .opaque_bytes } },
        .{ .path = "Stream.setUnknownMaxBytes" },
        .{ .path = "Stream.setVersionReport" },
        .{ .path = "Stream.setEnquiryResponse" },
        .{ .path = "Stream.colorSchemeChanged" },
        .{ .path = "Stream.clearColorScheme" },

        // Kitty drag and drop. The handler takes its whole payload as
        // arguments, so there is nothing to read back afterwards -- which also
        // means the acceptance is the one being reported rather than whatever
        // a later event in the same feed replaced it with.
        .{ .path = "root.onDrag" },
        .{ .path = "root.dragActive" },
        .{ .path = "root.dragRegisteredMimes" },
        .{ .path = "root.dragClientAccepted" },
        .{ .path = "root.dragMove" },
        .{ .path = "root.dragLeave" },
        .{ .path = "root.dragAddItem", .params = &.{ any, bytes } },
        .{ .path = "root.dragDrop" },
        .{ .path = "root.dragClearItems" },
        // A clipboard request runs while `feed` is on the stack, on the thread
        // that called it, and the callback answers it through the request it
        // is handed. Both facts are contracts a caller has to know, and they
        // are declared on the callback type above.
        .{ .path = "Stream.onClipboardWriteRequest" },
        .{ .path = "Stream.onClipboardReadRequest" },
        .{ .path = "ClipboardRequest.location" },
        .{ .path = "ClipboardRequest.name" },
        .{ .path = "ClipboardRequest.granted" },
        .{ .path = "ClipboardRequest.canRemember" },
        .{ .path = "ClipboardRequest.contentCount" },
        .{ .path = "ClipboardRequest.contentMime" },
        .{ .path = "ClipboardRequest.contentData", .returns = .{ .semantic = .opaque_bytes } },
        .{ .path = "ClipboardRequest.mimeCount" },
        .{ .path = "ClipboardRequest.mime" },
        .{ .path = "ClipboardRequest.allow" },
        .{ .path = "ClipboardRequest.replyText" },
        .{ .path = "ClipboardRequest.deny" },
        .{ .path = "Stream.writeContinuation" },
        .{ .path = "Stream.hasReplies" },
        .{ .path = "Stream.writeSnapshot" },
        .{ .path = "Stream.writeReplies" },

        // ghostty's own methods, bound directly.
        .{ .path = "Terminal.printString" },
        .{ .path = "Terminal.plainString", .returns = .{ .ownership = .caller } },
        .{ .path = "Terminal.setCursorStyle" },
        .{ .path = "Terminal.setCursorPos" },
        .{ .path = "Terminal.carriageReturn" },
        .{ .path = "Terminal.linefeed" },
        .{ .path = "Terminal.backspace" },
        .{ .path = "Terminal.cursorIsAtPrompt" },
        .{ .path = "Terminal.fullReset" },
        // Returns the screen being left, borrowed, or absent when `key` was
        // already active.
        .{ .path = "Terminal.switchScreen", .returns = .{ .ownership = .borrowed } },
        .{ .path = "Terminal.switchScreenMode" },
        .{ .path = "root.activeScreen", .returns = .{ .ownership = .borrowed } },
        .{ .path = "root.screen", .returns = .{ .ownership = .borrowed } },
        // ghostty takes the screen by value here; zigo passes the handle and
        // the shim copies, so no wrapper is needed.
        .{ .path = "Screen.viewportIsBottom" },
        .{ .path = "Screen.clearSelection" },
        .{ .path = "Screen.endHyperlink" },
        // `newSearch` returns by value, like `Terminal.init`: zigo boxes the
        // result and frees the box in `close`.
        .{ .path = "root.newSearch", .constructs = gostty.Search, .child_of_receiver = true },
        .{ .path = "root.searchClose", .destroys = gostty.Search },
        .{
            .path = "root.printAttributesInto",
            .params = &.{out},
            .covers = &.{"Terminal.printAttributes"},
        },
        .{ .path = "root.historyString", .returns = .{ .ownership = .caller }, .covers = &.{"Screen.dumpStringAlloc"} },

        // Cursor movement.
        .{ .path = "Terminal.cursorUp" },
        .{ .path = "Terminal.cursorDown" },
        .{ .path = "Terminal.cursorLeft" },
        .{ .path = "Terminal.cursorRight" },
        .{ .path = "Terminal.saveCursor" },
        .{ .path = "Terminal.restoreCursor" },
        .{ .path = "Terminal.index" },
        .{ .path = "Terminal.reverseIndex" },

        // Tab stops.
        .{ .path = "Terminal.horizontalTab" },
        .{ .path = "Terminal.horizontalTabBack" },
        .{ .path = "Terminal.tabSet" },
        .{ .path = "Terminal.tabReset" },
        .{ .path = "Terminal.tabClear" },

        // Scrolling and margins.
        .{ .path = "Terminal.scrollUp" },
        .{ .path = "Terminal.scrollDown" },
        .{ .path = "Terminal.setTopAndBottomMargin" },
        .{ .path = "Terminal.setLeftAndRightMargin" },
        .{ .path = "root.setScrollbackMaxBytes", .covers = &.{"Terminal.setScrollbackMaxBytes"} },
        .{ .path = "root.clearScrollbackMaxBytes" },
        .{ .path = "root.setScrollbackMaxLines", .covers = &.{"Terminal.setScrollbackMaxLines"} },
        .{ .path = "root.clearScrollbackMaxLines" },

        // Editing.
        .{ .path = "Terminal.insertLines" },
        .{ .path = "Terminal.deleteLines" },
        .{ .path = "Terminal.insertBlanks" },
        .{ .path = "Terminal.deleteChars" },
        .{ .path = "Terminal.eraseChars" },
        .{ .path = "Terminal.eraseLine" },
        .{ .path = "Terminal.eraseDisplay" },
        .{ .path = "Terminal.decaln" },

        // Printing.
        .{ .path = "Terminal.print", .params = &.{.{ .name = "c" }} },
        .{ .path = "Terminal.printRepeat" },
        .{ .path = "Terminal.printSlice", .params = &.{.{ .semantic = .codepoint }} },

        // Metadata the terminal tracks for the shell.
        .{ .path = "root.formatTerminal", .name = "Format" },
        // Snapshots.
        .{ .path = "root.decodeSnapshot", .name = "DecodeSnapshot", .constructs = gostty.Snapshot },
        .{ .path = "Snapshot.deinit", .destroys = gostty.Snapshot },
        // The incremental form: `ready` hands over a drawable terminal, then
        // `next` prepends the scrollback a page at a time.
        .{ .path = "root.newSnapshotDecoder", .constructs = gostty.SnapshotDecoder, .params = &.{bytes} },
        .{ .path = "root.freeSnapshotDecoder", .destroys = gostty.SnapshotDecoder },

        // Colors and modes.
        .{ .path = "root.backgroundColor" },
        .{ .path = "root.foregroundColor" },
        .{ .path = "root.cursorColor" },
        .{ .path = "root.paletteColors", .params = &.{out} },
        .{ .path = "root.setDefaultBackgroundColor" },
        .{ .path = "root.setDefaultForegroundColor" },
        .{ .path = "root.setDefaultCursorColor" },
        .{ .path = "root.modeEnabled" },
        .{ .path = "root.setMode" },
        .{ .path = "Terminal.setPwd" },
        .{ .path = "Terminal.getPwd", .returns = .{ .semantic = .utf8_string } },
        .{ .path = "Terminal.getTitle", .returns = .{ .semantic = .utf8_string } },
        .{ .path = "Terminal.setTitle" },
        .{ .path = "root.setAttribute", .covers = &.{"Terminal.setAttribute"} },
        .{ .path = "Terminal.setProtectedMode" },
        .{ .path = "Terminal.setDefaultCursorStyle" },
        .{ .path = "root.setDefaultCursorBlink", .covers = &.{"Terminal.setDefaultCursorBlink"} },
        .{ .path = "root.resetDefaultCursorBlink" },
        .{ .path = "Terminal.configureCharset" },
        .{ .path = "Terminal.invokeCharset" },
        .{ .path = "Terminal.deccolm" },
        .{ .path = "Terminal.scrollViewport" },
        .{ .path = "Terminal.compressionActivity" },
        .{ .path = "root.resize", .covers = &.{"Terminal.resize"} },
        .{ .path = "root.resizeCells" },

        // Rendering. `RenderState` is ghostty's own renderer-facing snapshot;
        // a frame is one `update` plus one `cells` crossing.
        .{ .path = "root.newRenderState", .constructs = gostty.RenderState },
        .{
            .path = "RenderState.update",
            .params = &.{.{ .name = "t" }},
            .covers = &.{ "RenderState.beginUpdate", "RenderState.endUpdate" },
        },
        .{ .path = "RenderState.clean" },
        .{ .path = "RenderState.deinit", .destroys = gostty.RenderState },

        // Kitty graphics. `KittyImages` is the same kind of snapshot as
        // `RenderState`, for the images rather than the cells: one `update` and
        // one `placements` crossing per frame, with the pixels fetched by id
        // only when their generation says they changed.
        .{ .path = "root.newKittyImages", .constructs = gostty.KittyImages },
        .{ .path = "root.freeKittyImages", .destroys = gostty.KittyImages },
        .{ .path = "Terminal.setKittyGraphicsSizeLimit" },
        .{
            .path = "root.setKittyGraphicsLoadingLimits",
            .covers = &.{"Terminal.setKittyGraphicsLoadingLimits"},
        },
        .{ .path = "root.kittyImage" },
        .{ .path = "root.kittyImageData", .params = &.{ any, out } },

        // System hooks: process-global, answered from inside the callback the
        // same way a clipboard request is. They live in a namespace so that one
        // `clear` is the release zigo requires for the retained callbacks.
        .{ .path = "root.sys.onPngDecodeRequest" },
        .{ .path = "root.sys.replyPngImage", .params = &.{ any, any, bytes } },
        .{ .path = "root.sys.onSecureRandomRequest" },
        .{ .path = "root.sys.clear" },
        .{ .path = "root.sys.replySecureRandom", .params = &.{bytes} },

        // Terminal configuration: what the embedder sets underneath whatever
        // a program on the pty asks for.
        .{ .path = "root.paletteColor" },
        .{ .path = "root.setPaletteColor" },
        .{ .path = "root.resetPaletteColor" },
        .{ .path = "root.resetPalette" },
        .{ .path = "root.setDefaultPaletteColor" },
        .{ .path = "root.resetDefaultPalette" },
        .{ .path = "root.setDefaultMode" },
        .{ .path = "root.resetModes" },
        .{ .path = "root.saveMode" },
        .{ .path = "root.restoreMode" },
        .{ .path = "root.setTabstop" },
        .{ .path = "root.unsetTabstop" },
        .{ .path = "root.resetTabstops" },

        // Terminal state reads: the gets for state the bindings could already
        // set, plus the resolved values no single mode flag reports.
        .{ .path = "root.scrollRegion" },
        .{ .path = "root.charset" },
        .{ .path = "root.charsetGL" },
        .{ .path = "root.charsetGR" },
        .{ .path = "root.charsetSingleShift" },
        .{ .path = "root.protectedMode" },
        .{ .path = "root.mouseTracking" },
        .{ .path = "root.mouseTrackingSendsMotion" },
        .{ .path = "root.mouseReportFormat" },
        .{ .path = "root.modeReport" },

        // Selection gestures. Like `Search`, a gesture borrows its terminal --
        // it holds a tracked pin inside it and hands it back on every call --
        // so it is a child handle and closes first.
        .{ .path = "root.newGesture", .constructs = gostty.Gesture, .child_of_receiver = true },
        .{ .path = "root.gestureClose", .destroys = gostty.Gesture },

        // The standalone parsers. `Stream` needs a `Terminal` behind it; these
        // two parse a sequence and hand back what it said, with no terminal
        // state involved at all.
        .{ .path = "root.newOSCParser", .constructs = gostty.OSCParser },
        .{ .path = "root.freeOSCParser", .destroys = gostty.OSCParser },
        .{ .path = "root.sgrAttributeCount" },
        .{ .path = "root.sgrAttributeAt" },
    },
    .methods = &.{
        // What a key is, for a caller deciding whether a press can carry text.
        // ghostty's own methods on the enum, bound as Go value-receiver methods.
        .{
            .receiver = gostty.Key,
            .functions = &.{
                .{ .path = "Key.codepoint" },
                .{ .path = "Key.printable" },
                .{ .path = "Key.modifier" },
                .{ .path = "Key.keypad" },
                .{ .path = "Key.leftOrRightShift" },
                .{ .path = "Key.leftOrRightAlt" },
                .{ .path = "Key.ctrlOrSuper" },
                .{ .path = "Key.shouldBeRemappable" },
                .{ .path = "Key.w3c", .name = "W3C" },
            },
        },
        // Screen is ghostty's own type, so these cannot be written as methods
        // on it; the group attaches them and drops the shared `screen` prefix.
        .{
            .receiver = gostty.Screen,
            .strip_prefix = "screen",
            .functions = &.{
                .{ .path = "root.screenSelectAll", .covers = &.{"Screen.selectAll"} },
                .{ .path = "root.screenHasSelection" },
                .{ .path = "root.screenSelectRange", .covers = &.{"Screen.select"} },
                .{ .path = "root.screenSelectWord", .covers = &.{"Screen.selectWord"} },
                .{ .path = "root.screenSelectLine", .covers = &.{"Screen.selectLine"} },
                .{ .path = "root.screenSelectOutput", .covers = &.{"Screen.selectOutput"} },
                .{ .path = "root.screenSelectionString", .returns = .{ .ownership = .caller }, .covers = &.{"Screen.selectionString"} },
                .{ .path = "root.screenSelection" },
                .{ .path = "root.screenSetSelection" },
                .{ .path = "root.screenViewportTop" },
                .{ .path = "root.screenScrollbar" },
                .{ .path = "root.screenFormat" },
                .{ .path = "root.screenFormatSelection" },
                .{ .path = "root.screenSelectionContains" },
                .{ .path = "root.screenSelectionAdjust" },
                .{ .path = "root.screenStartHyperlink", .covers = &.{"Screen.startHyperlink"} },
            },
        },
        .{
            .receiver = gostty.Search,
            .strip_prefix = "search",
            .functions = &.{
                .{ .path = "root.searchNeedle" },
                .{ .path = "root.searchStatus" },
                .{ .path = "root.searchTick" },
                .{ .path = "root.searchFeed" },
                .{ .path = "root.searchAll" },
                .{ .path = "root.searchSelect" },
                .{ .path = "root.searchMatchCount" },
                .{ .path = "root.searchMatches", .params = &.{out} },
                .{ .path = "root.searchViewportMatches", .params = &.{out} },
                .{ .path = "root.searchSelectedMatch" },
                .{ .path = "root.searchSelectedIndex" },
            },
        },
        .{
            .receiver = gostty.SnapshotDecoder,
            .strip_prefix = "snapshotDecoder",
            .functions = &.{
                .{ .path = "root.snapshotDecoderReady" },
                .{ .path = "root.snapshotDecoderRestoreInto" },
                .{ .path = "root.snapshotDecoderContinuation", .returns = .{ .semantic = .opaque_bytes } },
                .{ .path = "root.snapshotDecoderNext" },
            },
        },
        .{
            .receiver = gostty.Snapshot,
            .strip_prefix = "snapshot",
            .functions = &.{
                .{ .path = "root.snapshotRestoreInto" },
                .{ .path = "root.snapshotContinuation", .returns = .{ .semantic = .opaque_bytes } },
            },
        },
        .{
            .receiver = gostty.ColorName,
            .strip_prefix = "colorName",
            .functions = &.{
                .{ .path = "root.colorNameDefault", .covers = &.{"ColorName.default"} },
            },
        },
        .{
            .receiver = gostty.RenderState,
            .strip_prefix = "render",
            .functions = &.{
                .{ .path = "root.renderCellCount" },
                .{ .path = "root.renderCells", .params = &.{out} },
                .{ .path = "root.renderBackground" },
                .{ .path = "root.renderForeground" },
                .{ .path = "root.renderCursorX" },
                .{ .path = "root.renderCursorY" },
                .{ .path = "root.renderCursorWideTail" },
                .{ .path = "root.renderCursorColor" },
                // Partial redraw: which rows changed, one row's cells, and
                // marking them drawn.
                .{ .path = "root.renderDirty" },
                .{ .path = "root.renderDirtyRows", .params = &.{out} },
                .{ .path = "root.renderRowCells", .params = &.{ any, out } },
                .{
                    .path = "root.renderGraphemes",
                    .params = &.{ any, any, .{ .direction = .out, .written = .result, .semantic = .codepoint } },
                },
                .{ .path = "root.renderHyperlinkAt", .returns = .{ .ownership = .caller }, .covers = &.{"RenderState.linkCells"} },
            },
        },
        .{
            .receiver = gostty.KittyImages,
            .strip_prefix = "kitty",
            .functions = &.{
                .{ .path = "root.kittyUpdate" },
                .{ .path = "root.kittyPlacementCount" },
                .{ .path = "root.kittyPlacements", .params = &.{out} },
            },
        },
        .{
            .receiver = gostty.Gesture,
            .strip_prefix = "gesture",
            .functions = &.{
                .{ .path = "root.gestureSetBehaviors" },
                .{ .path = "root.gestureSetWordBoundaries" },
                .{ .path = "root.gestureSetGeometry" },
                .{ .path = "root.gesturePress" },
                .{ .path = "root.gestureDrag" },
                .{ .path = "root.gestureAutoscroll" },
                .{ .path = "root.gestureAutoscrollTick" },
                .{ .path = "root.gestureDeepPress" },
                .{ .path = "root.gestureRelease" },
                .{ .path = "root.gestureReset" },
                .{ .path = "root.gestureClickCount" },
                .{ .path = "root.gestureDragged" },
            },
        },
        .{
            .receiver = gostty.OSCParser,
            .functions = &.{
                .{ .path = "root.OSCParser.feed", .params = &.{bytes} },
                .{ .path = "root.OSCParser.end" },
                .{ .path = "root.OSCParser.reset" },
                .{ .path = "root.OSCParser.command" },
                // The strings below are borrowed from the parser and stay valid
                // only until the next feed, end or reset, which is why none of
                // them declare a release function.
                .{ .path = "root.OSCParser.windowTitle" },
                .{ .path = "root.OSCParser.icon" },
                .{ .path = "root.OSCParser.pwd" },
                .{ .path = "root.OSCParser.hyperlinkURI" },
                .{ .path = "root.OSCParser.hyperlinkID" },
                .{ .path = "root.OSCParser.notificationTitle" },
                .{ .path = "root.OSCParser.notificationBody" },
                .{ .path = "root.OSCParser.clipboardData" },
                .{ .path = "root.OSCParser.clipboardSelection" },
                .{ .path = "root.OSCParser.mouseShape" },
                .{ .path = "root.OSCParser.semanticPromptAction" },
                .{ .path = "root.OSCParser.semanticPromptOptions" },
                .{ .path = "root.OSCParser.progressState" },
                .{ .path = "root.OSCParser.progressValue" },
            },
        },
    },
});
