// Code generated by zigo. DO NOT EDIT.

package gostty

import (
	"encoding/binary"
	"fmt"
	"strings"
	"unsafe"

	"github.com/ironpark/gostty/internal/raw"
)

// Event is an owned Go snapshot of the Zig struct of the same name.
type Event struct {
	Kind          StreamEvent
	Title         string
	Pwd           string
	Body          string
	Sequence      []byte
	ProgressState ProgressState
	Progress      uint8
	HasProgress   bool
}

const zigoMaterializedMagicVersion = uint64(0x00024f47495a)

func zigoMaterializedU64(buffer []byte, offset uint64) uint64 {
	if offset > uint64(len(buffer)) || uint64(len(buffer))-offset < 8 {
		panic("zigo: invalid materialized result buffer")
	}
	return binary.LittleEndian.Uint64(buffer[int(offset) : int(offset)+8])
}

func zigoMaterializedBytes(buffer []byte, offset, length uint64) []byte {
	if offset > uint64(len(buffer)) || length > uint64(len(buffer))-offset {
		panic("zigo: invalid materialized result buffer")
	}
	return buffer[int(offset):int(offset+length)]
}

// zigoMaterializedWord reads a little-endian value of width bytes.
func zigoMaterializedWord(buffer []byte, offset, width uint64) uint64 {
	var value uint64
	for i, b := range zigoMaterializedBytes(buffer, offset, width) {
		value |= uint64(b) << (8 * uint(i))
	}
	return value
}

func zigoMaterializedHeader(buffer []byte, layout uint64) (uint64, uint64) {
	if len(buffer) < 40 || zigoMaterializedU64(buffer, 0) != zigoMaterializedMagicVersion ||
		zigoMaterializedU64(buffer, 8) != layout || zigoMaterializedU64(buffer, 32) != uint64(len(buffer)) {
		panic("zigo: invalid materialized result buffer")
	}
	return zigoMaterializedU64(buffer, 24), zigoMaterializedU64(buffer, 16)
}

func zigoDecodeEventBuffer(buffer []byte) Event {
	offset, count := zigoMaterializedHeader(buffer, 0)
	if count != 1 {
		panic("zigo: invalid materialized result buffer")
	}
	var result Event
	zigoDecodeEventInto(buffer, offset, &result)
	return result
}

func zigoDecodeEventInto(buffer []byte, offset uint64, result *Event) {
	_ = zigoMaterializedBytes(buffer, offset, 80)
	result.Kind = StreamEvent(zigoMaterializedWord(buffer, offset+0, 1))
	result.Title = string(zigoMaterializedBytes(buffer, zigoMaterializedU64(buffer, offset+8), zigoMaterializedU64(buffer, offset+8+8)))
	result.Pwd = string(zigoMaterializedBytes(buffer, zigoMaterializedU64(buffer, offset+24), zigoMaterializedU64(buffer, offset+24+8)))
	result.Body = string(zigoMaterializedBytes(buffer, zigoMaterializedU64(buffer, offset+40), zigoMaterializedU64(buffer, offset+40+8)))
	result.Sequence = append([]byte(nil), zigoMaterializedBytes(buffer, zigoMaterializedU64(buffer, offset+56), zigoMaterializedU64(buffer, offset+56+8))...)
	result.ProgressState = ProgressState(zigoMaterializedWord(buffer, offset+72, 1))
	result.Progress = uint8(zigoMaterializedWord(buffer, offset+73, 1))
	result.HasProgress = zigoMaterializedWord(buffer, offset+74, 1) != 0
}

// DragOperations mirrors the Zig packed struct of the same name.
type DragOperations struct {
	Copy bool
	Move bool
	Pad  uint8
}

func zigoDragOperationsToBacking(value DragOperations) uint8 {
	var result uint64
	result |= (uint64(zigoBoolToUint8(value.Copy)) & 0x1) << 0
	result |= (uint64(zigoBoolToUint8(value.Move)) & 0x1) << 1
	result |= (uint64(value.Pad) & 0x3f) << 2
	return uint8(result)
}

// Backing returns the integer representation used by Zig.
func (value DragOperations) Backing() uint8 { return zigoDragOperationsToBacking(value) }

// DragOperationsFromBacking reconstructs a DragOperations from its Zig integer representation.
func DragOperationsFromBacking(value uint8) DragOperations {
	return DragOperations{
		Copy: ((uint64(value) >> 0) & 0x1) != 0,
		Move: ((uint64(value) >> 1) & 0x1) != 0,
		Pad:  uint8(((uint64(value) >> 2) & 0x3f)),
	}
}

// String names the set members of DragOperations, joined by "|". A member left at
// its zero value is not named, so the zero DragOperations is "none".
func (value DragOperations) String() string {
	var parts []string
	if value.Copy {
		parts = append(parts, "Copy")
	}
	if value.Move {
		parts = append(parts, "Move")
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, "|")
}

// DragOperations satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(DragOperations)

// DragNotice mirrors the Zig packed struct of the same name.
type DragNotice struct {
	Event    DragEvent
	Accepted DragOperation
	Answered bool
	Pad      uint16
}

func zigoDragNoticeToBacking(value DragNotice) uint32 {
	var result uint64
	result |= (uint64(value.Event) & 0xff) << 0
	result |= (uint64(value.Accepted) & 0xff) << 8
	result |= (uint64(zigoBoolToUint8(value.Answered)) & 0x1) << 16
	result |= (uint64(value.Pad) & 0x7fff) << 17
	return uint32(result)
}

// Backing returns the integer representation used by Zig.
func (value DragNotice) Backing() uint32 { return zigoDragNoticeToBacking(value) }

// DragNoticeFromBacking reconstructs a DragNotice from its Zig integer representation.
func DragNoticeFromBacking(value uint32) DragNotice {
	return DragNotice{
		Event:    DragEvent(((uint64(value) >> 0) & 0xff)),
		Accepted: DragOperation(((uint64(value) >> 8) & 0xff)),
		Answered: ((uint64(value) >> 16) & 0x1) != 0,
		Pad:      uint16(((uint64(value) >> 17) & 0x7fff)),
	}
}

// String names the set members of DragNotice, joined by "|". A member left at
// its zero value is not named, so the zero DragNotice is "none".
func (value DragNotice) String() string {
	var parts []string
	if value.Event != 0 {
		parts = append(parts, fmt.Sprintf("Event:%v", value.Event))
	}
	if value.Accepted != 0 {
		parts = append(parts, fmt.Sprintf("Accepted:%v", value.Accepted))
	}
	if value.Answered {
		parts = append(parts, "Answered")
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, "|")
}

// DragNotice satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(DragNotice)

// RenderCursor mirrors the Zig packed struct of the same name.
type RenderCursor struct {
	X                uint16
	Y                uint16
	ViewportHasValue bool
	WideTail         bool
	Visible          bool
	Blinking         bool
	PasswordInput    bool
	Style            CursorStyle
	Pad              uint32
}

func zigoRenderCursorToBacking(value RenderCursor) uint64 {
	var result uint64
	result |= (uint64(value.X) & 0xffff) << 0
	result |= (uint64(value.Y) & 0xffff) << 16
	result |= (uint64(zigoBoolToUint8(value.ViewportHasValue)) & 0x1) << 32
	result |= (uint64(zigoBoolToUint8(value.WideTail)) & 0x1) << 33
	result |= (uint64(zigoBoolToUint8(value.Visible)) & 0x1) << 34
	result |= (uint64(zigoBoolToUint8(value.Blinking)) & 0x1) << 35
	result |= (uint64(zigoBoolToUint8(value.PasswordInput)) & 0x1) << 36
	result |= (uint64(value.Style) & 0x3) << 37
	result |= (uint64(value.Pad) & 0x1ffffff) << 39
	return uint64(result)
}

// Backing returns the integer representation used by Zig.
func (value RenderCursor) Backing() uint64 { return zigoRenderCursorToBacking(value) }

// RenderCursorFromBacking reconstructs a RenderCursor from its Zig integer representation.
func RenderCursorFromBacking(value uint64) RenderCursor {
	return RenderCursor{
		X:                uint16(((uint64(value) >> 0) & 0xffff)),
		Y:                uint16(((uint64(value) >> 16) & 0xffff)),
		ViewportHasValue: ((uint64(value) >> 32) & 0x1) != 0,
		WideTail:         ((uint64(value) >> 33) & 0x1) != 0,
		Visible:          ((uint64(value) >> 34) & 0x1) != 0,
		Blinking:         ((uint64(value) >> 35) & 0x1) != 0,
		PasswordInput:    ((uint64(value) >> 36) & 0x1) != 0,
		Style:            CursorStyle(((uint64(value) >> 37) & 0x3)),
		Pad:              uint32(((uint64(value) >> 39) & 0x1ffffff)),
	}
}

// CellFlags mirrors the Zig packed struct of the same name.
type CellFlags struct {
	Bold          bool
	Italic        bool
	Faint         bool
	Blink         bool
	Inverse       bool
	Invisible     bool
	Strikethrough bool
	Overline      bool
	Underline     Underline
	// Wide: Narrow, wide, or a spacer the renderer should skip.
	Wide CellWidth
	// Selected: Whether the cell falls inside the screen's selection.
	Selected bool
	// HasGrapheme: Whether the base codepoint has combining marks or other grapheme data.
	// A renderer can skip `renderGraphemes` for the common single-codepoint case.
	HasGrapheme bool
	Pad         uint32
}

func zigoCellFlagsToBacking(value CellFlags) uint32 {
	var result uint64
	result |= (uint64(zigoBoolToUint8(value.Bold)) & 0x1) << 0
	result |= (uint64(zigoBoolToUint8(value.Italic)) & 0x1) << 1
	result |= (uint64(zigoBoolToUint8(value.Faint)) & 0x1) << 2
	result |= (uint64(zigoBoolToUint8(value.Blink)) & 0x1) << 3
	result |= (uint64(zigoBoolToUint8(value.Inverse)) & 0x1) << 4
	result |= (uint64(zigoBoolToUint8(value.Invisible)) & 0x1) << 5
	result |= (uint64(zigoBoolToUint8(value.Strikethrough)) & 0x1) << 6
	result |= (uint64(zigoBoolToUint8(value.Overline)) & 0x1) << 7
	result |= (uint64(value.Underline) & 0x7) << 8
	result |= (uint64(value.Wide) & 0x3) << 11
	result |= (uint64(zigoBoolToUint8(value.Selected)) & 0x1) << 13
	result |= (uint64(zigoBoolToUint8(value.HasGrapheme)) & 0x1) << 14
	result |= (uint64(value.Pad) & 0x1ffff) << 15
	return uint32(result)
}

// Backing returns the integer representation used by Zig.
func (value CellFlags) Backing() uint32 { return zigoCellFlagsToBacking(value) }

// CellFlagsFromBacking reconstructs a CellFlags from its Zig integer representation.
func CellFlagsFromBacking(value uint32) CellFlags {
	return CellFlags{
		Bold:          ((uint64(value) >> 0) & 0x1) != 0,
		Italic:        ((uint64(value) >> 1) & 0x1) != 0,
		Faint:         ((uint64(value) >> 2) & 0x1) != 0,
		Blink:         ((uint64(value) >> 3) & 0x1) != 0,
		Inverse:       ((uint64(value) >> 4) & 0x1) != 0,
		Invisible:     ((uint64(value) >> 5) & 0x1) != 0,
		Strikethrough: ((uint64(value) >> 6) & 0x1) != 0,
		Overline:      ((uint64(value) >> 7) & 0x1) != 0,
		Underline:     Underline(((uint64(value) >> 8) & 0x7)),
		Wide:          CellWidth(((uint64(value) >> 11) & 0x3)),
		Selected:      ((uint64(value) >> 13) & 0x1) != 0,
		HasGrapheme:   ((uint64(value) >> 14) & 0x1) != 0,
		Pad:           uint32(((uint64(value) >> 15) & 0x1ffff)),
	}
}

// String names the set members of CellFlags, joined by "|". A member left at
// its zero value is not named, so the zero CellFlags is "none".
func (value CellFlags) String() string {
	var parts []string
	if value.Bold {
		parts = append(parts, "Bold")
	}
	if value.Italic {
		parts = append(parts, "Italic")
	}
	if value.Faint {
		parts = append(parts, "Faint")
	}
	if value.Blink {
		parts = append(parts, "Blink")
	}
	if value.Inverse {
		parts = append(parts, "Inverse")
	}
	if value.Invisible {
		parts = append(parts, "Invisible")
	}
	if value.Strikethrough {
		parts = append(parts, "Strikethrough")
	}
	if value.Overline {
		parts = append(parts, "Overline")
	}
	if value.Underline != 0 {
		parts = append(parts, fmt.Sprintf("Underline:%v", value.Underline))
	}
	if value.Wide != 0 {
		parts = append(parts, fmt.Sprintf("Wide:%v", value.Wide))
	}
	if value.Selected {
		parts = append(parts, "Selected")
	}
	if value.HasGrapheme {
		parts = append(parts, "HasGrapheme")
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, "|")
}

// CellFlags satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(CellFlags)

// GridPoint mirrors the Zig `extern struct` of the same name.
type GridPoint struct {
	// X: Column, zero-based.
	X uint16
	// Y: Row, in the coordinate space of the `PointTag` it was read with:
	// viewport-relative for `.viewport`, scrollback-inclusive for `.screen`.
	Y uint32
}

// GridPoint is reinterpreted as raw.GridPointData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(GridPoint{})-unsafe.Sizeof(raw.GridPointData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(GridPoint{}.X)-unsafe.Offsetof(raw.GridPointData{}.X)]
var _ = [1]struct{}{}[unsafe.Offsetof(GridPoint{}.Y)-unsafe.Offsetof(raw.GridPointData{}.Y)]

// String renders GridPoint as its type name and its fields.
func (value GridPoint) String() string {
	return fmt.Sprintf("GridPoint{X:%v, Y:%v}", value.X, value.Y)
}

// GridPoint satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(GridPoint)

// Selection mirrors the Zig `extern struct` of the same name.
type Selection struct {
	// StartX: Column of the corner the selection was started from, zero-based.
	StartX uint16
	// StartY: Row of that corner, in screen coordinates: scrollback included, so it
	// does not move when the viewport scrolls.
	StartY uint32
	// EndX: Column of the corner the selection was dragged to. It may be left of
	// `start_x`; a selection is not normalised to a direction.
	EndX uint16
	// EndY: Row of that corner, in the same screen coordinates as `start_y`.
	EndY uint32
	// Rectangle: A rectangle between the two corners rather than a run of lines.
	Rectangle bool
}

// String renders Selection as its type name and its fields.
func (value Selection) String() string {
	return fmt.Sprintf("Selection{StartX:%v, StartY:%v, EndX:%v, EndY:%v, Rectangle:%v}", value.StartX, value.StartY, value.EndX, value.EndY, value.Rectangle)
}

// Selection satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(Selection)

// FormatOptions mirrors the Zig `extern struct` of the same name.
type FormatOptions struct {
	// Format: Which of the three renderings to emit. The zero value is plain text.
	Format FormatterFormat
	// Unwrap: Join soft-wrapped lines back into one instead of emitting them as
	// they are laid out at the current width.
	Unwrap bool
	// KeepTrailingWhitespace: Keep trailing spaces on lines that have other text. Trailing blank
	// lines are always dropped.
	KeepTrailingWhitespace bool
	// Cursor: Include the cursor position. Styled formats only.
	Cursor bool
	// NoStyles: Leave out text styles. Styled formats only.
	NoStyles bool
	// NoHyperlinks: Leave out OSC 8 hyperlinks. Styled formats only.
	NoHyperlinks bool
	// ResolvePalette: Resolve palette indices to the terminal's current RGB values rather
	// than emitting the index. Styled formats only.
	//
	// `Terminal.format` and `Terminal.formatSelection` only. A `Screen` is
	// borrowed from its terminal and does not carry the palette or the default
	// colors, so its formatters ignore this and emit the index. Since the
	// terminal's formatter reaches the scrollback too, format through the
	// terminal when the output has to carry real colors.
	ResolvePalette bool
}

// RGB mirrors the Zig `extern struct` of the same name.
type RGB struct {
	// R: The red channel.
	R uint8
	// G: The green channel.
	G uint8
	// B: The blue channel.
	B uint8
}

// RGB is reinterpreted as raw.RGBData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(RGB{})-unsafe.Sizeof(raw.RGBData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(RGB{}.R)-unsafe.Offsetof(raw.RGBData{}.R)]
var _ = [1]struct{}{}[unsafe.Offsetof(RGB{}.G)-unsafe.Offsetof(raw.RGBData{}.G)]
var _ = [1]struct{}{}[unsafe.Offsetof(RGB{}.B)-unsafe.Offsetof(raw.RGBData{}.B)]

// Scrollbar mirrors the Zig `extern struct` of the same name.
type Scrollbar struct {
	// Total size of the scrollable area.
	Total uint64
	// Offset: The offset into the total area that the viewport is at. This is
	// guaranteed to be less than or equal to total. This includes the
	// visible row.
	Offset uint64
	// Len: The length of the visible area. This is including the offset row.
	Len uint64
}

// Scrollbar is reinterpreted as raw.ScrollbarData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(Scrollbar{})-unsafe.Sizeof(raw.ScrollbarData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(Scrollbar{}.Total)-unsafe.Offsetof(raw.ScrollbarData{}.Total)]
var _ = [1]struct{}{}[unsafe.Offsetof(Scrollbar{}.Offset)-unsafe.Offsetof(raw.ScrollbarData{}.Offset)]
var _ = [1]struct{}{}[unsafe.Offsetof(Scrollbar{}.Len)-unsafe.Offsetof(raw.ScrollbarData{}.Len)]

// ScrollRegion mirrors the Zig `extern struct` of the same name.
type ScrollRegion struct {
	// Top: First row that scrolls, zero-based and inclusive (DECSTBM top).
	Top uint16
	// Bottom: Last row that scrolls, inclusive. A full-height region ends at
	// `rows - 1`.
	Bottom uint16
	// Left: First column that scrolls, inclusive (DECSLRM left). Meaningful only
	// while left-right margin mode is on; otherwise it is 0.
	Left uint16
	// Right: Last column that scrolls, inclusive. Without margin mode it is
	// `cols - 1`.
	Right uint16
}

// ScrollRegion is reinterpreted as raw.ScrollRegionData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(ScrollRegion{})-unsafe.Sizeof(raw.ScrollRegionData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(ScrollRegion{}.Top)-unsafe.Offsetof(raw.ScrollRegionData{}.Top)]
var _ = [1]struct{}{}[unsafe.Offsetof(ScrollRegion{}.Bottom)-unsafe.Offsetof(raw.ScrollRegionData{}.Bottom)]
var _ = [1]struct{}{}[unsafe.Offsetof(ScrollRegion{}.Left)-unsafe.Offsetof(raw.ScrollRegionData{}.Left)]
var _ = [1]struct{}{}[unsafe.Offsetof(ScrollRegion{}.Right)-unsafe.Offsetof(raw.ScrollRegionData{}.Right)]

// String renders ScrollRegion as its type name and its fields.
func (value ScrollRegion) String() string {
	return fmt.Sprintf("ScrollRegion{Top:%v, Bottom:%v, Left:%v, Right:%v}", value.Top, value.Bottom, value.Left, value.Right)
}

// ScrollRegion satisfies fmt.Stringer as a value, which is the form `%v` is
// handed; a pointer receiver would stop this compiling.
var _ fmt.Stringer = *new(ScrollRegion)

// GestureGeometry mirrors the Zig `extern struct` of the same name.
type GestureGeometry struct {
	// Columns in the rendered grid.
	Columns uint32
	// CellWidth: One cell's width in surface pixels.
	CellWidth uint32
	// PaddingLeft: Padding before the first column, in surface pixels.
	PaddingLeft uint32
	// ScreenHeight: The surface height in pixels, which is where a downward drag starts
	// asking for autoscroll.
	ScreenHeight uint32
}

// GestureGeometry is reinterpreted as raw.GestureGeometryData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(GestureGeometry{})-unsafe.Sizeof(raw.GestureGeometryData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(GestureGeometry{}.Columns)-unsafe.Offsetof(raw.GestureGeometryData{}.Columns)]
var _ = [1]struct{}{}[unsafe.Offsetof(GestureGeometry{}.CellWidth)-unsafe.Offsetof(raw.GestureGeometryData{}.CellWidth)]
var _ = [1]struct{}{}[unsafe.Offsetof(GestureGeometry{}.PaddingLeft)-unsafe.Offsetof(raw.GestureGeometryData{}.PaddingLeft)]
var _ = [1]struct{}{}[unsafe.Offsetof(GestureGeometry{}.ScreenHeight)-unsafe.Offsetof(raw.GestureGeometryData{}.ScreenHeight)]

// GesturePressEvent mirrors the Zig `extern struct` of the same name.
type GesturePressEvent struct {
	// X: Column of the cell under the pointer, in viewport coordinates.
	X uint16
	// Y: Row of that cell, in viewport coordinates: 0 is the top visible row,
	// not the top of the scrollback.
	Y uint16
	// Xpos: Pointer x in surface pixels from the top left. Kept apart from the
	// cell because both the multi-click distance test and the within-cell
	// selection threshold need sub-cell precision.
	Xpos float64
	// Ypos: Pointer y in surface pixels, for the same reason as `xpos`.
	Ypos float64
	// MaxDistance: How far a second press may be from the first and still count as a
	// repeat. One cell width is a reasonable choice.
	MaxDistance float64
	// RepeatIntervalNs: How long after a press a second one still counts as a repeat. Zero
	// disables multi-click entirely: every press is then a fresh single
	// click, which is also the honest setting for a caller with no clock.
	RepeatIntervalNs uint64
	// TimeNs: When the press happened, in nanoseconds on a monotonic clock.
	//
	// Passed in rather than read from a clock here: the embedder already has
	// the timestamp the window system delivered with the event, that one is
	// the truth about when the user clicked (a queued event can reach the
	// terminal much later), and a test can drive double clicks without
	// sleeping. Only differences matter, so any epoch will do. Time that runs
	// backwards ends the click sequence.
	TimeNs int64
}

// GesturePressEvent is reinterpreted as raw.GesturePressEventData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(GesturePressEvent{})-unsafe.Sizeof(raw.GesturePressEventData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.X)-unsafe.Offsetof(raw.GesturePressEventData{}.X)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.Y)-unsafe.Offsetof(raw.GesturePressEventData{}.Y)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.Xpos)-unsafe.Offsetof(raw.GesturePressEventData{}.Xpos)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.Ypos)-unsafe.Offsetof(raw.GesturePressEventData{}.Ypos)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.MaxDistance)-unsafe.Offsetof(raw.GesturePressEventData{}.MaxDistance)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.RepeatIntervalNs)-unsafe.Offsetof(raw.GesturePressEventData{}.RepeatIntervalNs)]
var _ = [1]struct{}{}[unsafe.Offsetof(GesturePressEvent{}.TimeNs)-unsafe.Offsetof(raw.GesturePressEventData{}.TimeNs)]

// GestureDragEvent mirrors the Zig `extern struct` of the same name.
type GestureDragEvent struct {
	// X: The cell under the pointer, in viewport coordinates. For an autoscroll
	// tick this is resolved after the viewport moves, so it names the row that
	// scrolled under the pointer.
	X uint16
	// Y: Row of that cell, in viewport coordinates.
	Y uint16
	// Xpos: Pointer x in surface pixels from the top left.
	Xpos float64
	// Ypos: Pointer y in surface pixels from the top left.
	Ypos float64
	// Rectangle: Select the block between the two corners rather than the flow of text.
	Rectangle bool
}

// DragMove mirrors the Zig `extern struct` of the same name.
type DragMove struct {
	// CellX: Column of the cell under the pointer, zero-based from the top left.
	CellX uint32
	// CellY: Row of that cell, zero-based from the top left.
	CellY uint32
	// PixelX: Pointer x in pixels, relative to the top left of the content area.
	PixelX int32
	// PixelY: Pointer y in pixels, relative to the top left of the content area.
	PixelY int32
	// Operations: What the source is offering -- copy, move, link -- as a flag set. The
	// reply picks one of these and no other.
	Operations DragOperations
}

// FeedBoundary mirrors the Zig `extern struct` of the same name.
type FeedBoundary struct {
	// Consumed: Bytes taken from the input. When `reached` is false this is all of
	// them; otherwise it stops just past the sequence that ended at ground.
	Consumed uint
	// Reached: Whether the parser came back to ground within the input. False means
	// the input ended mid-sequence and the rest is still pending.
	Reached bool
}

// SnapshotProgress mirrors the Zig `extern struct` of the same name.
type SnapshotProgress struct {
	// Rows prepended above what that screen already had, or zero when the
	// page was read and validated but dropped -- because the screen is gone,
	// the terminal was resized, or the scrollback has no room.
	Rows uint64
	// Remaining: Pages still to come for the same screen.
	Remaining uint32
	// Pad: Padding so the struct's layout matches across the C ABI. Not data.
	Pad uint32
}

// SnapshotProgress is reinterpreted as raw.SnapshotProgressData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(SnapshotProgress{})-unsafe.Sizeof(raw.SnapshotProgressData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(SnapshotProgress{}.Rows)-unsafe.Offsetof(raw.SnapshotProgressData{}.Rows)]
var _ = [1]struct{}{}[unsafe.Offsetof(SnapshotProgress{}.Remaining)-unsafe.Offsetof(raw.SnapshotProgressData{}.Remaining)]
var _ = [1]struct{}{}[unsafe.Offsetof(SnapshotProgress{}.Pad)-unsafe.Offsetof(raw.SnapshotProgressData{}.Pad)]

// RenderColors mirrors the Zig `extern struct` of the same name.
type RenderColors struct {
	// Background: The terminal's default background, after any OSC 11 the program set.
	// What an unstyled cell should be painted with.
	Background RGB
	// Foreground: The default foreground, after any OSC 10.
	Foreground RGB
	// Cursor: The cursor colour, meaningful only when `cursor_has_value` is set.
	Cursor RGB
	// CursorHasValue: Whether the program set a cursor colour at all. When false the cursor
	// is the embedder's to colour, conventionally with `foreground`.
	CursorHasValue bool
}

// RenderCell mirrors the Zig `extern struct` of the same name.
type RenderCell struct {
	// Codepoint: The cell's codepoint, or 0 for an empty cell. Only the first codepoint
	// of a grapheme cluster; combining marks are not carried across.
	Codepoint rune
	// Fg: Foreground, already resolved: palette indices and
	// defaults are looked up, so this is the colour to paint with.
	Fg RGB
	// Bg: Background, resolved the same way as `fg`.
	Bg RGB
	// Flags: Style bits for this cell -- bold, underline, selection and the rest.
	// Carried as the backing integer in array positions; read a named field
	// off it with `CellFlagsFromBacking`.
	Flags CellFlags
}

// KittyPlacement mirrors the Zig `extern struct` of the same name.
type KittyPlacement struct {
	// ImageID: The image to draw. Look it up with `kittyImage`.
	ImageID uint32
	// PlacementID: Which placement of that image this is. Together with `image_id` it
	// identifies the placement for as long as it exists.
	PlacementID uint32
	// ViewportCol: Where the top-left corner goes, in viewport cells. The row is negative
	// when the image has scrolled partly above the viewport, and either can be
	// negative for a placement positioned relative to another one.
	ViewportCol int32
	// ViewportRow: The row of that corner, in viewport cells, negative under the same
	// conditions as `viewport_col`.
	ViewportRow int32
	// XOffset: Horizontal offset within that cell, in pixels.
	XOffset uint32
	// YOffset: Vertical offset within that cell, in pixels.
	YOffset uint32
	// PixelWidth: How big to draw it, in pixels. This is the source rectangle scaled to
	// whatever the program asked for, so it is what the image should be
	// stretched to rather than its natural size.
	PixelWidth uint32
	// PixelHeight: The height to draw it at, in pixels; the other half of `pixel_width`.
	PixelHeight uint32
	// GridCols: The same size in cells, which is what the placement occupies on the
	// grid. Useful for clipping; the pixel size is what to draw.
	GridCols uint32
	// GridRows: The same height in cells, the other half of `grid_cols`.
	GridRows uint32
	// SourceX: The part of the image to draw, in image pixels. Already clamped to the
	// image, and a zero-sized request already turned into the full dimension.
	SourceX uint32
	// SourceY: Top edge of that rectangle, in image pixels.
	SourceY uint32
	// SourceWidth: Width of that rectangle, in image pixels.
	SourceWidth uint32
	// SourceHeight: Height of that rectangle, in image pixels.
	SourceHeight uint32
	// Z: Stacking order. The snapshot is sorted by it, so drawing the array in
	// order is correct; `layer` is the same value split into the three bands
	// a renderer draws in.
	Z int32
	// Layer: Which band `z` falls in.
	Layer KittyLayer
	// Virtual: True for a placement the program positioned with unicode placeholders
	// rather than at a cursor position.
	//
	// It has no position of its own -- the cells that reference it decide
	// where it goes -- so `viewport_col` and `viewport_row` are zero and mean
	// nothing. Everything else is filled in, because a renderer that scans
	// cells for placeholders finds the placement by `image_id` and
	// `placement_id` and needs its source rectangle and size. A renderer that
	// does not do that scan should skip these.
	Virtual bool
	// Pad: Padding so the struct's layout matches across the C ABI. Not data.
	Pad uint16
}

// KittyImage mirrors the Zig `extern struct` of the same name.
type KittyImage struct {
	// Generation: Changes whenever the bytes behind `kittyImageData` change, including
	// when an animation advances a frame. Cache textures on it.
	Generation uint64
	// DataLen: The length `kittyImageData` will write.
	DataLen uint64
	// Width: The image's own size in pixels, which is what `source_*` on a placement
	// indexes into. Not the size it is drawn at.
	Width uint32
	// Height: The image's own height in pixels, the other half of `width`.
	Height uint32
	// Format: How the bytes `kittyImageData` writes are laid out per pixel.
	Format KittyFormat
	// Compression: Whether those bytes are compressed, and how. `.none` for most images.
	Compression KittyCompression
	// Pad: Padding so the struct's layout matches across the C ABI. Not data.
	Pad uint16
}

// KittyImage is reinterpreted as raw.KittyImageData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(KittyImage{})-unsafe.Sizeof(raw.KittyImageData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Generation)-unsafe.Offsetof(raw.KittyImageData{}.Generation)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.DataLen)-unsafe.Offsetof(raw.KittyImageData{}.DataLen)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Width)-unsafe.Offsetof(raw.KittyImageData{}.Width)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Height)-unsafe.Offsetof(raw.KittyImageData{}.Height)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Format)-unsafe.Offsetof(raw.KittyImageData{}.Format)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Compression)-unsafe.Offsetof(raw.KittyImageData{}.Compression)]
var _ = [1]struct{}{}[unsafe.Offsetof(KittyImage{}.Pad)-unsafe.Offsetof(raw.KittyImageData{}.Pad)]

func zigoGridPointFromRaw(value raw.GridPointData) GridPoint {
	return GridPoint{
		X: value.X,
		Y: value.Y,
	}
}

func zigoSelectionToRaw(value Selection) raw.SelectionData {
	return raw.SelectionData{
		StartX:    value.StartX,
		StartY:    value.StartY,
		EndX:      value.EndX,
		EndY:      value.EndY,
		Rectangle: zigoBoolToUint8(value.Rectangle),
	}
}

func zigoSelectionFromRaw(value raw.SelectionData) Selection {
	return Selection{
		StartX:    value.StartX,
		StartY:    value.StartY,
		EndX:      value.EndX,
		EndY:      value.EndY,
		Rectangle: value.Rectangle != 0,
	}
}

func zigoSelectionSliceCopyFromRaw(dst []Selection, values []raw.SelectionData, count int) {
	if count > len(dst) {
		count = len(dst)
	}
	if count > len(values) {
		count = len(values)
	}
	for i := 0; i < count; i++ {
		dst[i] = zigoSelectionFromRaw(values[i])
	}
}

func zigoFormatOptionsToRaw(value FormatOptions) raw.FormatOptionsData {
	return raw.FormatOptionsData{
		Format:                 uint8(value.Format),
		Unwrap:                 zigoBoolToUint8(value.Unwrap),
		KeepTrailingWhitespace: zigoBoolToUint8(value.KeepTrailingWhitespace),
		Cursor:                 zigoBoolToUint8(value.Cursor),
		NoStyles:               zigoBoolToUint8(value.NoStyles),
		NoHyperlinks:           zigoBoolToUint8(value.NoHyperlinks),
		ResolvePalette:         zigoBoolToUint8(value.ResolvePalette),
	}
}

func zigoRGBToRaw(value RGB) raw.RGBData {
	return raw.RGBData{
		R: value.R,
		G: value.G,
		B: value.B,
	}
}

func zigoRGBFromRaw(value raw.RGBData) RGB {
	return RGB{
		R: value.R,
		G: value.G,
		B: value.B,
	}
}

func zigoScrollbarFromRaw(value raw.ScrollbarData) Scrollbar {
	return Scrollbar{
		Total:  value.Total,
		Offset: value.Offset,
		Len:    value.Len,
	}
}

func zigoScrollRegionFromRaw(value raw.ScrollRegionData) ScrollRegion {
	return ScrollRegion{
		Top:    value.Top,
		Bottom: value.Bottom,
		Left:   value.Left,
		Right:  value.Right,
	}
}

func zigoGestureGeometryToRaw(value GestureGeometry) raw.GestureGeometryData {
	return raw.GestureGeometryData{
		Columns:      value.Columns,
		CellWidth:    value.CellWidth,
		PaddingLeft:  value.PaddingLeft,
		ScreenHeight: value.ScreenHeight,
	}
}

func zigoGesturePressEventToRaw(value GesturePressEvent) raw.GesturePressEventData {
	return raw.GesturePressEventData{
		X:                value.X,
		Y:                value.Y,
		Xpos:             value.Xpos,
		Ypos:             value.Ypos,
		MaxDistance:      value.MaxDistance,
		RepeatIntervalNs: value.RepeatIntervalNs,
		TimeNs:           value.TimeNs,
	}
}

func zigoGestureDragEventToRaw(value GestureDragEvent) raw.GestureDragEventData {
	return raw.GestureDragEventData{
		X:         value.X,
		Y:         value.Y,
		Xpos:      value.Xpos,
		Ypos:      value.Ypos,
		Rectangle: zigoBoolToUint8(value.Rectangle),
	}
}

func zigoDragMoveToRaw(value DragMove) raw.DragMoveData {
	return raw.DragMoveData{
		CellX:      value.CellX,
		CellY:      value.CellY,
		PixelX:     value.PixelX,
		PixelY:     value.PixelY,
		Operations: value.Operations.Backing(),
	}
}

func zigoFeedBoundaryFromRaw(value raw.FeedBoundaryData) FeedBoundary {
	return FeedBoundary{
		Consumed: value.Consumed,
		Reached:  value.Reached != 0,
	}
}

func zigoSnapshotProgressFromRaw(value raw.SnapshotProgressData) SnapshotProgress {
	return SnapshotProgress{
		Rows:      value.Rows,
		Remaining: value.Remaining,
		Pad:       value.Pad,
	}
}

func zigoRenderColorsFromRaw(value raw.RenderColorsData) RenderColors {
	return RenderColors{
		Background:     zigoRGBFromRaw(value.Background),
		Foreground:     zigoRGBFromRaw(value.Foreground),
		Cursor:         zigoRGBFromRaw(value.Cursor),
		CursorHasValue: value.CursorHasValue != 0,
	}
}

func zigoRenderCellFromRaw(value raw.RenderCellData) RenderCell {
	return RenderCell{
		Codepoint: rune(value.Codepoint),
		Fg:        zigoRGBFromRaw(value.Fg),
		Bg:        zigoRGBFromRaw(value.Bg),
		Flags:     CellFlagsFromBacking(value.Flags),
	}
}

func zigoRenderCellSliceCopyFromRaw(dst []RenderCell, values []raw.RenderCellData, count int) {
	if count > len(dst) {
		count = len(dst)
	}
	if count > len(values) {
		count = len(values)
	}
	for i := 0; i < count; i++ {
		dst[i] = zigoRenderCellFromRaw(values[i])
	}
}

func zigoKittyPlacementFromRaw(value raw.KittyPlacementData) KittyPlacement {
	return KittyPlacement{
		ImageID:      value.ImageID,
		PlacementID:  value.PlacementID,
		ViewportCol:  value.ViewportCol,
		ViewportRow:  value.ViewportRow,
		XOffset:      value.XOffset,
		YOffset:      value.YOffset,
		PixelWidth:   value.PixelWidth,
		PixelHeight:  value.PixelHeight,
		GridCols:     value.GridCols,
		GridRows:     value.GridRows,
		SourceX:      value.SourceX,
		SourceY:      value.SourceY,
		SourceWidth:  value.SourceWidth,
		SourceHeight: value.SourceHeight,
		Z:            value.Z,
		Layer:        KittyLayer(value.Layer),
		Virtual:      value.Virtual != 0,
		Pad:          value.Pad,
	}
}

func zigoKittyPlacementSliceCopyFromRaw(dst []KittyPlacement, values []raw.KittyPlacementData, count int) {
	if count > len(dst) {
		count = len(dst)
	}
	if count > len(values) {
		count = len(values)
	}
	for i := 0; i < count; i++ {
		dst[i] = zigoKittyPlacementFromRaw(values[i])
	}
}

func zigoKittyImageFromRaw(value raw.KittyImageData) KittyImage {
	return KittyImage{
		Generation:  value.Generation,
		DataLen:     value.DataLen,
		Width:       value.Width,
		Height:      value.Height,
		Format:      KittyFormat(value.Format),
		Compression: KittyCompression(value.Compression),
		Pad:         value.Pad,
	}
}

func zigoAttributeFromRaw(value raw.AttributeData) Attribute {
	switch AttributeTag(value.Tag) {
	case AttributeTagUnset:
		return AttributeUnset()
	case AttributeTagBold:
		return AttributeBold()
	case AttributeTagResetBold:
		return AttributeResetBold()
	case AttributeTagItalic:
		return AttributeItalic()
	case AttributeTagResetItalic:
		return AttributeResetItalic()
	case AttributeTagFaint:
		return AttributeFaint()
	case AttributeTagUnderline:
		return AttributeUnderline(Underline(value.Underline))
	case AttributeTagUnderlineColorRgb:
		return AttributeUnderlineColorRgb(RGB{R: value.UnderlineColorRgbR, G: value.UnderlineColorRgbG, B: value.UnderlineColorRgbB})
	case AttributeTagUnderlineColor256:
		return AttributeUnderlineColor256(value.UnderlineColor256)
	case AttributeTagResetUnderlineColor:
		return AttributeResetUnderlineColor()
	case AttributeTagOverline:
		return AttributeOverline()
	case AttributeTagResetOverline:
		return AttributeResetOverline()
	case AttributeTagBlink:
		return AttributeBlink()
	case AttributeTagResetBlink:
		return AttributeResetBlink()
	case AttributeTagInverse:
		return AttributeInverse()
	case AttributeTagResetInverse:
		return AttributeResetInverse()
	case AttributeTagInvisible:
		return AttributeInvisible()
	case AttributeTagResetInvisible:
		return AttributeResetInvisible()
	case AttributeTagStrikethrough:
		return AttributeStrikethrough()
	case AttributeTagResetStrikethrough:
		return AttributeResetStrikethrough()
	case AttributeTagDirectColorFg:
		return AttributeDirectColorFg(RGB{R: value.DirectColorFgR, G: value.DirectColorFgG, B: value.DirectColorFgB})
	case AttributeTagDirectColorBg:
		return AttributeDirectColorBg(RGB{R: value.DirectColorBgR, G: value.DirectColorBgG, B: value.DirectColorBgB})
	case AttributeTagColor256Fg:
		return AttributeColor256Fg(value.Color256Fg)
	case AttributeTagColor256Bg:
		return AttributeColor256Bg(value.Color256Bg)
	case AttributeTagNamedFg:
		return AttributeNamedFg(ColorName(value.NamedFg))
	case AttributeTagNamedBg:
		return AttributeNamedBg(ColorName(value.NamedBg))
	case AttributeTagBrightNamedFg:
		return AttributeBrightNamedFg(ColorName(value.BrightNamedFg))
	case AttributeTagBrightNamedBg:
		return AttributeBrightNamedBg(ColorName(value.BrightNamedBg))
	case AttributeTagResetFg:
		return AttributeResetFg()
	case AttributeTagResetBg:
		return AttributeResetBg()
	case AttributeTagUnknown:
		return AttributeUnknown()
	default:
		return Attribute{}
	}
}

// Attribute is a tagged-union value passed to native code by copy.
type Attribute struct {
	tag               AttributeTag
	underline         Underline
	underlineColorRgb RGB
	underlineColor256 uint8
	directColorFg     RGB
	directColorBg     RGB
	color256Fg        uint8
	color256Bg        uint8
	namedFg           ColorName
	namedBg           ColorName
	brightNamedFg     ColorName
	brightNamedBg     ColorName
}

// Tag returns the active Attribute variant.
func (value Attribute) Tag() AttributeTag { return value.tag }

// AsUnderline returns the underline payload and whether it is the active variant.
func (value Attribute) AsUnderline() (Underline, bool) {
	return value.underline, value.tag == AttributeTagUnderline
}

// AsUnderlineColorRgb returns the underline_color_rgb payload and whether it is the active variant.
func (value Attribute) AsUnderlineColorRgb() (RGB, bool) {
	return value.underlineColorRgb, value.tag == AttributeTagUnderlineColorRgb
}

// AsUnderlineColor256 returns the underline_color_256 payload and whether it is the active variant.
func (value Attribute) AsUnderlineColor256() (uint8, bool) {
	return value.underlineColor256, value.tag == AttributeTagUnderlineColor256
}

// AsDirectColorFg returns the direct_color_fg payload and whether it is the active variant.
func (value Attribute) AsDirectColorFg() (RGB, bool) {
	return value.directColorFg, value.tag == AttributeTagDirectColorFg
}

// AsDirectColorBg returns the direct_color_bg payload and whether it is the active variant.
func (value Attribute) AsDirectColorBg() (RGB, bool) {
	return value.directColorBg, value.tag == AttributeTagDirectColorBg
}

// AsColor256Fg returns the color_256_fg payload and whether it is the active variant.
func (value Attribute) AsColor256Fg() (uint8, bool) {
	return value.color256Fg, value.tag == AttributeTagColor256Fg
}

// AsColor256Bg returns the color_256_bg payload and whether it is the active variant.
func (value Attribute) AsColor256Bg() (uint8, bool) {
	return value.color256Bg, value.tag == AttributeTagColor256Bg
}

// AsNamedFg returns the named_fg payload and whether it is the active variant.
func (value Attribute) AsNamedFg() (ColorName, bool) {
	return value.namedFg, value.tag == AttributeTagNamedFg
}

// AsNamedBg returns the named_bg payload and whether it is the active variant.
func (value Attribute) AsNamedBg() (ColorName, bool) {
	return value.namedBg, value.tag == AttributeTagNamedBg
}

// AsBrightNamedFg returns the bright_named_fg payload and whether it is the active variant.
func (value Attribute) AsBrightNamedFg() (ColorName, bool) {
	return value.brightNamedFg, value.tag == AttributeTagBrightNamedFg
}

// AsBrightNamedBg returns the bright_named_bg payload and whether it is the active variant.
func (value Attribute) AsBrightNamedBg() (ColorName, bool) {
	return value.brightNamedBg, value.tag == AttributeTagBrightNamedBg
}

// AttributeUnset constructs the unset variant.
func AttributeUnset() Attribute {
	return Attribute{tag: AttributeTagUnset}
}

// AttributeBold constructs the bold variant.
func AttributeBold() Attribute {
	return Attribute{tag: AttributeTagBold}
}

// AttributeResetBold constructs the reset_bold variant.
func AttributeResetBold() Attribute {
	return Attribute{tag: AttributeTagResetBold}
}

// AttributeItalic constructs the italic variant.
func AttributeItalic() Attribute {
	return Attribute{tag: AttributeTagItalic}
}

// AttributeResetItalic constructs the reset_italic variant.
func AttributeResetItalic() Attribute {
	return Attribute{tag: AttributeTagResetItalic}
}

// AttributeFaint constructs the faint variant.
func AttributeFaint() Attribute {
	return Attribute{tag: AttributeTagFaint}
}

// AttributeUnderline constructs the underline variant.
func AttributeUnderline(value Underline) Attribute {
	return Attribute{tag: AttributeTagUnderline, underline: value}
}

// AttributeUnderlineColorRgb constructs the underline_color_rgb variant.
func AttributeUnderlineColorRgb(value RGB) Attribute {
	return Attribute{tag: AttributeTagUnderlineColorRgb, underlineColorRgb: value}
}

// AttributeUnderlineColor256 constructs the underline_color_256 variant.
func AttributeUnderlineColor256(n uint8) Attribute {
	return Attribute{tag: AttributeTagUnderlineColor256, underlineColor256: n}
}

// AttributeResetUnderlineColor constructs the reset_underline_color variant.
func AttributeResetUnderlineColor() Attribute {
	return Attribute{tag: AttributeTagResetUnderlineColor}
}

// AttributeOverline constructs the overline variant.
func AttributeOverline() Attribute {
	return Attribute{tag: AttributeTagOverline}
}

// AttributeResetOverline constructs the reset_overline variant.
func AttributeResetOverline() Attribute {
	return Attribute{tag: AttributeTagResetOverline}
}

// AttributeBlink constructs the blink variant.
func AttributeBlink() Attribute {
	return Attribute{tag: AttributeTagBlink}
}

// AttributeResetBlink constructs the reset_blink variant.
func AttributeResetBlink() Attribute {
	return Attribute{tag: AttributeTagResetBlink}
}

// AttributeInverse constructs the inverse variant.
func AttributeInverse() Attribute {
	return Attribute{tag: AttributeTagInverse}
}

// AttributeResetInverse constructs the reset_inverse variant.
func AttributeResetInverse() Attribute {
	return Attribute{tag: AttributeTagResetInverse}
}

// AttributeInvisible constructs the invisible variant.
func AttributeInvisible() Attribute {
	return Attribute{tag: AttributeTagInvisible}
}

// AttributeResetInvisible constructs the reset_invisible variant.
func AttributeResetInvisible() Attribute {
	return Attribute{tag: AttributeTagResetInvisible}
}

// AttributeStrikethrough constructs the strikethrough variant.
func AttributeStrikethrough() Attribute {
	return Attribute{tag: AttributeTagStrikethrough}
}

// AttributeResetStrikethrough constructs the reset_strikethrough variant.
func AttributeResetStrikethrough() Attribute {
	return Attribute{tag: AttributeTagResetStrikethrough}
}

// AttributeDirectColorFg constructs the direct_color_fg variant.
func AttributeDirectColorFg(value RGB) Attribute {
	return Attribute{tag: AttributeTagDirectColorFg, directColorFg: value}
}

// AttributeDirectColorBg constructs the direct_color_bg variant.
func AttributeDirectColorBg(value RGB) Attribute {
	return Attribute{tag: AttributeTagDirectColorBg, directColorBg: value}
}

// AttributeColor256Fg constructs the color_256_fg variant.
func AttributeColor256Fg(n uint8) Attribute {
	return Attribute{tag: AttributeTagColor256Fg, color256Fg: n}
}

// AttributeColor256Bg constructs the color_256_bg variant.
func AttributeColor256Bg(n uint8) Attribute {
	return Attribute{tag: AttributeTagColor256Bg, color256Bg: n}
}

// AttributeNamedFg constructs the named_fg variant.
func AttributeNamedFg(value ColorName) Attribute {
	return Attribute{tag: AttributeTagNamedFg, namedFg: value}
}

// AttributeNamedBg constructs the named_bg variant.
func AttributeNamedBg(value ColorName) Attribute {
	return Attribute{tag: AttributeTagNamedBg, namedBg: value}
}

// AttributeBrightNamedFg constructs the bright_named_fg variant.
func AttributeBrightNamedFg(value ColorName) Attribute {
	return Attribute{tag: AttributeTagBrightNamedFg, brightNamedFg: value}
}

// AttributeBrightNamedBg constructs the bright_named_bg variant.
func AttributeBrightNamedBg(value ColorName) Attribute {
	return Attribute{tag: AttributeTagBrightNamedBg, brightNamedBg: value}
}

// AttributeResetFg constructs the reset_fg variant.
func AttributeResetFg() Attribute {
	return Attribute{tag: AttributeTagResetFg}
}

// AttributeResetBg constructs the reset_bg variant.
func AttributeResetBg() Attribute {
	return Attribute{tag: AttributeTagResetBg}
}

// AttributeUnknown constructs the unknown variant.
func AttributeUnknown() Attribute {
	return Attribute{tag: AttributeTagUnknown}
}

// ScrollViewport is a tagged-union value passed to native code by copy.
type ScrollViewport struct {
	tag   ScrollViewportTag
	delta int
	row   uint
}

// Tag returns the active ScrollViewport variant.
func (value ScrollViewport) Tag() ScrollViewportTag { return value.tag }

// AsDelta returns the delta payload and whether it is the active variant.
func (value ScrollViewport) AsDelta() (int, bool) {
	return value.delta, value.tag == ScrollViewportTagDelta
}

// AsRow returns the row payload and whether it is the active variant.
func (value ScrollViewport) AsRow() (uint, bool) {
	return value.row, value.tag == ScrollViewportTagRow
}

// ScrollViewportTop constructs the top variant.
func ScrollViewportTop() ScrollViewport {
	return ScrollViewport{tag: ScrollViewportTagTop}
}

// ScrollViewportBottom constructs the bottom variant.
func ScrollViewportBottom() ScrollViewport {
	return ScrollViewport{tag: ScrollViewportTagBottom}
}

// ScrollViewportDelta constructs the delta variant.
func ScrollViewportDelta(n int) ScrollViewport {
	return ScrollViewport{tag: ScrollViewportTagDelta, delta: n}
}

// ScrollViewportRow constructs the row variant.
func ScrollViewportRow(n uint) ScrollViewport {
	return ScrollViewport{tag: ScrollViewportTagRow, row: n}
}
