// Code generated by zigo. DO NOT EDIT.

package gostty

import (
	"io"
	"runtime/cgo"
	"sync/atomic"
	"unsafe"

	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

type zigoHandle = lifecycle.Handle

type zigoChildHandle = lifecycle.ChildHandle

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return lifecycle.CheckedPointer(operation, value)
}
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	return lifecycle.PoisonAfterPanic(err, handles...)
}

// The lifecycle methods of every handle here stay unexported. The shared
// runtime reaches them through this registration.
func init() {
	lifecycle.Register(lifecycle.Methods[*Terminal]{Acquire: (*Terminal).zigoAcquire, Release: (*Terminal).zigoRelease, Poison: (*Terminal).zigoPoison, AcquireChild: (*Terminal).zigoAcquireChild, DropChild: (*Terminal).zigoDropChild})
	lifecycle.Register(lifecycle.Methods[*Screen]{Acquire: (*Screen).zigoAcquire, Release: (*Screen).zigoRelease, Poison: (*Screen).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*Search]{Acquire: (*Search).zigoAcquire, Release: (*Search).zigoRelease, Poison: (*Search).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*GridRef]{Acquire: (*GridRef).zigoAcquire, Release: (*GridRef).zigoRelease, Poison: (*GridRef).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*Gesture]{Acquire: (*Gesture).zigoAcquire, Release: (*Gesture).zigoRelease, Poison: (*Gesture).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*Stream]{Acquire: (*Stream).zigoAcquire, Release: (*Stream).zigoRelease, Poison: (*Stream).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*ClipboardRequest]{Acquire: (*ClipboardRequest).zigoAcquire, Release: (*ClipboardRequest).zigoRelease, Poison: (*ClipboardRequest).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*OSCParser]{Acquire: (*OSCParser).zigoAcquire, Release: (*OSCParser).zigoRelease, Poison: (*OSCParser).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*Snapshot]{Acquire: (*Snapshot).zigoAcquire, Release: (*Snapshot).zigoRelease, Poison: (*Snapshot).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*SnapshotDecoder]{Acquire: (*SnapshotDecoder).zigoAcquire, Release: (*SnapshotDecoder).zigoRelease, Poison: (*SnapshotDecoder).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*RenderState]{Acquire: (*RenderState).zigoAcquire, Release: (*RenderState).zigoRelease, Poison: (*RenderState).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*KittyImages]{Acquire: (*KittyImages).zigoAcquire, Release: (*KittyImages).zigoRelease, Poison: (*KittyImages).zigoPoison})
}

// DragHandler is the Go callback signature accepted by the generated binding.
// Reentrancy: allowed; the callback may re-enter the binding while it is running.
// Thread: caller; the callback runs on the thread that initiated the native call.
type DragHandler func(DragNotice, string)

// ClipboardHandler is the Go callback signature accepted by the generated binding.
// Reentrancy: allowed; the callback may re-enter the binding while it is running.
// Thread: caller; the callback runs on the thread that initiated the native call.
type ClipboardHandler func(*ClipboardRequest)

func zigoBoolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var zigoActiveCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func zigoNewDragHandlerHandle(value DragHandler) zigoCallbackHandle {
	stored := func(p0 uint32, p1 string) {
		value(DragNoticeFromBacking(p0), p1)
	}
	handle := cgo.NewHandle(&raw.CallbackState{Fn: stored})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoNewClipboardHandlerHandle(value ClipboardHandler) zigoCallbackHandle {
	stored := func(p0 unsafe.Pointer) {
		value(zigoNewBorrowedClipboardRequest(p0, nil))
	}
	handle := cgo.NewHandle(&raw.CallbackState{Fn: stored})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoNewWriterStreamHandle(value io.Writer) zigoCallbackHandle {
	handle := cgo.NewHandle(&raw.CallbackState{Writer: value})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoNewReaderStreamHandle(value io.Reader) zigoCallbackHandle {
	handle := cgo.NewHandle(&raw.CallbackState{Reader: value})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoDeleteCallbackHandle(handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	handle.Delete()
	zigoActiveCallbackHandles.Add(-1)
}

func zigoActiveCallbackHandleCount() int64 { return zigoActiveCallbackHandles.Load() }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}

// zigoStreamError reports the error the Go stream behind handle returned
// inside the native call that has just finished, wrapped so the caller can
// match it with errors.Is.
func zigoStreamError(operation string, parameter string, handle zigoCallbackHandle) error {
	if err, ok := raw.TakeStreamError(handle); ok {
		return &StreamError{Operation: operation, Parameter: parameter, Err: err}
	}
	return nil
}

// zigoReaderBytes returns the bytes a reader can hand over whole, or nil
// when it cannot and the native call has to read it a chunk at a time.
// The slice is never nil when the fast path applies, so an empty reader
// is still told apart from one that has to be streamed.
func zigoReaderBytes(value io.Reader) []byte {
	var data []byte
	switch source := value.(type) {
	case interface{ zigoBytes() []byte }:
		data = source.zigoBytes()
	case interface{ Bytes() []byte }:
		data = source.Bytes()
	default:
		return nil
	}
	if data == nil {
		return []byte{}
	}
	return data
}

// gosttyMustSucceed panics with a typed error, for a Must variant of a
// function whose only result is the error.
func gosttyMustSucceed(err error) {
	if err != nil {
		panic(err)
	}
}

// gosttyMustValue panics with a typed error, for a Must variant with one result.
func gosttyMustValue[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

// gosttyMustMatch panics with a typed error, for a Must variant whose result
// carries a presence flag beside the value.
func gosttyMustMatch[T any](value T, matched bool, err error) (T, bool) {
	if err != nil {
		panic(err)
	}
	return value, matched
}
