// Code generated by zigo. DO NOT EDIT.

package gostty

import (
	"io"
	"runtime"
	"strings"
	"sync"
	"unsafe"

	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

// Terminal owns mutable terminal state. Serialize all calls, including
// getters, with calls on its streams, screens, searches, gestures and grid
// references. Handle locks protect lifetime only; they do not serialize native
// operations. Callbacks may answer their supplied request but must not
// recursively feed, resize, reset or close the same terminal.
type Terminal struct {
	ptr      unsafe.Pointer
	mu       sync.Mutex
	active   int
	children int
	closed   bool
	poison   *NativePanicError
	cleanup  runtime.Cleanup
}

// zigoAcquire pins te open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (te *Terminal) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if te == nil {
		return nil, &HandleError{Operation: operation}
	}
	te.mu.Lock()
	defer te.mu.Unlock()
	if te.closed || te.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if te.poison != nil {
		return nil, te.poison.Poisoned(operation)
	}
	te.active++
	return te.ptr, nil
}

func (te *Terminal) zigoRelease() {
	if te == nil {
		return
	}
	te.mu.Lock()
	te.active--
	state, release := te.zigoTakeLocked()
	te.mu.Unlock()
	if release {
		zigoCleanupTerminal(state)
	}
}

// zigoPoison marks te unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (te *Terminal) zigoPoison(cause *NativePanicError) {
	if te == nil {
		return
	}
	te.mu.Lock()
	defer te.mu.Unlock()
	if te.poison == nil {
		te.poison = cause
		te.cleanup.Stop()
	}
}

// zigoAcquireChild reserves one dependent child atomically with the call pin.
func (te *Terminal) zigoAcquireChild(operation string) (unsafe.Pointer, zigoChildHandle, error) {
	if te == nil {
		return nil, nil, &HandleError{Operation: operation}
	}
	te.mu.Lock()
	defer te.mu.Unlock()
	if te.closed || te.ptr == nil {
		return nil, nil, &HandleError{Operation: operation}
	}
	if te.poison != nil {
		return nil, nil, te.poison.Poisoned(operation)
	}
	te.active++
	te.children++
	return te.ptr, te, nil
}

func (te *Terminal) zigoDropChild() {
	if te == nil {
		return
	}
	te.mu.Lock()
	te.children--
	te.mu.Unlock()
}

type zigoTerminalCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewTerminal(ptr unsafe.Pointer) *Terminal {
	value := &Terminal{ptr: ptr}
	state := zigoTerminalCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupTerminal, state)
	return value
}

func zigoCleanupTerminal(state zigoTerminalCleanupState) {
	if state.ptr != nil {
		raw.TerminalDeinit(state.ptr)
	}
}

// Close releases the native Terminal resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native or a dependent child remains open.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (te *Terminal) Close() error {
	if te == nil {
		return nil
	}
	te.mu.Lock()
	if te.closed {
		te.mu.Unlock()
		return nil
	}
	if te.children != 0 {
		children := te.children
		te.mu.Unlock()
		return &HandleInUseError{Operation: "Terminal.Close", Children: children}
	}
	if te.active != 0 {
		active := te.active
		te.mu.Unlock()
		return &HandleInUseError{Operation: "Terminal.Close", Children: active}
	}
	te.closed = true
	te.cleanup.Stop()
	state, release := te.zigoTakeLocked()
	te.mu.Unlock()
	if release {
		zigoCleanupTerminal(state)
	}
	runtime.KeepAlive(te)
	return nil
}

var _ io.Closer = (*Terminal)(nil)

// zigoTakeLocked hands out what is left to release once te is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (te *Terminal) zigoTakeLocked() (zigoTerminalCleanupState, bool) {
	if !te.closed || te.active != 0 || te.ptr == nil {
		return zigoTerminalCleanupState{}, false
	}
	state := zigoTerminalCleanupState{ptr: te.ptr}
	te.ptr = nil
	if te.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// TerminalConfig configures a new terminal. Cols and Rows must be nonzero.
// Nil optional fields retain native defaults; pointers distinguish an explicit
// zero or false from an omitted setting. Configuration is copied during creation.
type TerminalConfig struct {
	Cols, Rows         uint16
	ScrollbackMaxBytes *uint // Zero disables scrollback immediately.
	ScrollbackMaxLines *uint // Pruned at native page boundaries, not an exact row cap.
	BackgroundColor    *RGB
	ForegroundColor    *RGB
	CursorColor        *RGB
	CursorBlink        *bool
	ModeDefaults       []ModeDefault
}

// ModeDefault sets both the current value and reset default of a mode.
type ModeDefault struct {
	Mode    Mode
	Enabled bool
}

// NewTerminalWithConfig creates and configures a terminal. The settings
// ghostty's own Options carries -- scrollback and the cursor defaults -- are
// passed to the constructor, so they hold from the first byte fed rather than
// from a setter afterwards. Colors and mode defaults cannot cross at
// construction and are applied after; a failure in one of those closes the
// newly created terminal, so no partially configured handle escapes.
func NewTerminalWithConfig(cfg TerminalConfig, extra ...TerminalOption) (_ *Terminal, err error) {
	if cfg.Cols == 0 {
		return nil, &RangeError{Operation: "NewTerminalWithConfig", Parameter: "Cols", Type: "nonzero cell count"}
	}
	if cfg.Rows == 0 {
		return nil, &RangeError{Operation: "NewTerminalWithConfig", Parameter: "Rows", Type: "nonzero cell count"}
	}
	for _, mode := range cfg.ModeDefaults {
		if !mode.Mode.IsKnown() {
			return nil, &RangeError{Operation: "NewTerminalWithConfig", Parameter: "ModeDefaults", Type: "known Mode"}
		}
	}

	// A nil field means "leave ghostty's default", which is what omitting the
	// option does, so the nil checks decide whether to append rather than what
	// to pass.
	opts := make([]TerminalOption, 0, 3+len(extra))
	if cfg.ScrollbackMaxBytes != nil {
		opts = append(opts, WithTerminalMaxScrollbackBytes(cfg.ScrollbackMaxBytes))
	}
	if cfg.ScrollbackMaxLines != nil {
		opts = append(opts, WithTerminalMaxScrollbackLines(cfg.ScrollbackMaxLines))
	}
	if cfg.CursorBlink != nil {
		opts = append(opts, WithTerminalDefaultCursorBlink(cfg.CursorBlink))
	}
	opts = append(opts, extra...)

	term, err := NewTerminal(cfg.Cols, cfg.Rows, opts...)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err != nil {
			_ = term.Close()
		}
	}()
	if cfg.BackgroundColor != nil {
		if err = term.SetDefaultBackgroundColor(*cfg.BackgroundColor); err != nil {
			return nil, err
		}
	}
	if cfg.ForegroundColor != nil {
		if err = term.SetDefaultForegroundColor(*cfg.ForegroundColor); err != nil {
			return nil, err
		}
	}
	if cfg.CursorColor != nil {
		if err = term.SetDefaultCursorColor(*cfg.CursorColor); err != nil {
			return nil, err
		}
	}
	for _, mode := range cfg.ModeDefaults {
		if err = term.SetDefaultMode(mode.Mode, mode.Enabled); err != nil {
			return nil, err
		}
	}
	return term, nil
}

// StreamConfig configures the parser and its embedder identity. Zero limits
// disable continuation tracking and unknown-sequence capture respectively.
// A nil Version leaves Ghostty's identity unchanged. Callbacks run synchronously;
// only request-response calls may reenter the active terminal's bindings.
type StreamConfig struct {
	ContinuationMaxBytes uint
	UnknownMaxBytes      uint
	Version              *VersionReport
	EnquiryResponse      string
	ColorScheme          *ColorScheme
	ClipboardRead        ClipboardHandler
	ClipboardWrite       ClipboardHandler
}

// VersionReport is the application identity returned by XTVERSION.
type VersionReport struct{ Name, Version string }

// NewStreamWithConfig creates a child stream and applies all settings before
// returning it. On failure it closes the stream and releases the parent claim.
func (t *Terminal) NewStreamWithConfig(cfg StreamConfig) (_ *Stream, err error) {
	s, err := t.NewStream(cfg.ContinuationMaxBytes)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err != nil {
			_ = s.Close()
		}
	}()
	if err = s.SetUnknownMaxBytes(cfg.UnknownMaxBytes); err != nil {
		return nil, err
	}
	if cfg.Version != nil {
		if err = s.SetVersionReport(cfg.Version.Name, cfg.Version.Version); err != nil {
			return nil, err
		}
	}
	if err = s.SetEnquiryResponse(cfg.EnquiryResponse); err != nil {
		return nil, err
	}
	if cfg.ColorScheme != nil {
		if *cfg.ColorScheme != ColorSchemeDark && *cfg.ColorScheme != ColorSchemeLight {
			return nil, &RangeError{Operation: "Terminal.NewStreamWithConfig", Parameter: "ColorScheme", Type: "ColorScheme"}
		}
		if err = s.ColorSchemeChanged(*cfg.ColorScheme); err != nil {
			return nil, err
		}
	}
	if cfg.ClipboardRead != nil {
		if err = s.OnClipboardReadRequest(cfg.ClipboardRead); err != nil {
			return nil, err
		}
	}
	if cfg.ClipboardWrite != nil {
		if err = s.OnClipboardWriteRequest(cfg.ClipboardWrite); err != nil {
			return nil, err
		}
	}
	return s, nil
}

// The option constructors below take values where the generated ones take
// pointers. `?usize` and `?bool` in ghostty's Options are three-state -- unset,
// or set to a number that may be zero -- so the generated `With*` spell that
// with a pointer. A caller who is calling the option at all has a value in
// hand, and `&` on a literal is not Go one can write, so these wrap it.

// WithScrollbackMaxBytes sets the maximum scrollback allocation in bytes.
// Zero disables scrollback immediately.
func WithScrollbackMaxBytes(bytes uint) TerminalOption {
	return WithTerminalMaxScrollbackBytes(&bytes)
}

// WithScrollbackMaxLines sets the maximum number of physical lines retained in
// scrollback. Pruned at native page boundaries, not an exact row cap.
func WithScrollbackMaxLines(lines uint) TerminalOption {
	return WithTerminalMaxScrollbackLines(&lines)
}

// WithDefaultCursorBlink sets the cursor blink state restored by DECSCUSR
// default and RIS.
func WithDefaultCursorBlink(blink bool) TerminalOption {
	return WithTerminalDefaultCursorBlink(&blink)
}

// MustNewTerminal creates a terminal with the given options, panicking on failure.
func MustNewTerminal(cols, rows uint16, opts ...TerminalOption) *Terminal {
	term, err := NewTerminal(cols, rows, opts...)
	if err != nil {
		panic(err)
	}
	return term
}

// StreamOption configures a Stream.
type StreamOption func(*StreamConfig)

// WithContinuationMaxBytes sets the maximum number of replay-safe VT continuation bytes retained.
func WithContinuationMaxBytes(bytes uint) StreamOption {
	return func(c *StreamConfig) { c.ContinuationMaxBytes = bytes }
}

// WithUnknownMaxBytes sets the maximum number of bytes retained for an unsupported escape sequence.
func WithUnknownMaxBytes(bytes uint) StreamOption {
	return func(c *StreamConfig) { c.UnknownMaxBytes = bytes }
}

// WithVersionReport configures the application identity returned by XTVERSION.
func WithVersionReport(name, version string) StreamOption {
	return func(c *StreamConfig) { c.Version = &VersionReport{Name: name, Version: version} }
}

// WithEnquiryResponse configures the response to ENQ (0x05).
func WithEnquiryResponse(response string) StreamOption {
	return func(c *StreamConfig) { c.EnquiryResponse = response }
}

// WithColorScheme sets the terminal color scheme (ColorSchemeDark or ColorSchemeLight).
func WithColorScheme(scheme ColorScheme) StreamOption {
	return func(c *StreamConfig) { c.ColorScheme = &scheme }
}

// WithClipboardReadHandler registers a handler for clipboard read requests.
func WithClipboardReadHandler(handler ClipboardHandler) StreamOption {
	return func(c *StreamConfig) { c.ClipboardRead = handler }
}

// WithClipboardWriteHandler registers a handler for clipboard write requests.
func WithClipboardWriteHandler(handler ClipboardHandler) StreamOption {
	return func(c *StreamConfig) { c.ClipboardWrite = handler }
}

// NewStreamWithOptions creates a child stream and applies functional options before returning it.
func (t *Terminal) NewStreamWithOptions(opts ...StreamOption) (*Stream, error) {
	var cfg StreamConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return t.NewStreamWithConfig(cfg)
}

// FormatString formats the active screen contents, including scrollback,
// according to opts and returns the result as a string.
func (t *Terminal) FormatString(opts FormatOptions) (string, error) {
	var buf strings.Builder
	if err := t.Format(opts, &buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// PlainText returns the active screen contents, including scrollback, as
// trimmed plain text. Use FormatString with KeepTrailingWhitespace to preserve
// trailing spaces.
func (t *Terminal) PlainText() (string, error) {
	return t.FormatString(FormatOptions{
		Format: FormatterFormatPlain,
	})
}

// FormatString formats the screen contents (including scrollback) according to opts and returns a string.
func (s *Screen) FormatString(opts FormatOptions) (string, error) {
	var buf strings.Builder
	if err := s.Format(opts, &buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// PlainText returns the screen contents (including scrollback) as trimmed plain
// text. Use FormatString with KeepTrailingWhitespace to preserve trailing spaces.
func (s *Screen) PlainText() (string, error) {
	return s.FormatString(FormatOptions{
		Format: FormatterFormatPlain,
	})
}

// SessionConfig configures both the terminal a session owns and its primary
// stream. TerminalOptions are the generated constructor options, applied after
// the fields TerminalConfig maps to the same options, so they win on conflict.
type SessionConfig struct {
	Terminal        TerminalConfig
	TerminalOptions []TerminalOption
	Stream          StreamConfig
}

// SessionOption configures a SessionConfig.
type SessionOption func(*SessionConfig)

// WithTerminalConfig sets the underlying TerminalConfig.
func WithTerminalConfig(cfg TerminalConfig) SessionOption {
	return func(c *SessionConfig) { c.Terminal = cfg }
}

// WithStreamConfig sets the underlying StreamConfig.
func WithStreamConfig(cfg StreamConfig) SessionOption {
	return func(c *SessionConfig) { c.Stream = cfg }
}

// WithTerminalOptions adds constructor options for the session's terminal.
// A TerminalOption is the generated kind, which the constructor consumes; it
// cannot be applied to a TerminalConfig, so it is collected rather than run here.
func WithTerminalOptions(opts ...TerminalOption) SessionOption {
	return func(c *SessionConfig) {
		c.TerminalOptions = append(c.TerminalOptions, opts...)
	}
}

// WithStreamOptions applies functional options to the session's stream.
func WithStreamOptions(opts ...StreamOption) SessionOption {
	return func(c *SessionConfig) {
		for _, opt := range opts {
			opt(&c.Stream)
		}
	}
}

// New is the short way in, and what most programs want: a terminal with a
// stream already wired to it, under one handle with one Close.
//
//	t, err := gostty.New(80, 24)
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer t.Close()
//	fmt.Fprintf(t, "Hello, \033[1;32mworld\033[0m!\r\n")
//	out, _ := t.PlainText()
//
// A Session is an io.Writer, so VT data goes in through fmt.Fprintf, io.Copy,
// or anything else that writes. Reach the pieces with Terminal() and Stream()
// when a call is not on the session itself.
//
// Terminal is not an io.Writer, and deliberately: a stream carries parser
// state across writes and is a child handle with its own lifetime, so a
// terminal that made one silently would be a terminal whose Close could fail
// for a reason the caller never asked for. The session is where that pair is
// owned together.
//
// NewTerminal is still there for a caller who wants the terminal alone --
// replaying a snapshot, or driving it only through the printing methods.
// NewSession adopts an already-built terminal; New builds the pair from
// options. If either construction step fails, nothing escapes.
func New(cols, rows uint16, opts ...SessionOption) (*Session, error) {
	cfg := SessionConfig{Terminal: TerminalConfig{Cols: cols, Rows: rows}}
	for _, opt := range opts {
		opt(&cfg)
	}
	term, err := NewTerminalWithConfig(cfg.Terminal, cfg.TerminalOptions...)
	if err != nil {
		return nil, err
	}
	stream, err := term.NewStreamWithConfig(cfg.Stream)
	if err != nil {
		_ = term.Close()
		return nil, err
	}
	return NewSession(term).AddStream(stream), nil
}

// MustNew creates a session with New and panics on failure. For tests and for
// program startup, where a failure has nowhere to go.
func MustNew(cols, rows uint16, opts ...SessionOption) *Session {
	sess, err := New(cols, rows, opts...)
	if err != nil {
		panic(err)
	}
	return sess
}

// Formatter returns a reusable formatter for the session terminal's active
// screen contents, including scrollback.
func (s *Session) Formatter(opts FormatOptions) *Formatter {
	return s.Terminal().Formatter(opts)
}

// Stream returns the session's primary stream: the first one adopted, which is
// the one New wired to the terminal. It is nil for a session
// that has adopted no stream, and after Close.
func (s *Session) Stream() *Stream {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if len(s.streams) == 0 {
		return nil
	}
	return s.streams[0]
}

// Write feeds bytes into the session's primary stream, satisfying io.Writer.
func (s *Session) Write(p []byte) (int, error) {
	stream := s.Stream()
	if stream == nil {
		return 0, &HandleError{Operation: "Session.Write"}
	}
	return stream.Write(p)
}

// WriteString feeds str into the session's primary stream, satisfying io.StringWriter.
func (s *Session) WriteString(str string) (int, error) {
	stream := s.Stream()
	if stream == nil {
		return 0, &HandleError{Operation: "Session.WriteString"}
	}
	return stream.WriteString(str)
}

// FormatString formats the active screen area and returns the result as a string.
func (s *Session) FormatString(opts FormatOptions) (string, error) {
	return s.Terminal().FormatString(opts)
}

// PlainText returns the active screen contents, including scrollback, as
// trimmed plain text.
func (s *Session) PlainText() (string, error) {
	return s.Terminal().PlainText()
}

var (
	_ io.Writer       = (*Session)(nil)
	_ io.StringWriter = (*Session)(nil)
	_ io.Closer       = (*Session)(nil)
	_ io.StringWriter = (*Stream)(nil)
)

// RGB is an opaque color stored as red, green and blue bytes.
// It implements image/color.Color with a fully opaque alpha channel.
type RGB [3]byte

// R returns the red channel.
func (c RGB) R() byte { return c[0] }

// G returns the green channel.
func (c RGB) G() byte { return c[1] }

// B returns the blue channel.
func (c RGB) B() byte { return c[2] }

func rgbToRaw(c RGB) raw.RGBData {
	return raw.RGBData{R: c[0], G: c[1], B: c[2]}
}

func rgbFromRaw(c raw.RGBData) RGB {
	return RGB{c.R, c.G, c.B}
}

// NewRGB builds a color from its three channels.
func NewRGB(r, g, b uint8) RGB {
	return RGB{r, g, b}
}

// RGBFromUint32 reads a color from the packed 0xRRGGBB form, which is how VT
// sequences and most configuration formats carry one. Bits above the low 24
// are ignored.
func RGBFromUint32(v uint32) RGB {
	return RGB{uint8(v >> 16), uint8(v >> 8), uint8(v)}
}

// Uint32 returns the color packed as 0xRRGGBB.
func (c RGB) Uint32() uint32 {
	return uint32(c.R())<<16 | uint32(c.G())<<8 | uint32(c.B())
}

// RGBA implements image/color.Color. The terminal has no alpha channel, so the
// color is always fully opaque, and each channel is scaled to 16 bits the way
// the standard library's own 8-bit colors are.
func (c RGB) RGBA() (r, g, b, a uint32) {
	r = uint32(c.R())
	r |= r << 8
	g = uint32(c.G())
	g |= g << 8
	b = uint32(c.B())
	b |= b << 8
	return r, g, b, 0xffff
}

const zigoHexDigits = "0123456789abcdef"

// String returns the color in CSS hex form, "#rrggbb".
func (c RGB) String() string {
	out := [7]byte{'#'}
	for i, v := range [3]uint8{c.R(), c.G(), c.B()} {
		out[1+i*2] = zigoHexDigits[v>>4]
		out[2+i*2] = zigoHexDigits[v&0xf]
	}
	return string(out[:])
}

// ParseRGB reads "#rrggbb" or "rrggbb", in either case. The three-digit CSS
// shorthand is not accepted: it is ambiguous next to a truncated six-digit
// value, and nothing the terminal emits uses it.
func ParseRGB(text string) (RGB, error) {
	fail := func() (RGB, error) {
		return RGB{}, &RangeError{Operation: "ParseRGB", Parameter: "text", Type: `a "#rrggbb" color`}
	}
	body := strings.TrimPrefix(text, "#")
	if len(body) != 6 {
		return fail()
	}
	var out [3]uint8
	for i := range out {
		hi, okHi := zigoHexNibble(body[i*2])
		lo, okLo := zigoHexNibble(body[i*2+1])
		if !okHi || !okLo {
			return fail()
		}
		out[i] = hi<<4 | lo
	}
	return RGB(out), nil
}

func zigoHexNibble(b byte) (uint8, bool) {
	switch {
	case b >= '0' && b <= '9':
		return b - '0', true
	case b >= 'a' && b <= 'f':
		return b - 'a' + 10, true
	case b >= 'A' && b <= 'F':
		return b - 'A' + 10, true
	}
	return 0, false
}

// Formatter formats the same target repeatedly under one set of options,
// reusing its buffer across calls. Format and Screen.Format allocate a result
// per call, which is right for a one-off dump and wasteful for a renderer
// doing it every frame; a Formatter is the second case.
//
// A Formatter owns no native resource. It holds the handle it was built from
// and nothing else, so there is no Close: it is done with when it goes out of
// scope, and a call after its target is closed reports ErrInvalidHandle the
// same way a direct call would.
//
// A Formatter is not safe for concurrent use, and the slice Append and Bytes
// return is only valid until the next call on the same Formatter.
type Formatter struct {
	// Exactly one of these is set. A terminal formats its active screen area
	// as it is now, which is what a renderer wants; a screen formats its whole
	// contents including scrollback, and stays the screen it was built from
	// even after the program switches away from it.
	terminal *Terminal
	screen   *Screen
	opts     FormatOptions
	buf      []byte
}

// Formatter returns a reusable formatter for the terminal's active screen
// area. It follows the active screen, so a program switching to the alternate
// screen changes what the same Formatter produces.
func (t *Terminal) Formatter(opts FormatOptions) *Formatter {
	return &Formatter{terminal: t, opts: opts}
}

// Formatter returns a reusable formatter for the screen's contents, scrollback
// included. It stays bound to this screen whether or not it is the active one.
func (s *Screen) Formatter(opts FormatOptions) *Formatter {
	return &Formatter{screen: s, opts: opts}
}

// Options returns the options the formatter writes with.
func (f *Formatter) Options() FormatOptions { return f.opts }

// SetOptions replaces the options for subsequent calls.
func (f *Formatter) SetOptions(opts FormatOptions) { f.opts = opts }

// zigoInto writes one formatting pass into w.
func (f *Formatter) zigoInto(w io.Writer) error {
	if f.screen != nil {
		return f.screen.Format(f.opts, w)
	}
	return f.terminal.Format(f.opts, w)
}

// zigoFill refills the internal buffer with one formatting pass.
func (f *Formatter) zigoFill() error {
	dst := zigoAppendWriter{buf: f.buf[:0]}
	err := f.zigoInto(&dst)
	f.buf = dst.buf
	return err
}

// Bytes formats into the formatter's own buffer and returns it. The slice is
// only valid until the next call on this Formatter; copy it, or use Append,
// to keep it.
func (f *Formatter) Bytes() ([]byte, error) {
	if err := f.zigoFill(); err != nil {
		return nil, err
	}
	return f.buf, nil
}

// Append formats and appends the result to dst, returning the extended slice.
// This is the allocation-free form: a caller that keeps one slice across
// frames and passes it back as dst[:0] never allocates after the first.
func (f *Formatter) Append(dst []byte) ([]byte, error) {
	out := zigoAppendWriter{buf: dst}
	if err := f.zigoInto(&out); err != nil {
		return dst, err
	}
	return out.buf, nil
}

// String formats and returns the result as a string. Unlike Bytes, the result
// is a copy the caller may keep.
func (f *Formatter) String() (string, error) {
	if err := f.zigoFill(); err != nil {
		return "", err
	}
	return string(f.buf), nil
}

// WriteTo formats straight into w, satisfying io.WriteTo. Nothing is buffered
// on the way, so this is the cheapest form when the destination is a file or a
// network connection rather than memory.
func (f *Formatter) WriteTo(w io.Writer) (int64, error) {
	counted := zigoCountingWriter{inner: w}
	err := f.zigoInto(&counted)
	return counted.written, err
}

// zigoAppendWriter collects writes into a growable slice.
type zigoAppendWriter struct{ buf []byte }

func (w *zigoAppendWriter) Write(p []byte) (int, error) {
	w.buf = append(w.buf, p...)
	return len(p), nil
}

// zigoCountingWriter forwards writes and counts the bytes, for io.WriterTo.
type zigoCountingWriter struct {
	inner   io.Writer
	written int64
}

func (w *zigoCountingWriter) Write(p []byte) (int, error) {
	n, err := w.inner.Write(p)
	w.written += int64(n)
	return n, err
}

var _ io.WriterTo = (*Formatter)(nil)

// Screen represents a native Zig handle.
type Screen struct {
	ptr    unsafe.Pointer
	mu     sync.Mutex
	active int
	closed bool
	poison *NativePanicError
	owner  zigoHandle
}

func zigoNewBorrowedScreen(ptr unsafe.Pointer, owner zigoHandle) *Screen {
	return &Screen{ptr: ptr, owner: owner}
}

// zigoAcquire pins s and its parent open for one native call.
func (s *Screen) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	parent := s.owner
	s.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	s.mu.Lock()
	var err error
	switch {
	case s.closed || s.ptr == nil:
		err = &HandleError{Operation: operation}
	case s.poison != nil:
		err = s.poison.Poisoned(operation)
	default:
		s.active++
	}
	ptr := s.ptr
	s.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (s *Screen) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	parent := s.owner
	s.mu.Unlock()
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Screen) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	parent := s.owner
	if s.poison == nil {
		s.poison = cause
	}
	s.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

// Close detaches this borrowed Screen view without releasing native resources.
func (s *Screen) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	if s.active != 0 {
		active := s.active
		s.mu.Unlock()
		return &HandleInUseError{Operation: "Screen.Close", Children: active}
	}
	s.closed = true
	s.ptr = nil
	s.owner = nil
	s.mu.Unlock()
	return nil
}

var _ io.Closer = (*Screen)(nil)

// Search is a caller-owned native handle. Call Close when it is no longer needed.
type Search struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	parent  zigoChildHandle
	cleanup runtime.Cleanup
}

// zigoAcquire pins s and its parent open for one native call.
func (s *Search) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	parent := s.parent
	s.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	s.mu.Lock()
	var err error
	switch {
	case s.closed || s.ptr == nil:
		err = &HandleError{Operation: operation}
	case s.poison != nil:
		err = s.poison.Poisoned(operation)
	default:
		s.active++
	}
	ptr := s.ptr
	s.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (s *Search) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	parent := s.parent
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSearch(state)
	}
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Search) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	parent := s.parent
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
	s.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

type zigoSearchCleanupState struct {
	ptr    unsafe.Pointer
	parent zigoChildHandle
}

func zigoNewSearch(ptr unsafe.Pointer, parent zigoChildHandle) *Search {
	value := &Search{ptr: ptr, parent: parent}
	state := zigoSearchCleanupState{ptr: ptr, parent: parent}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSearch, state)
	return value
}

func zigoCleanupSearch(state zigoSearchCleanupState) {
	if state.ptr != nil {
		raw.SearchSearchClose(state.ptr)
	}
	if state.parent != nil {
		lifecycle.DropChild(state.parent)
	}
}

// Close releases the native Search resources. It is safe to call more than once.
// The error result is always nil; it exists so Search satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Search) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSearch(state)
	}
	runtime.KeepAlive(s)
	return nil
}

var _ io.Closer = (*Search)(nil)

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Search) zigoTakeLocked() (zigoSearchCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSearchCleanupState{}, false
	}
	state := zigoSearchCleanupState{ptr: s.ptr, parent: s.parent}
	s.ptr = nil
	s.parent = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// GridRef is a caller-owned native handle. Call Close when it is no longer needed.
type GridRef struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	parent  zigoChildHandle
	cleanup runtime.Cleanup
}

// zigoAcquire pins g and its parent open for one native call.
func (g *GridRef) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if g == nil {
		return nil, &HandleError{Operation: operation}
	}
	g.mu.Lock()
	parent := g.parent
	g.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	g.mu.Lock()
	var err error
	switch {
	case g.closed || g.ptr == nil:
		err = &HandleError{Operation: operation}
	case g.poison != nil:
		err = g.poison.Poisoned(operation)
	default:
		g.active++
	}
	ptr := g.ptr
	g.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (g *GridRef) zigoRelease() {
	if g == nil {
		return
	}
	g.mu.Lock()
	g.active--
	parent := g.parent
	state, release := g.zigoTakeLocked()
	g.mu.Unlock()
	if release {
		zigoCleanupGridRef(state)
	}
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks g unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (g *GridRef) zigoPoison(cause *NativePanicError) {
	if g == nil {
		return
	}
	g.mu.Lock()
	parent := g.parent
	if g.poison == nil {
		g.poison = cause
		g.cleanup.Stop()
	}
	g.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

type zigoGridRefCleanupState struct {
	ptr    unsafe.Pointer
	parent zigoChildHandle
}

func zigoNewGridRef(ptr unsafe.Pointer, parent zigoChildHandle) *GridRef {
	value := &GridRef{ptr: ptr, parent: parent}
	state := zigoGridRefCleanupState{ptr: ptr, parent: parent}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupGridRef, state)
	return value
}

func zigoCleanupGridRef(state zigoGridRefCleanupState) {
	if state.ptr != nil {
		raw.GridRefGridRefClose(state.ptr)
	}
	if state.parent != nil {
		lifecycle.DropChild(state.parent)
	}
}

// Close releases the native GridRef resources. It is safe to call more than once.
// The error result is always nil; it exists so GridRef satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (g *GridRef) Close() error {
	if g == nil {
		return nil
	}
	g.mu.Lock()
	if g.closed {
		g.mu.Unlock()
		return nil
	}
	g.closed = true
	g.cleanup.Stop()
	state, release := g.zigoTakeLocked()
	g.mu.Unlock()
	if release {
		zigoCleanupGridRef(state)
	}
	runtime.KeepAlive(g)
	return nil
}

var _ io.Closer = (*GridRef)(nil)

// zigoTakeLocked hands out what is left to release once g is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (g *GridRef) zigoTakeLocked() (zigoGridRefCleanupState, bool) {
	if !g.closed || g.active != 0 || g.ptr == nil {
		return zigoGridRefCleanupState{}, false
	}
	state := zigoGridRefCleanupState{ptr: g.ptr, parent: g.parent}
	g.ptr = nil
	g.parent = nil
	if g.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Gesture is a caller-owned native handle. Call Close when it is no longer needed.
type Gesture struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	parent  zigoChildHandle
	cleanup runtime.Cleanup
}

// zigoAcquire pins g and its parent open for one native call.
func (g *Gesture) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if g == nil {
		return nil, &HandleError{Operation: operation}
	}
	g.mu.Lock()
	parent := g.parent
	g.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	g.mu.Lock()
	var err error
	switch {
	case g.closed || g.ptr == nil:
		err = &HandleError{Operation: operation}
	case g.poison != nil:
		err = g.poison.Poisoned(operation)
	default:
		g.active++
	}
	ptr := g.ptr
	g.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (g *Gesture) zigoRelease() {
	if g == nil {
		return
	}
	g.mu.Lock()
	g.active--
	parent := g.parent
	state, release := g.zigoTakeLocked()
	g.mu.Unlock()
	if release {
		zigoCleanupGesture(state)
	}
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks g unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (g *Gesture) zigoPoison(cause *NativePanicError) {
	if g == nil {
		return
	}
	g.mu.Lock()
	parent := g.parent
	if g.poison == nil {
		g.poison = cause
		g.cleanup.Stop()
	}
	g.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

type zigoGestureCleanupState struct {
	ptr    unsafe.Pointer
	parent zigoChildHandle
}

func zigoNewGesture(ptr unsafe.Pointer, parent zigoChildHandle) *Gesture {
	value := &Gesture{ptr: ptr, parent: parent}
	state := zigoGestureCleanupState{ptr: ptr, parent: parent}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupGesture, state)
	return value
}

func zigoCleanupGesture(state zigoGestureCleanupState) {
	if state.ptr != nil {
		raw.GestureGestureClose(state.ptr)
	}
	if state.parent != nil {
		lifecycle.DropChild(state.parent)
	}
}

// Close releases the native Gesture resources. It is safe to call more than once.
// The error result is always nil; it exists so Gesture satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (g *Gesture) Close() error {
	if g == nil {
		return nil
	}
	g.mu.Lock()
	if g.closed {
		g.mu.Unlock()
		return nil
	}
	g.closed = true
	g.cleanup.Stop()
	state, release := g.zigoTakeLocked()
	g.mu.Unlock()
	if release {
		zigoCleanupGesture(state)
	}
	runtime.KeepAlive(g)
	return nil
}

var _ io.Closer = (*Gesture)(nil)

// zigoTakeLocked hands out what is left to release once g is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (g *Gesture) zigoTakeLocked() (zigoGestureCleanupState, bool) {
	if !g.closed || g.active != 0 || g.ptr == nil {
		return zigoGestureCleanupState{}, false
	}
	state := zigoGestureCleanupState{ptr: g.ptr, parent: g.parent}
	g.ptr = nil
	g.parent = nil
	if g.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Stream parses VT bytes into its parent terminal. Serialize complete calls,
// including event iteration, with all other calls touching the parent or its
// children. Callbacks run synchronously; only request-response operations may
// reenter the active terminal's bindings. Close the stream before its parent
// terminal.
type Stream struct {
	ptr             unsafe.Pointer
	mu              sync.Mutex
	active          int
	closed          bool
	poison          *NativePanicError
	parent          zigoChildHandle
	callbackHandles []zigoCallbackHandle
	cleanup         runtime.Cleanup
}

func (s *Stream) zigoCallbackHandle(slot int) zigoCallbackHandle {
	s.mu.Lock()
	handle := s.callbackHandles[slot]
	s.mu.Unlock()
	return handle
}

// zigoReplaceCallbackHandle swaps one generation-time callback slot under the handle lock.
func (s *Stream) zigoReplaceCallbackHandle(slot int, handle zigoCallbackHandle) zigoCallbackHandle {
	s.mu.Lock()
	previous := s.callbackHandles[slot]
	s.callbackHandles[slot] = handle
	s.mu.Unlock()
	return previous
}

// zigoAcquire pins s and its parent open for one native call.
func (s *Stream) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	parent := s.parent
	s.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	s.mu.Lock()
	var err error
	switch {
	case s.closed || s.ptr == nil:
		err = &HandleError{Operation: operation}
	case s.poison != nil:
		err = s.poison.Poisoned(operation)
	default:
		s.active++
	}
	ptr := s.ptr
	s.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (s *Stream) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	parent := s.parent
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupStream(state)
	}
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Stream) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	parent := s.parent
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
	s.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

type zigoStreamCleanupState struct {
	ptr             unsafe.Pointer
	parent          zigoChildHandle
	callbackHandles []zigoCallbackHandle
}

func zigoNewStream(ptr unsafe.Pointer, parent zigoChildHandle, callbackHandles []zigoCallbackHandle) *Stream {
	value := &Stream{ptr: ptr, parent: parent, callbackHandles: callbackHandles}
	state := zigoStreamCleanupState{ptr: ptr, parent: parent, callbackHandles: callbackHandles}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupStream, state)
	return value
}

func zigoCleanupStream(state zigoStreamCleanupState) {
	if state.ptr != nil {
		raw.StreamFreeStream(state.ptr)
	}
	for _, handle := range state.callbackHandles {
		zigoDeleteCallbackHandle(handle)
	}
	if state.parent != nil {
		lifecycle.DropChild(state.parent)
	}
}

// Close releases the native Stream resources. It is safe to call more than once.
// The error result is always nil; it exists so Stream satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Stream) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupStream(state)
	}
	runtime.KeepAlive(s)
	return nil
}

var _ io.Closer = (*Stream)(nil)

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Stream) zigoTakeLocked() (zigoStreamCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoStreamCleanupState{}, false
	}
	state := zigoStreamCleanupState{ptr: s.ptr, callbackHandles: s.callbackHandles, parent: s.parent}
	s.ptr = nil
	s.callbackHandles = nil
	s.parent = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}

var _ io.Writer = (*Stream)(nil)
var _ io.StringWriter = (*Stream)(nil)

// Stream satisfies io.WriteCloser; this assertion stops compiling the day it does not.
var _ io.WriteCloser = (*Stream)(nil)

// ClipboardRequest represents a native Zig handle.
type ClipboardRequest struct {
	ptr    unsafe.Pointer
	mu     sync.Mutex
	active int
	closed bool
	poison *NativePanicError
	owner  zigoHandle
}

func zigoNewBorrowedClipboardRequest(ptr unsafe.Pointer, owner zigoHandle) *ClipboardRequest {
	return &ClipboardRequest{ptr: ptr, owner: owner}
}

// zigoAcquire pins c and its parent open for one native call.
func (c *ClipboardRequest) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if c == nil {
		return nil, &HandleError{Operation: operation}
	}
	c.mu.Lock()
	parent := c.owner
	c.mu.Unlock()
	if parent != nil {
		if _, err := lifecycle.Acquire(operation, parent); err != nil {
			return nil, err
		}
	}
	c.mu.Lock()
	var err error
	switch {
	case c.closed || c.ptr == nil:
		err = &HandleError{Operation: operation}
	case c.poison != nil:
		err = c.poison.Poisoned(operation)
	default:
		c.active++
	}
	ptr := c.ptr
	c.mu.Unlock()
	if err != nil {
		if parent != nil {
			lifecycle.Release(parent)
		}
		return nil, err
	}
	return ptr, nil
}

func (c *ClipboardRequest) zigoRelease() {
	if c == nil {
		return
	}
	c.mu.Lock()
	c.active--
	parent := c.owner
	c.mu.Unlock()
	if parent != nil {
		lifecycle.Release(parent)
	}
}

// zigoPoison marks c unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (c *ClipboardRequest) zigoPoison(cause *NativePanicError) {
	if c == nil {
		return
	}
	c.mu.Lock()
	parent := c.owner
	if c.poison == nil {
		c.poison = cause
	}
	c.mu.Unlock()
	if parent != nil {
		lifecycle.Poison(parent, cause)
	}
}

// Close detaches this borrowed ClipboardRequest view without releasing native resources.
func (c *ClipboardRequest) Close() error {
	if c == nil {
		return nil
	}
	c.mu.Lock()
	if c.closed {
		c.mu.Unlock()
		return nil
	}
	if c.active != 0 {
		active := c.active
		c.mu.Unlock()
		return &HandleInUseError{Operation: "ClipboardRequest.Close", Children: active}
	}
	c.closed = true
	c.ptr = nil
	c.owner = nil
	c.mu.Unlock()
	return nil
}

var _ io.Closer = (*ClipboardRequest)(nil)

// ClipboardContent is one MIME representation of a single logical clipboard value.
// Data is binary-safe and may be empty.
type ClipboardContent struct {
	MIME string
	Data []byte
}

// Reply answers a pending read atomically with the supplied representations.
// It replaces any staged contents. Inputs are copied before the native reply;
// they may be reused after this call. Call only inside the clipboard callback.
// On staging failure nothing is sent, and staged data is discarded. Returning
// from the callback without a successful reply or explicit denial denies it.
func (r *ClipboardRequest) Reply(contents []ClipboardContent, remember bool) error {
	if err := r.ClearReplyContents(); err != nil {
		return err
	}
	for _, content := range contents {
		if err := r.AddContent(content.MIME, content.Data); err != nil {
			_ = r.ClearReplyContents()
			return err
		}
	}
	return r.ReplyContents(remember)
}

// OSCParser is a caller-owned native handle. Call Close when it is no longer needed.
type OSCParser struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins o open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (o *OSCParser) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if o == nil {
		return nil, &HandleError{Operation: operation}
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.closed || o.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if o.poison != nil {
		return nil, o.poison.Poisoned(operation)
	}
	o.active++
	return o.ptr, nil
}

func (o *OSCParser) zigoRelease() {
	if o == nil {
		return
	}
	o.mu.Lock()
	o.active--
	state, release := o.zigoTakeLocked()
	o.mu.Unlock()
	if release {
		zigoCleanupOSCParser(state)
	}
}

// zigoPoison marks o unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (o *OSCParser) zigoPoison(cause *NativePanicError) {
	if o == nil {
		return
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.poison == nil {
		o.poison = cause
		o.cleanup.Stop()
	}
}

type zigoOSCParserCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewOSCParser(ptr unsafe.Pointer) *OSCParser {
	value := &OSCParser{ptr: ptr}
	state := zigoOSCParserCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupOSCParser, state)
	return value
}

func zigoCleanupOSCParser(state zigoOSCParserCleanupState) {
	if state.ptr != nil {
		raw.OscParserFreeOscParser(state.ptr)
	}
}

// Close releases the native OSCParser resources. It is safe to call more than once.
// The error result is always nil; it exists so OSCParser satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (o *OSCParser) Close() error {
	if o == nil {
		return nil
	}
	o.mu.Lock()
	if o.closed {
		o.mu.Unlock()
		return nil
	}
	o.closed = true
	o.cleanup.Stop()
	state, release := o.zigoTakeLocked()
	o.mu.Unlock()
	if release {
		zigoCleanupOSCParser(state)
	}
	runtime.KeepAlive(o)
	return nil
}

var _ io.Closer = (*OSCParser)(nil)

// zigoTakeLocked hands out what is left to release once o is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (o *OSCParser) zigoTakeLocked() (zigoOSCParserCleanupState, bool) {
	if !o.closed || o.active != 0 || o.ptr == nil {
		return zigoOSCParserCleanupState{}, false
	}
	state := zigoOSCParserCleanupState{ptr: o.ptr}
	o.ptr = nil
	if o.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Snapshot is a caller-owned native handle. Call Close when it is no longer needed.
type Snapshot struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins s open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (s *Snapshot) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed || s.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if s.poison != nil {
		return nil, s.poison.Poisoned(operation)
	}
	s.active++
	return s.ptr, nil
}

func (s *Snapshot) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshot(state)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Snapshot) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
}

type zigoSnapshotCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewSnapshot(ptr unsafe.Pointer) *Snapshot {
	value := &Snapshot{ptr: ptr}
	state := zigoSnapshotCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSnapshot, state)
	return value
}

func zigoCleanupSnapshot(state zigoSnapshotCleanupState) {
	if state.ptr != nil {
		raw.SnapshotDeinit(state.ptr)
	}
}

// Close releases the native Snapshot resources. It is safe to call more than once.
// The error result is always nil; it exists so Snapshot satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Snapshot) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshot(state)
	}
	runtime.KeepAlive(s)
	return nil
}

var _ io.Closer = (*Snapshot)(nil)

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Snapshot) zigoTakeLocked() (zigoSnapshotCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSnapshotCleanupState{}, false
	}
	state := zigoSnapshotCleanupState{ptr: s.ptr}
	s.ptr = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// SnapshotDecoder is a caller-owned native handle. Call Close when it is no longer needed.
type SnapshotDecoder struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins s open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (s *SnapshotDecoder) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed || s.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if s.poison != nil {
		return nil, s.poison.Poisoned(operation)
	}
	s.active++
	return s.ptr, nil
}

func (s *SnapshotDecoder) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshotDecoder(state)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *SnapshotDecoder) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
}

type zigoSnapshotDecoderCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewSnapshotDecoder(ptr unsafe.Pointer) *SnapshotDecoder {
	value := &SnapshotDecoder{ptr: ptr}
	state := zigoSnapshotDecoderCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSnapshotDecoder, state)
	return value
}

func zigoCleanupSnapshotDecoder(state zigoSnapshotDecoderCleanupState) {
	if state.ptr != nil {
		raw.SnapshotDecoderFreeSnapshotDecoder(state.ptr)
	}
}

// Close releases the native SnapshotDecoder resources. It is safe to call more than once.
// The error result is always nil; it exists so SnapshotDecoder satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *SnapshotDecoder) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshotDecoder(state)
	}
	runtime.KeepAlive(s)
	return nil
}

var _ io.Closer = (*SnapshotDecoder)(nil)

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *SnapshotDecoder) zigoTakeLocked() (zigoSnapshotDecoderCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSnapshotDecoderCleanupState{}, false
	}
	state := zigoSnapshotDecoderCleanupState{ptr: s.ptr}
	s.ptr = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// RenderState owns a render snapshot. Update requires exclusive access to both
// the terminal and this state. After Update, reads do not touch the terminal,
// but must be serialized with Update, Clean and Close on this state. Copied
// cell, cursor and color values can be retained across updates. Call Clean
// only after successfully drawing the frame.
type RenderState struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins r open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (r *RenderState) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if r == nil {
		return nil, &HandleError{Operation: operation}
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed || r.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if r.poison != nil {
		return nil, r.poison.Poisoned(operation)
	}
	r.active++
	return r.ptr, nil
}

func (r *RenderState) zigoRelease() {
	if r == nil {
		return
	}
	r.mu.Lock()
	r.active--
	state, release := r.zigoTakeLocked()
	r.mu.Unlock()
	if release {
		zigoCleanupRenderState(state)
	}
}

// zigoPoison marks r unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (r *RenderState) zigoPoison(cause *NativePanicError) {
	if r == nil {
		return
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.poison == nil {
		r.poison = cause
		r.cleanup.Stop()
	}
}

type zigoRenderStateCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewRenderState(ptr unsafe.Pointer) *RenderState {
	value := &RenderState{ptr: ptr}
	state := zigoRenderStateCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupRenderState, state)
	return value
}

func zigoCleanupRenderState(state zigoRenderStateCleanupState) {
	if state.ptr != nil {
		raw.RenderStateDeinit(state.ptr)
	}
}

// Close releases the native RenderState resources. It is safe to call more than once.
// The error result is always nil; it exists so RenderState satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (r *RenderState) Close() error {
	if r == nil {
		return nil
	}
	r.mu.Lock()
	if r.closed {
		r.mu.Unlock()
		return nil
	}
	r.closed = true
	r.cleanup.Stop()
	state, release := r.zigoTakeLocked()
	r.mu.Unlock()
	if release {
		zigoCleanupRenderState(state)
	}
	runtime.KeepAlive(r)
	return nil
}

var _ io.Closer = (*RenderState)(nil)

// zigoTakeLocked hands out what is left to release once r is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (r *RenderState) zigoTakeLocked() (zigoRenderStateCleanupState, bool) {
	if !r.closed || r.active != 0 || r.ptr == nil {
		return zigoRenderStateCleanupState{}, false
	}
	state := zigoRenderStateCleanupState{ptr: r.ptr}
	r.ptr = nil
	if r.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// KittyImages is a caller-owned native handle. Call Close when it is no longer needed.
type KittyImages struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins k open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (k *KittyImages) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if k == nil {
		return nil, &HandleError{Operation: operation}
	}
	k.mu.Lock()
	defer k.mu.Unlock()
	if k.closed || k.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if k.poison != nil {
		return nil, k.poison.Poisoned(operation)
	}
	k.active++
	return k.ptr, nil
}

func (k *KittyImages) zigoRelease() {
	if k == nil {
		return
	}
	k.mu.Lock()
	k.active--
	state, release := k.zigoTakeLocked()
	k.mu.Unlock()
	if release {
		zigoCleanupKittyImages(state)
	}
}

// zigoPoison marks k unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (k *KittyImages) zigoPoison(cause *NativePanicError) {
	if k == nil {
		return
	}
	k.mu.Lock()
	defer k.mu.Unlock()
	if k.poison == nil {
		k.poison = cause
		k.cleanup.Stop()
	}
}

type zigoKittyImagesCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewKittyImages(ptr unsafe.Pointer) *KittyImages {
	value := &KittyImages{ptr: ptr}
	state := zigoKittyImagesCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupKittyImages, state)
	return value
}

func zigoCleanupKittyImages(state zigoKittyImagesCleanupState) {
	if state.ptr != nil {
		raw.KittyImagesFreeKittyImages(state.ptr)
	}
}

// Close releases the native KittyImages resources. It is safe to call more than once.
// The error result is always nil; it exists so KittyImages satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (k *KittyImages) Close() error {
	if k == nil {
		return nil
	}
	k.mu.Lock()
	if k.closed {
		k.mu.Unlock()
		return nil
	}
	k.closed = true
	k.cleanup.Stop()
	state, release := k.zigoTakeLocked()
	k.mu.Unlock()
	if release {
		zigoCleanupKittyImages(state)
	}
	runtime.KeepAlive(k)
	return nil
}

var _ io.Closer = (*KittyImages)(nil)

// zigoTakeLocked hands out what is left to release once k is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (k *KittyImages) zigoTakeLocked() (zigoKittyImagesCleanupState, bool) {
	if !k.closed || k.active != 0 || k.ptr == nil {
		return zigoKittyImagesCleanupState{}, false
	}
	state := zigoKittyImagesCleanupState{ptr: k.ptr}
	k.ptr = nil
	if k.poison != nil {
		state.ptr = nil
	}
	return state, true
}
