// Code generated by zigo. DO NOT EDIT.

package gostty

import (
	"strconv"
	"strings"
)

// EnumParseError reports text that names no value of a generated enum.
type EnumParseError struct {
	// Type is the Go enum type name.
	Type string
	// Text is the rejected input.
	Text string
}

// Error implements error.
func (err *EnumParseError) Error() string {
	return "zigo: " + err.Type + ": unknown value " + strconv.Quote(err.Text)
}

// ColorName represents the corresponding Zig open enum; values outside the named constants are valid.
type ColorName uint8

const (
	// ColorNameBlack corresponds to the Zig tag black.
	ColorNameBlack ColorName = 0
	// ColorNameRed corresponds to the Zig tag red.
	ColorNameRed ColorName = 1
	// ColorNameGreen corresponds to the Zig tag green.
	ColorNameGreen ColorName = 2
	// ColorNameYellow corresponds to the Zig tag yellow.
	ColorNameYellow ColorName = 3
	// ColorNameBlue corresponds to the Zig tag blue.
	ColorNameBlue ColorName = 4
	// ColorNameMagenta corresponds to the Zig tag magenta.
	ColorNameMagenta ColorName = 5
	// ColorNameCyan corresponds to the Zig tag cyan.
	ColorNameCyan ColorName = 6
	// ColorNameWhite corresponds to the Zig tag white.
	ColorNameWhite ColorName = 7
	// ColorNameBrightBlack corresponds to the Zig tag bright_black.
	ColorNameBrightBlack ColorName = 8
	// ColorNameBrightRed corresponds to the Zig tag bright_red.
	ColorNameBrightRed ColorName = 9
	// ColorNameBrightGreen corresponds to the Zig tag bright_green.
	ColorNameBrightGreen ColorName = 10
	// ColorNameBrightYellow corresponds to the Zig tag bright_yellow.
	ColorNameBrightYellow ColorName = 11
	// ColorNameBrightBlue corresponds to the Zig tag bright_blue.
	ColorNameBrightBlue ColorName = 12
	// ColorNameBrightMagenta corresponds to the Zig tag bright_magenta.
	ColorNameBrightMagenta ColorName = 13
	// ColorNameBrightCyan corresponds to the Zig tag bright_cyan.
	ColorNameBrightCyan ColorName = 14
	// ColorNameBrightWhite corresponds to the Zig tag bright_white.
	ColorNameBrightWhite ColorName = 15
)

var zigoColorNameNames = [16]string{
	0:  "black",
	1:  "red",
	2:  "green",
	3:  "yellow",
	4:  "blue",
	5:  "magenta",
	6:  "cyan",
	7:  "white",
	8:  "bright_black",
	9:  "bright_red",
	10: "bright_green",
	11: "bright_yellow",
	12: "bright_blue",
	13: "bright_magenta",
	14: "bright_cyan",
	15: "bright_white",
}

// String returns the Zig tag name.
func (value ColorName) String() string {
	if value >= 0 && value <= 15 {
		return zigoColorNameNames[uint64(value)]
	}
	return "ColorName(" + strconv.Itoa(int(value)) + ")"
}

// ParseColorName returns the ColorName named by text, which is a Zig tag name.
// Values outside the named constants are accepted in the ColorName(N) spelling String returns.
func ParseColorName(text string) (ColorName, error) {
	switch text {
	case "black":
		return ColorNameBlack, nil
	case "red":
		return ColorNameRed, nil
	case "green":
		return ColorNameGreen, nil
	case "yellow":
		return ColorNameYellow, nil
	case "blue":
		return ColorNameBlue, nil
	case "magenta":
		return ColorNameMagenta, nil
	case "cyan":
		return ColorNameCyan, nil
	case "white":
		return ColorNameWhite, nil
	case "bright_black":
		return ColorNameBrightBlack, nil
	case "bright_red":
		return ColorNameBrightRed, nil
	case "bright_green":
		return ColorNameBrightGreen, nil
	case "bright_yellow":
		return ColorNameBrightYellow, nil
	case "bright_blue":
		return ColorNameBrightBlue, nil
	case "bright_magenta":
		return ColorNameBrightMagenta, nil
	case "bright_cyan":
		return ColorNameBrightCyan, nil
	case "bright_white":
		return ColorNameBrightWhite, nil
	}
	if strings.HasPrefix(text, "ColorName(") && strings.HasSuffix(text, ")") {
		if number, err := strconv.ParseUint(text[len("ColorName("):len(text)-1], 10, 8); err == nil {
			return ColorName(number), nil
		}
	}
	return 0, &EnumParseError{Type: "ColorName", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value ColorName) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseColorName.
func (value *ColorName) UnmarshalText(text []byte) error {
	parsed, err := ParseColorName(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ColorNameValues returns a fresh slice of known values in declaration order.
func ColorNameValues() []ColorName {
	return []ColorName{
		ColorNameBlack,
		ColorNameRed,
		ColorNameGreen,
		ColorNameYellow,
		ColorNameBlue,
		ColorNameMagenta,
		ColorNameCyan,
		ColorNameWhite,
		ColorNameBrightBlack,
		ColorNameBrightRed,
		ColorNameBrightGreen,
		ColorNameBrightYellow,
		ColorNameBrightBlue,
		ColorNameBrightMagenta,
		ColorNameBrightCyan,
		ColorNameBrightWhite,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value ColorName) IsKnown() bool {
	return value >= 0 && value <= 15
}

// PointTag represents the corresponding Zig enum.
type PointTag uint8

const (
	// PointTagActive corresponds to the Zig tag active.
	PointTagActive PointTag = 0
	// PointTagViewport corresponds to the Zig tag viewport.
	PointTagViewport PointTag = 1
	// PointTagScreen corresponds to the Zig tag screen.
	PointTagScreen PointTag = 2
	// PointTagHistory corresponds to the Zig tag history.
	PointTagHistory PointTag = 3
)

var zigoPointTagNames = [4]string{
	0: "active",
	1: "viewport",
	2: "screen",
	3: "history",
}

// String returns the Zig tag name.
func (value PointTag) String() string {
	if value >= 0 && value <= 3 {
		return zigoPointTagNames[uint64(value)]
	}
	return "PointTag(" + strconv.Itoa(int(value)) + ")"
}

// ParsePointTag returns the PointTag named by text, which is a Zig tag name.
func ParsePointTag(text string) (PointTag, error) {
	switch text {
	case "active":
		return PointTagActive, nil
	case "viewport":
		return PointTagViewport, nil
	case "screen":
		return PointTagScreen, nil
	case "history":
		return PointTagHistory, nil
	}
	return 0, &EnumParseError{Type: "PointTag", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value PointTag) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParsePointTag.
func (value *PointTag) UnmarshalText(text []byte) error {
	parsed, err := ParsePointTag(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// CursorStyle represents the corresponding Zig enum.
type CursorStyle uint8

const (
	// CursorStyleBar corresponds to the Zig tag bar.
	CursorStyleBar CursorStyle = 0
	// CursorStyleBlock corresponds to the Zig tag block.
	CursorStyleBlock CursorStyle = 1
	// CursorStyleUnderline corresponds to the Zig tag underline.
	CursorStyleUnderline CursorStyle = 2
	// CursorStyleBlockHollow corresponds to the Zig tag block_hollow.
	CursorStyleBlockHollow CursorStyle = 3
)

var zigoCursorStyleNames = [4]string{
	0: "bar",
	1: "block",
	2: "underline",
	3: "block_hollow",
}

// String returns the Zig tag name.
func (value CursorStyle) String() string {
	if value >= 0 && value <= 3 {
		return zigoCursorStyleNames[uint64(value)]
	}
	return "CursorStyle(" + strconv.Itoa(int(value)) + ")"
}

// ParseCursorStyle returns the CursorStyle named by text, which is a Zig tag name.
func ParseCursorStyle(text string) (CursorStyle, error) {
	switch text {
	case "bar":
		return CursorStyleBar, nil
	case "block":
		return CursorStyleBlock, nil
	case "underline":
		return CursorStyleUnderline, nil
	case "block_hollow":
		return CursorStyleBlockHollow, nil
	}
	return 0, &EnumParseError{Type: "CursorStyle", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value CursorStyle) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseCursorStyle.
func (value *CursorStyle) UnmarshalText(text []byte) error {
	parsed, err := ParseCursorStyle(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// CursorStyleReq represents the corresponding Zig enum.
type CursorStyleReq uint8

const (
	// CursorStyleReqDefault corresponds to the Zig tag default.
	CursorStyleReqDefault CursorStyleReq = 0
	// CursorStyleReqBlinkingBlock corresponds to the Zig tag blinking_block.
	CursorStyleReqBlinkingBlock CursorStyleReq = 1
	// CursorStyleReqSteadyBlock corresponds to the Zig tag steady_block.
	CursorStyleReqSteadyBlock CursorStyleReq = 2
	// CursorStyleReqBlinkingUnderline corresponds to the Zig tag blinking_underline.
	CursorStyleReqBlinkingUnderline CursorStyleReq = 3
	// CursorStyleReqSteadyUnderline corresponds to the Zig tag steady_underline.
	CursorStyleReqSteadyUnderline CursorStyleReq = 4
	// CursorStyleReqBlinkingBar corresponds to the Zig tag blinking_bar.
	CursorStyleReqBlinkingBar CursorStyleReq = 5
	// CursorStyleReqSteadyBar corresponds to the Zig tag steady_bar.
	CursorStyleReqSteadyBar CursorStyleReq = 6
)

var zigoCursorStyleReqNames = [7]string{
	0: "default",
	1: "blinking_block",
	2: "steady_block",
	3: "blinking_underline",
	4: "steady_underline",
	5: "blinking_bar",
	6: "steady_bar",
}

// String returns the Zig tag name.
func (value CursorStyleReq) String() string {
	if value >= 0 && value <= 6 {
		return zigoCursorStyleReqNames[uint64(value)]
	}
	return "CursorStyleReq(" + strconv.Itoa(int(value)) + ")"
}

// EraseDisplay represents the corresponding Zig enum.
type EraseDisplay uint8

const (
	// EraseDisplayBelow corresponds to the Zig tag below.
	EraseDisplayBelow EraseDisplay = 0
	// EraseDisplayAbove corresponds to the Zig tag above.
	EraseDisplayAbove EraseDisplay = 1
	// EraseDisplayComplete corresponds to the Zig tag complete.
	EraseDisplayComplete EraseDisplay = 2
	// EraseDisplayScrollback corresponds to the Zig tag scrollback.
	EraseDisplayScrollback EraseDisplay = 3
	// EraseDisplayScrollComplete corresponds to the Zig tag scroll_complete.
	EraseDisplayScrollComplete EraseDisplay = 22
)

// String returns the Zig tag name.
func (value EraseDisplay) String() string {
	switch value {
	case EraseDisplayBelow:
		return "below"
	case EraseDisplayAbove:
		return "above"
	case EraseDisplayComplete:
		return "complete"
	case EraseDisplayScrollback:
		return "scrollback"
	case EraseDisplayScrollComplete:
		return "scroll_complete"
	}
	return "EraseDisplay(" + strconv.Itoa(int(value)) + ")"
}

// EraseLine represents the corresponding Zig open enum; values outside the named constants are valid.
type EraseLine uint8

const (
	// EraseLineRight corresponds to the Zig tag right.
	EraseLineRight EraseLine = 0
	// EraseLineLeft corresponds to the Zig tag left.
	EraseLineLeft EraseLine = 1
	// EraseLineComplete corresponds to the Zig tag complete.
	EraseLineComplete EraseLine = 2
	// EraseLineRightUnlessPendingWrap corresponds to the Zig tag right_unless_pending_wrap.
	EraseLineRightUnlessPendingWrap EraseLine = 4
)

var zigoEraseLineNames = [5]string{
	0: "right",
	1: "left",
	2: "complete",
	4: "right_unless_pending_wrap",
}

// String returns the Zig tag name.
func (value EraseLine) String() string {
	if value >= 0 && value <= 4 {
		if name := zigoEraseLineNames[uint64(value)]; name != "" {
			return name
		}
	}
	return "EraseLine(" + strconv.Itoa(int(value)) + ")"
}

// ParseEraseLine returns the EraseLine named by text, which is a Zig tag name.
// Values outside the named constants are accepted in the EraseLine(N) spelling String returns.
func ParseEraseLine(text string) (EraseLine, error) {
	switch text {
	case "right":
		return EraseLineRight, nil
	case "left":
		return EraseLineLeft, nil
	case "complete":
		return EraseLineComplete, nil
	case "right_unless_pending_wrap":
		return EraseLineRightUnlessPendingWrap, nil
	}
	if strings.HasPrefix(text, "EraseLine(") && strings.HasSuffix(text, ")") {
		if number, err := strconv.ParseUint(text[len("EraseLine("):len(text)-1], 10, 8); err == nil {
			return EraseLine(number), nil
		}
	}
	return 0, &EnumParseError{Type: "EraseLine", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value EraseLine) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseEraseLine.
func (value *EraseLine) UnmarshalText(text []byte) error {
	parsed, err := ParseEraseLine(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// EraseLineValues returns a fresh slice of known values in declaration order.
func EraseLineValues() []EraseLine {
	return []EraseLine{
		EraseLineRight,
		EraseLineLeft,
		EraseLineComplete,
		EraseLineRightUnlessPendingWrap,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value EraseLine) IsKnown() bool {
	switch value {
	case EraseLineRight:
		return true
	case EraseLineLeft:
		return true
	case EraseLineComplete:
		return true
	case EraseLineRightUnlessPendingWrap:
		return true
	}
	return false
}

// TabClear represents the corresponding Zig open enum; values outside the named constants are valid.
type TabClear uint8

const (
	// TabClearCurrent corresponds to the Zig tag current.
	TabClearCurrent TabClear = 0
	// TabClearAll corresponds to the Zig tag all.
	TabClearAll TabClear = 3
)

var zigoTabClearNames = [4]string{
	0: "current",
	3: "all",
}

// String returns the Zig tag name.
func (value TabClear) String() string {
	if value >= 0 && value <= 3 {
		if name := zigoTabClearNames[uint64(value)]; name != "" {
			return name
		}
	}
	return "TabClear(" + strconv.Itoa(int(value)) + ")"
}

// ParseTabClear returns the TabClear named by text, which is a Zig tag name.
// Values outside the named constants are accepted in the TabClear(N) spelling String returns.
func ParseTabClear(text string) (TabClear, error) {
	switch text {
	case "current":
		return TabClearCurrent, nil
	case "all":
		return TabClearAll, nil
	}
	if strings.HasPrefix(text, "TabClear(") && strings.HasSuffix(text, ")") {
		if number, err := strconv.ParseUint(text[len("TabClear("):len(text)-1], 10, 8); err == nil {
			return TabClear(number), nil
		}
	}
	return 0, &EnumParseError{Type: "TabClear", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value TabClear) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseTabClear.
func (value *TabClear) UnmarshalText(text []byte) error {
	parsed, err := ParseTabClear(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// TabClearValues returns a fresh slice of known values in declaration order.
func TabClearValues() []TabClear {
	return []TabClear{
		TabClearCurrent,
		TabClearAll,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value TabClear) IsKnown() bool {
	switch value {
	case TabClearCurrent:
		return true
	case TabClearAll:
		return true
	}
	return false
}

// ProtectedMode represents the corresponding Zig enum.
type ProtectedMode uint8

const (
	// ProtectedModeOff corresponds to the Zig tag off.
	ProtectedModeOff ProtectedMode = 0
	// ProtectedModeIso corresponds to the Zig tag iso.
	ProtectedModeIso ProtectedMode = 1
	// ProtectedModeDec corresponds to the Zig tag dec.
	ProtectedModeDec ProtectedMode = 2
)

var zigoProtectedModeNames = [3]string{
	0: "off",
	1: "iso",
	2: "dec",
}

// String returns the Zig tag name.
func (value ProtectedMode) String() string {
	if value >= 0 && value <= 2 {
		return zigoProtectedModeNames[uint64(value)]
	}
	return "ProtectedMode(" + strconv.Itoa(int(value)) + ")"
}

// ScreenKey represents the corresponding Zig enum.
type ScreenKey uint8

const (
	// ScreenKeyPrimary corresponds to the Zig tag primary.
	ScreenKeyPrimary ScreenKey = 0
	// ScreenKeyAlternate corresponds to the Zig tag alternate.
	ScreenKeyAlternate ScreenKey = 1
)

var zigoScreenKeyNames = [2]string{
	0: "primary",
	1: "alternate",
}

// String returns the Zig tag name.
func (value ScreenKey) String() string {
	if value >= 0 && value <= 1 {
		return zigoScreenKeyNames[uint64(value)]
	}
	return "ScreenKey(" + strconv.Itoa(int(value)) + ")"
}

// SwitchScreenMode represents the corresponding Zig enum.
type SwitchScreenMode uint8

const (
	// SwitchScreenMode47 corresponds to the Zig tag 47.
	SwitchScreenMode47 SwitchScreenMode = 0
	// SwitchScreenMode1047 corresponds to the Zig tag 1047.
	SwitchScreenMode1047 SwitchScreenMode = 1
	// SwitchScreenMode1049 corresponds to the Zig tag 1049.
	SwitchScreenMode1049 SwitchScreenMode = 2
)

var zigoSwitchScreenModeNames = [3]string{
	0: "47",
	1: "1047",
	2: "1049",
}

// String returns the Zig tag name.
func (value SwitchScreenMode) String() string {
	if value >= 0 && value <= 2 {
		return zigoSwitchScreenModeNames[uint64(value)]
	}
	return "SwitchScreenMode(" + strconv.Itoa(int(value)) + ")"
}

// Mode represents the corresponding Zig enum.
type Mode uint16

const (
	// ModeDisableKeyboard corresponds to the Zig tag disable_keyboard.
	ModeDisableKeyboard Mode = 32770
	// ModeInsert corresponds to the Zig tag insert.
	ModeInsert Mode = 32772
	// ModeSendReceiveMode corresponds to the Zig tag send_receive_mode.
	ModeSendReceiveMode Mode = 32780
	// ModeLinefeed corresponds to the Zig tag linefeed.
	ModeLinefeed Mode = 32788
	// ModeCursorKeys corresponds to the Zig tag cursor_keys.
	ModeCursorKeys Mode = 1
	// Mode132Column corresponds to the Zig tag 132_column.
	Mode132Column Mode = 3
	// ModeSlowScroll corresponds to the Zig tag slow_scroll.
	ModeSlowScroll Mode = 4
	// ModeReverseColors corresponds to the Zig tag reverse_colors.
	ModeReverseColors Mode = 5
	// ModeOrigin corresponds to the Zig tag origin.
	ModeOrigin Mode = 6
	// ModeWraparound corresponds to the Zig tag wraparound.
	ModeWraparound Mode = 7
	// ModeAutorepeat corresponds to the Zig tag autorepeat.
	ModeAutorepeat Mode = 8
	// ModeMouseEventX10 corresponds to the Zig tag mouse_event_x10.
	ModeMouseEventX10 Mode = 9
	// ModeCursorBlinking corresponds to the Zig tag cursor_blinking.
	ModeCursorBlinking Mode = 12
	// ModeCursorVisible corresponds to the Zig tag cursor_visible.
	ModeCursorVisible Mode = 25
	// ModeEnableMode3 corresponds to the Zig tag enable_mode_3.
	ModeEnableMode3 Mode = 40
	// ModeReverseWrap corresponds to the Zig tag reverse_wrap.
	ModeReverseWrap Mode = 45
	// ModeAltScreenLegacy corresponds to the Zig tag alt_screen_legacy.
	ModeAltScreenLegacy Mode = 47
	// ModeKeypadKeys corresponds to the Zig tag keypad_keys.
	ModeKeypadKeys Mode = 66
	// ModeBackarrowKeyMode corresponds to the Zig tag backarrow_key_mode.
	ModeBackarrowKeyMode Mode = 67
	// ModeEnableLeftAndRightMargin corresponds to the Zig tag enable_left_and_right_margin.
	ModeEnableLeftAndRightMargin Mode = 69
	// ModeMouseEventNormal corresponds to the Zig tag mouse_event_normal.
	ModeMouseEventNormal Mode = 1000
	// ModeMouseEventButton corresponds to the Zig tag mouse_event_button.
	ModeMouseEventButton Mode = 1002
	// ModeMouseEventAny corresponds to the Zig tag mouse_event_any.
	ModeMouseEventAny Mode = 1003
	// ModeFocusEvent corresponds to the Zig tag focus_event.
	ModeFocusEvent Mode = 1004
	// ModeMouseFormatUTF8 corresponds to the Zig tag mouse_format_utf8.
	ModeMouseFormatUTF8 Mode = 1005
	// ModeMouseFormatSgr corresponds to the Zig tag mouse_format_sgr.
	ModeMouseFormatSgr Mode = 1006
	// ModeMouseAlternateScroll corresponds to the Zig tag mouse_alternate_scroll.
	ModeMouseAlternateScroll Mode = 1007
	// ModeMouseFormatUrxvt corresponds to the Zig tag mouse_format_urxvt.
	ModeMouseFormatUrxvt Mode = 1015
	// ModeMouseFormatSgrPixels corresponds to the Zig tag mouse_format_sgr_pixels.
	ModeMouseFormatSgrPixels Mode = 1016
	// ModeIgnoreKeypadWithNumlock corresponds to the Zig tag ignore_keypad_with_numlock.
	ModeIgnoreKeypadWithNumlock Mode = 1035
	// ModeAltEscPrefix corresponds to the Zig tag alt_esc_prefix.
	ModeAltEscPrefix Mode = 1036
	// ModeAltSendsEscape corresponds to the Zig tag alt_sends_escape.
	ModeAltSendsEscape Mode = 1039
	// ModeReverseWrapExtended corresponds to the Zig tag reverse_wrap_extended.
	ModeReverseWrapExtended Mode = 1045
	// ModeAltScreen corresponds to the Zig tag alt_screen.
	ModeAltScreen Mode = 1047
	// ModeSaveCursor corresponds to the Zig tag save_cursor.
	ModeSaveCursor Mode = 1048
	// ModeAltScreenSaveCursorClearEnter corresponds to the Zig tag alt_screen_save_cursor_clear_enter.
	ModeAltScreenSaveCursorClearEnter Mode = 1049
	// ModeBracketedPaste corresponds to the Zig tag bracketed_paste.
	ModeBracketedPaste Mode = 2004
	// ModeSynchronizedOutput corresponds to the Zig tag synchronized_output.
	ModeSynchronizedOutput Mode = 2026
	// ModeGraphemeCluster corresponds to the Zig tag grapheme_cluster.
	ModeGraphemeCluster Mode = 2027
	// ModeReportColorScheme corresponds to the Zig tag report_color_scheme.
	ModeReportColorScheme Mode = 2031
	// ModeReportVisibility corresponds to the Zig tag report_visibility.
	ModeReportVisibility Mode = 2033
	// ModeInBandSizeReports corresponds to the Zig tag in_band_size_reports.
	ModeInBandSizeReports Mode = 2048
	// ModeKittyPasteEvents corresponds to the Zig tag kitty_paste_events.
	ModeKittyPasteEvents Mode = 5522
)

// String returns the Zig tag name.
func (value Mode) String() string {
	switch value {
	case ModeDisableKeyboard:
		return "disable_keyboard"
	case ModeInsert:
		return "insert"
	case ModeSendReceiveMode:
		return "send_receive_mode"
	case ModeLinefeed:
		return "linefeed"
	case ModeCursorKeys:
		return "cursor_keys"
	case Mode132Column:
		return "132_column"
	case ModeSlowScroll:
		return "slow_scroll"
	case ModeReverseColors:
		return "reverse_colors"
	case ModeOrigin:
		return "origin"
	case ModeWraparound:
		return "wraparound"
	case ModeAutorepeat:
		return "autorepeat"
	case ModeMouseEventX10:
		return "mouse_event_x10"
	case ModeCursorBlinking:
		return "cursor_blinking"
	case ModeCursorVisible:
		return "cursor_visible"
	case ModeEnableMode3:
		return "enable_mode_3"
	case ModeReverseWrap:
		return "reverse_wrap"
	case ModeAltScreenLegacy:
		return "alt_screen_legacy"
	case ModeKeypadKeys:
		return "keypad_keys"
	case ModeBackarrowKeyMode:
		return "backarrow_key_mode"
	case ModeEnableLeftAndRightMargin:
		return "enable_left_and_right_margin"
	case ModeMouseEventNormal:
		return "mouse_event_normal"
	case ModeMouseEventButton:
		return "mouse_event_button"
	case ModeMouseEventAny:
		return "mouse_event_any"
	case ModeFocusEvent:
		return "focus_event"
	case ModeMouseFormatUTF8:
		return "mouse_format_utf8"
	case ModeMouseFormatSgr:
		return "mouse_format_sgr"
	case ModeMouseAlternateScroll:
		return "mouse_alternate_scroll"
	case ModeMouseFormatUrxvt:
		return "mouse_format_urxvt"
	case ModeMouseFormatSgrPixels:
		return "mouse_format_sgr_pixels"
	case ModeIgnoreKeypadWithNumlock:
		return "ignore_keypad_with_numlock"
	case ModeAltEscPrefix:
		return "alt_esc_prefix"
	case ModeAltSendsEscape:
		return "alt_sends_escape"
	case ModeReverseWrapExtended:
		return "reverse_wrap_extended"
	case ModeAltScreen:
		return "alt_screen"
	case ModeSaveCursor:
		return "save_cursor"
	case ModeAltScreenSaveCursorClearEnter:
		return "alt_screen_save_cursor_clear_enter"
	case ModeBracketedPaste:
		return "bracketed_paste"
	case ModeSynchronizedOutput:
		return "synchronized_output"
	case ModeGraphemeCluster:
		return "grapheme_cluster"
	case ModeReportColorScheme:
		return "report_color_scheme"
	case ModeReportVisibility:
		return "report_visibility"
	case ModeInBandSizeReports:
		return "in_band_size_reports"
	case ModeKittyPasteEvents:
		return "kitty_paste_events"
	}
	return "Mode(" + strconv.Itoa(int(value)) + ")"
}

// ParseMode returns the Mode named by text, which is a Zig tag name.
func ParseMode(text string) (Mode, error) {
	switch text {
	case "disable_keyboard":
		return ModeDisableKeyboard, nil
	case "insert":
		return ModeInsert, nil
	case "send_receive_mode":
		return ModeSendReceiveMode, nil
	case "linefeed":
		return ModeLinefeed, nil
	case "cursor_keys":
		return ModeCursorKeys, nil
	case "132_column":
		return Mode132Column, nil
	case "slow_scroll":
		return ModeSlowScroll, nil
	case "reverse_colors":
		return ModeReverseColors, nil
	case "origin":
		return ModeOrigin, nil
	case "wraparound":
		return ModeWraparound, nil
	case "autorepeat":
		return ModeAutorepeat, nil
	case "mouse_event_x10":
		return ModeMouseEventX10, nil
	case "cursor_blinking":
		return ModeCursorBlinking, nil
	case "cursor_visible":
		return ModeCursorVisible, nil
	case "enable_mode_3":
		return ModeEnableMode3, nil
	case "reverse_wrap":
		return ModeReverseWrap, nil
	case "alt_screen_legacy":
		return ModeAltScreenLegacy, nil
	case "keypad_keys":
		return ModeKeypadKeys, nil
	case "backarrow_key_mode":
		return ModeBackarrowKeyMode, nil
	case "enable_left_and_right_margin":
		return ModeEnableLeftAndRightMargin, nil
	case "mouse_event_normal":
		return ModeMouseEventNormal, nil
	case "mouse_event_button":
		return ModeMouseEventButton, nil
	case "mouse_event_any":
		return ModeMouseEventAny, nil
	case "focus_event":
		return ModeFocusEvent, nil
	case "mouse_format_utf8":
		return ModeMouseFormatUTF8, nil
	case "mouse_format_sgr":
		return ModeMouseFormatSgr, nil
	case "mouse_alternate_scroll":
		return ModeMouseAlternateScroll, nil
	case "mouse_format_urxvt":
		return ModeMouseFormatUrxvt, nil
	case "mouse_format_sgr_pixels":
		return ModeMouseFormatSgrPixels, nil
	case "ignore_keypad_with_numlock":
		return ModeIgnoreKeypadWithNumlock, nil
	case "alt_esc_prefix":
		return ModeAltEscPrefix, nil
	case "alt_sends_escape":
		return ModeAltSendsEscape, nil
	case "reverse_wrap_extended":
		return ModeReverseWrapExtended, nil
	case "alt_screen":
		return ModeAltScreen, nil
	case "save_cursor":
		return ModeSaveCursor, nil
	case "alt_screen_save_cursor_clear_enter":
		return ModeAltScreenSaveCursorClearEnter, nil
	case "bracketed_paste":
		return ModeBracketedPaste, nil
	case "synchronized_output":
		return ModeSynchronizedOutput, nil
	case "grapheme_cluster":
		return ModeGraphemeCluster, nil
	case "report_color_scheme":
		return ModeReportColorScheme, nil
	case "report_visibility":
		return ModeReportVisibility, nil
	case "in_band_size_reports":
		return ModeInBandSizeReports, nil
	case "kitty_paste_events":
		return ModeKittyPasteEvents, nil
	}
	return 0, &EnumParseError{Type: "Mode", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value Mode) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseMode.
func (value *Mode) UnmarshalText(text []byte) error {
	parsed, err := ParseMode(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ModeValues returns a fresh slice of known values in declaration order.
func ModeValues() []Mode {
	return []Mode{
		ModeDisableKeyboard,
		ModeInsert,
		ModeSendReceiveMode,
		ModeLinefeed,
		ModeCursorKeys,
		Mode132Column,
		ModeSlowScroll,
		ModeReverseColors,
		ModeOrigin,
		ModeWraparound,
		ModeAutorepeat,
		ModeMouseEventX10,
		ModeCursorBlinking,
		ModeCursorVisible,
		ModeEnableMode3,
		ModeReverseWrap,
		ModeAltScreenLegacy,
		ModeKeypadKeys,
		ModeBackarrowKeyMode,
		ModeEnableLeftAndRightMargin,
		ModeMouseEventNormal,
		ModeMouseEventButton,
		ModeMouseEventAny,
		ModeFocusEvent,
		ModeMouseFormatUTF8,
		ModeMouseFormatSgr,
		ModeMouseAlternateScroll,
		ModeMouseFormatUrxvt,
		ModeMouseFormatSgrPixels,
		ModeIgnoreKeypadWithNumlock,
		ModeAltEscPrefix,
		ModeAltSendsEscape,
		ModeReverseWrapExtended,
		ModeAltScreen,
		ModeSaveCursor,
		ModeAltScreenSaveCursorClearEnter,
		ModeBracketedPaste,
		ModeSynchronizedOutput,
		ModeGraphemeCluster,
		ModeReportColorScheme,
		ModeReportVisibility,
		ModeInBandSizeReports,
		ModeKittyPasteEvents,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value Mode) IsKnown() bool {
	switch value {
	case ModeDisableKeyboard:
		return true
	case ModeInsert:
		return true
	case ModeSendReceiveMode:
		return true
	case ModeLinefeed:
		return true
	case ModeCursorKeys:
		return true
	case Mode132Column:
		return true
	case ModeSlowScroll:
		return true
	case ModeReverseColors:
		return true
	case ModeOrigin:
		return true
	case ModeWraparound:
		return true
	case ModeAutorepeat:
		return true
	case ModeMouseEventX10:
		return true
	case ModeCursorBlinking:
		return true
	case ModeCursorVisible:
		return true
	case ModeEnableMode3:
		return true
	case ModeReverseWrap:
		return true
	case ModeAltScreenLegacy:
		return true
	case ModeKeypadKeys:
		return true
	case ModeBackarrowKeyMode:
		return true
	case ModeEnableLeftAndRightMargin:
		return true
	case ModeMouseEventNormal:
		return true
	case ModeMouseEventButton:
		return true
	case ModeMouseEventAny:
		return true
	case ModeFocusEvent:
		return true
	case ModeMouseFormatUTF8:
		return true
	case ModeMouseFormatSgr:
		return true
	case ModeMouseAlternateScroll:
		return true
	case ModeMouseFormatUrxvt:
		return true
	case ModeMouseFormatSgrPixels:
		return true
	case ModeIgnoreKeypadWithNumlock:
		return true
	case ModeAltEscPrefix:
		return true
	case ModeAltSendsEscape:
		return true
	case ModeReverseWrapExtended:
		return true
	case ModeAltScreen:
		return true
	case ModeSaveCursor:
		return true
	case ModeAltScreenSaveCursorClearEnter:
		return true
	case ModeBracketedPaste:
		return true
	case ModeSynchronizedOutput:
		return true
	case ModeGraphemeCluster:
		return true
	case ModeReportColorScheme:
		return true
	case ModeReportVisibility:
		return true
	case ModeInBandSizeReports:
		return true
	case ModeKittyPasteEvents:
		return true
	}
	return false
}

// FormatterFormat represents the corresponding Zig enum.
type FormatterFormat uint8

const (
	// FormatterFormatPlain corresponds to the Zig tag plain.
	FormatterFormatPlain FormatterFormat = 0
	// FormatterFormatVt corresponds to the Zig tag vt.
	FormatterFormatVt FormatterFormat = 1
	// FormatterFormatHtml corresponds to the Zig tag html.
	FormatterFormatHtml FormatterFormat = 2
)

var zigoFormatterFormatNames = [3]string{
	0: "plain",
	1: "vt",
	2: "html",
}

// String returns the Zig tag name.
func (value FormatterFormat) String() string {
	if value >= 0 && value <= 2 {
		return zigoFormatterFormatNames[uint64(value)]
	}
	return "FormatterFormat(" + strconv.Itoa(int(value)) + ")"
}

// ParseFormatterFormat returns the FormatterFormat named by text, which is a Zig tag name.
func ParseFormatterFormat(text string) (FormatterFormat, error) {
	switch text {
	case "plain":
		return FormatterFormatPlain, nil
	case "vt":
		return FormatterFormatVt, nil
	case "html":
		return FormatterFormatHtml, nil
	}
	return 0, &EnumParseError{Type: "FormatterFormat", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value FormatterFormat) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseFormatterFormat.
func (value *FormatterFormat) UnmarshalText(text []byte) error {
	parsed, err := ParseFormatterFormat(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// SelectionAdjustment represents the corresponding Zig enum.
type SelectionAdjustment uint8

const (
	// SelectionAdjustmentLeft corresponds to the Zig tag left.
	SelectionAdjustmentLeft SelectionAdjustment = 0
	// SelectionAdjustmentRight corresponds to the Zig tag right.
	SelectionAdjustmentRight SelectionAdjustment = 1
	// SelectionAdjustmentUp corresponds to the Zig tag up.
	SelectionAdjustmentUp SelectionAdjustment = 2
	// SelectionAdjustmentDown corresponds to the Zig tag down.
	SelectionAdjustmentDown SelectionAdjustment = 3
	// SelectionAdjustmentHome corresponds to the Zig tag home.
	SelectionAdjustmentHome SelectionAdjustment = 4
	// SelectionAdjustmentEnd corresponds to the Zig tag end.
	SelectionAdjustmentEnd SelectionAdjustment = 5
	// SelectionAdjustmentPageUp corresponds to the Zig tag page_up.
	SelectionAdjustmentPageUp SelectionAdjustment = 6
	// SelectionAdjustmentPageDown corresponds to the Zig tag page_down.
	SelectionAdjustmentPageDown SelectionAdjustment = 7
	// SelectionAdjustmentBeginningOfLine corresponds to the Zig tag beginning_of_line.
	SelectionAdjustmentBeginningOfLine SelectionAdjustment = 8
	// SelectionAdjustmentEndOfLine corresponds to the Zig tag end_of_line.
	SelectionAdjustmentEndOfLine SelectionAdjustment = 9
)

var zigoSelectionAdjustmentNames = [10]string{
	0: "left",
	1: "right",
	2: "up",
	3: "down",
	4: "home",
	5: "end",
	6: "page_up",
	7: "page_down",
	8: "beginning_of_line",
	9: "end_of_line",
}

// String returns the Zig tag name.
func (value SelectionAdjustment) String() string {
	if value >= 0 && value <= 9 {
		return zigoSelectionAdjustmentNames[uint64(value)]
	}
	return "SelectionAdjustment(" + strconv.Itoa(int(value)) + ")"
}

// ParseSelectionAdjustment returns the SelectionAdjustment named by text, which is a Zig tag name.
func ParseSelectionAdjustment(text string) (SelectionAdjustment, error) {
	switch text {
	case "left":
		return SelectionAdjustmentLeft, nil
	case "right":
		return SelectionAdjustmentRight, nil
	case "up":
		return SelectionAdjustmentUp, nil
	case "down":
		return SelectionAdjustmentDown, nil
	case "home":
		return SelectionAdjustmentHome, nil
	case "end":
		return SelectionAdjustmentEnd, nil
	case "page_up":
		return SelectionAdjustmentPageUp, nil
	case "page_down":
		return SelectionAdjustmentPageDown, nil
	case "beginning_of_line":
		return SelectionAdjustmentBeginningOfLine, nil
	case "end_of_line":
		return SelectionAdjustmentEndOfLine, nil
	}
	return 0, &EnumParseError{Type: "SelectionAdjustment", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value SelectionAdjustment) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseSelectionAdjustment.
func (value *SelectionAdjustment) UnmarshalText(text []byte) error {
	parsed, err := ParseSelectionAdjustment(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// Underline represents the corresponding Zig enum.
type Underline uint8

const (
	// UnderlineNone corresponds to the Zig tag none.
	UnderlineNone Underline = 0
	// UnderlineSingle corresponds to the Zig tag single.
	UnderlineSingle Underline = 1
	// UnderlineDouble corresponds to the Zig tag double.
	UnderlineDouble Underline = 2
	// UnderlineCurly corresponds to the Zig tag curly.
	UnderlineCurly Underline = 3
	// UnderlineDotted corresponds to the Zig tag dotted.
	UnderlineDotted Underline = 4
	// UnderlineDashed corresponds to the Zig tag dashed.
	UnderlineDashed Underline = 5
)

var zigoUnderlineNames = [6]string{
	0: "none",
	1: "single",
	2: "double",
	3: "curly",
	4: "dotted",
	5: "dashed",
}

// String returns the Zig tag name.
func (value Underline) String() string {
	if value >= 0 && value <= 5 {
		return zigoUnderlineNames[uint64(value)]
	}
	return "Underline(" + strconv.Itoa(int(value)) + ")"
}

// AttributeTag represents the corresponding Zig enum.
type AttributeTag uint8

const (
	// AttributeTagUnset corresponds to the Zig tag unset.
	AttributeTagUnset AttributeTag = 0
	// AttributeTagBold corresponds to the Zig tag bold.
	AttributeTagBold AttributeTag = 1
	// AttributeTagResetBold corresponds to the Zig tag reset_bold.
	AttributeTagResetBold AttributeTag = 2
	// AttributeTagItalic corresponds to the Zig tag italic.
	AttributeTagItalic AttributeTag = 3
	// AttributeTagResetItalic corresponds to the Zig tag reset_italic.
	AttributeTagResetItalic AttributeTag = 4
	// AttributeTagFaint corresponds to the Zig tag faint.
	AttributeTagFaint AttributeTag = 5
	// AttributeTagUnderline corresponds to the Zig tag underline.
	AttributeTagUnderline AttributeTag = 6
	// AttributeTagUnderlineColorRgb corresponds to the Zig tag underline_color_rgb.
	AttributeTagUnderlineColorRgb AttributeTag = 7
	// AttributeTagUnderlineColor256 corresponds to the Zig tag underline_color_256.
	AttributeTagUnderlineColor256 AttributeTag = 8
	// AttributeTagResetUnderlineColor corresponds to the Zig tag reset_underline_color.
	AttributeTagResetUnderlineColor AttributeTag = 9
	// AttributeTagOverline corresponds to the Zig tag overline.
	AttributeTagOverline AttributeTag = 10
	// AttributeTagResetOverline corresponds to the Zig tag reset_overline.
	AttributeTagResetOverline AttributeTag = 11
	// AttributeTagBlink corresponds to the Zig tag blink.
	AttributeTagBlink AttributeTag = 12
	// AttributeTagResetBlink corresponds to the Zig tag reset_blink.
	AttributeTagResetBlink AttributeTag = 13
	// AttributeTagInverse corresponds to the Zig tag inverse.
	AttributeTagInverse AttributeTag = 14
	// AttributeTagResetInverse corresponds to the Zig tag reset_inverse.
	AttributeTagResetInverse AttributeTag = 15
	// AttributeTagInvisible corresponds to the Zig tag invisible.
	AttributeTagInvisible AttributeTag = 16
	// AttributeTagResetInvisible corresponds to the Zig tag reset_invisible.
	AttributeTagResetInvisible AttributeTag = 17
	// AttributeTagStrikethrough corresponds to the Zig tag strikethrough.
	AttributeTagStrikethrough AttributeTag = 18
	// AttributeTagResetStrikethrough corresponds to the Zig tag reset_strikethrough.
	AttributeTagResetStrikethrough AttributeTag = 19
	// AttributeTagDirectColorFg corresponds to the Zig tag direct_color_fg.
	AttributeTagDirectColorFg AttributeTag = 20
	// AttributeTagDirectColorBg corresponds to the Zig tag direct_color_bg.
	AttributeTagDirectColorBg AttributeTag = 21
	// AttributeTagColor256Fg corresponds to the Zig tag color_256_fg.
	AttributeTagColor256Fg AttributeTag = 22
	// AttributeTagColor256Bg corresponds to the Zig tag color_256_bg.
	AttributeTagColor256Bg AttributeTag = 23
	// AttributeTagNamedFg corresponds to the Zig tag named_fg.
	AttributeTagNamedFg AttributeTag = 24
	// AttributeTagNamedBg corresponds to the Zig tag named_bg.
	AttributeTagNamedBg AttributeTag = 25
	// AttributeTagBrightNamedFg corresponds to the Zig tag bright_named_fg.
	AttributeTagBrightNamedFg AttributeTag = 26
	// AttributeTagBrightNamedBg corresponds to the Zig tag bright_named_bg.
	AttributeTagBrightNamedBg AttributeTag = 27
	// AttributeTagResetFg corresponds to the Zig tag reset_fg.
	AttributeTagResetFg AttributeTag = 28
	// AttributeTagResetBg corresponds to the Zig tag reset_bg.
	AttributeTagResetBg AttributeTag = 29
	// AttributeTagUnknown corresponds to the Zig tag unknown.
	AttributeTagUnknown AttributeTag = 30
)

var zigoAttributeTagNames = [31]string{
	0:  "unset",
	1:  "bold",
	2:  "reset_bold",
	3:  "italic",
	4:  "reset_italic",
	5:  "faint",
	6:  "underline",
	7:  "underline_color_rgb",
	8:  "underline_color_256",
	9:  "reset_underline_color",
	10: "overline",
	11: "reset_overline",
	12: "blink",
	13: "reset_blink",
	14: "inverse",
	15: "reset_inverse",
	16: "invisible",
	17: "reset_invisible",
	18: "strikethrough",
	19: "reset_strikethrough",
	20: "direct_color_fg",
	21: "direct_color_bg",
	22: "color_256_fg",
	23: "color_256_bg",
	24: "named_fg",
	25: "named_bg",
	26: "bright_named_fg",
	27: "bright_named_bg",
	28: "reset_fg",
	29: "reset_bg",
	30: "unknown",
}

// String returns the Zig tag name.
func (value AttributeTag) String() string {
	if value >= 0 && value <= 30 {
		return zigoAttributeTagNames[uint64(value)]
	}
	return "AttributeTag(" + strconv.Itoa(int(value)) + ")"
}

// SearchDirection represents the corresponding Zig enum.
type SearchDirection uint8

const (
	// SearchDirectionNext corresponds to the Zig tag next.
	SearchDirectionNext SearchDirection = 0
	// SearchDirectionPrev corresponds to the Zig tag prev.
	SearchDirectionPrev SearchDirection = 1
)

var zigoSearchDirectionNames = [2]string{
	0: "next",
	1: "prev",
}

// String returns the Zig tag name.
func (value SearchDirection) String() string {
	if value >= 0 && value <= 1 {
		return zigoSearchDirectionNames[uint64(value)]
	}
	return "SearchDirection(" + strconv.Itoa(int(value)) + ")"
}

// SearchScroll represents the corresponding Zig enum.
type SearchScroll uint8

const (
	// SearchScrollIfNeeded corresponds to the Zig tag if_needed.
	SearchScrollIfNeeded SearchScroll = 0
	// SearchScrollNone corresponds to the Zig tag none.
	SearchScrollNone SearchScroll = 1
)

var zigoSearchScrollNames = [2]string{
	0: "if_needed",
	1: "none",
}

// String returns the Zig tag name.
func (value SearchScroll) String() string {
	if value >= 0 && value <= 1 {
		return zigoSearchScrollNames[uint64(value)]
	}
	return "SearchScroll(" + strconv.Itoa(int(value)) + ")"
}

// SearchState represents the corresponding Zig enum.
type SearchState uint8

const (
	// SearchStateRunning corresponds to the Zig tag running.
	SearchStateRunning SearchState = 0
	// SearchStateFeedRequired corresponds to the Zig tag feed_required.
	SearchStateFeedRequired SearchState = 1
	// SearchStateComplete corresponds to the Zig tag complete.
	SearchStateComplete SearchState = 2
)

var zigoSearchStateNames = [3]string{
	0: "running",
	1: "feed_required",
	2: "complete",
}

// String returns the Zig tag name.
func (value SearchState) String() string {
	if value >= 0 && value <= 2 {
		return zigoSearchStateNames[uint64(value)]
	}
	return "SearchState(" + strconv.Itoa(int(value)) + ")"
}

// SearchProgress represents the corresponding Zig enum.
type SearchProgress uint8

const (
	// SearchProgressComplete corresponds to the Zig tag complete.
	SearchProgressComplete SearchProgress = 0
	// SearchProgressProgress corresponds to the Zig tag progress.
	SearchProgressProgress SearchProgress = 1
	// SearchProgressBlocked corresponds to the Zig tag blocked.
	SearchProgressBlocked SearchProgress = 2
)

var zigoSearchProgressNames = [3]string{
	0: "complete",
	1: "progress",
	2: "blocked",
}

// String returns the Zig tag name.
func (value SearchProgress) String() string {
	if value >= 0 && value <= 2 {
		return zigoSearchProgressNames[uint64(value)]
	}
	return "SearchProgress(" + strconv.Itoa(int(value)) + ")"
}

// Charset represents the corresponding Zig enum.
type Charset uint8

const (
	// CharsetUTF8 corresponds to the Zig tag utf8.
	CharsetUTF8 Charset = 0
	// CharsetAscii corresponds to the Zig tag ascii.
	CharsetAscii Charset = 1
	// CharsetBritish corresponds to the Zig tag british.
	CharsetBritish Charset = 2
	// CharsetDecSpecial corresponds to the Zig tag dec_special.
	CharsetDecSpecial Charset = 3
)

var zigoCharsetNames = [4]string{
	0: "utf8",
	1: "ascii",
	2: "british",
	3: "dec_special",
}

// String returns the Zig tag name.
func (value Charset) String() string {
	if value >= 0 && value <= 3 {
		return zigoCharsetNames[uint64(value)]
	}
	return "Charset(" + strconv.Itoa(int(value)) + ")"
}

// CharsetSlot represents the corresponding Zig enum.
type CharsetSlot uint8

const (
	// CharsetSlotG0 corresponds to the Zig tag G0.
	CharsetSlotG0 CharsetSlot = 0
	// CharsetSlotG1 corresponds to the Zig tag G1.
	CharsetSlotG1 CharsetSlot = 1
	// CharsetSlotG2 corresponds to the Zig tag G2.
	CharsetSlotG2 CharsetSlot = 2
	// CharsetSlotG3 corresponds to the Zig tag G3.
	CharsetSlotG3 CharsetSlot = 3
)

var zigoCharsetSlotNames = [4]string{
	0: "G0",
	1: "G1",
	2: "G2",
	3: "G3",
}

// String returns the Zig tag name.
func (value CharsetSlot) String() string {
	if value >= 0 && value <= 3 {
		return zigoCharsetSlotNames[uint64(value)]
	}
	return "CharsetSlot(" + strconv.Itoa(int(value)) + ")"
}

// CharsetActiveSlot represents the corresponding Zig enum.
type CharsetActiveSlot uint8

const (
	// CharsetActiveSlotGl corresponds to the Zig tag GL.
	CharsetActiveSlotGl CharsetActiveSlot = 0
	// CharsetActiveSlotGr corresponds to the Zig tag GR.
	CharsetActiveSlotGr CharsetActiveSlot = 1
)

var zigoCharsetActiveSlotNames = [2]string{
	0: "GL",
	1: "GR",
}

// String returns the Zig tag name.
func (value CharsetActiveSlot) String() string {
	if value >= 0 && value <= 1 {
		return zigoCharsetActiveSlotNames[uint64(value)]
	}
	return "CharsetActiveSlot(" + strconv.Itoa(int(value)) + ")"
}

// DeccolmMode represents the corresponding Zig enum.
type DeccolmMode uint8

const (
	// DeccolmMode80Cols corresponds to the Zig tag 80_cols.
	DeccolmMode80Cols DeccolmMode = 0
	// DeccolmMode132Cols corresponds to the Zig tag 132_cols.
	DeccolmMode132Cols DeccolmMode = 1
)

var zigoDeccolmModeNames = [2]string{
	0: "80_cols",
	1: "132_cols",
}

// String returns the Zig tag name.
func (value DeccolmMode) String() string {
	if value >= 0 && value <= 1 {
		return zigoDeccolmModeNames[uint64(value)]
	}
	return "DeccolmMode(" + strconv.Itoa(int(value)) + ")"
}

// ScrollViewportTag represents the corresponding Zig enum.
type ScrollViewportTag uint8

const (
	// ScrollViewportTagTop corresponds to the Zig tag top.
	ScrollViewportTagTop ScrollViewportTag = 0
	// ScrollViewportTagBottom corresponds to the Zig tag bottom.
	ScrollViewportTagBottom ScrollViewportTag = 1
	// ScrollViewportTagDelta corresponds to the Zig tag delta.
	ScrollViewportTagDelta ScrollViewportTag = 2
	// ScrollViewportTagRow corresponds to the Zig tag row.
	ScrollViewportTagRow ScrollViewportTag = 3
)

var zigoScrollViewportTagNames = [4]string{
	0: "top",
	1: "bottom",
	2: "delta",
	3: "row",
}

// String returns the Zig tag name.
func (value ScrollViewportTag) String() string {
	if value >= 0 && value <= 3 {
		return zigoScrollViewportTagNames[uint64(value)]
	}
	return "ScrollViewportTag(" + strconv.Itoa(int(value)) + ")"
}

// MouseTracking represents the corresponding Zig enum.
type MouseTracking uint8

const (
	// MouseTrackingNone corresponds to the Zig tag none.
	MouseTrackingNone MouseTracking = 0
	// MouseTrackingX10 corresponds to the Zig tag x10.
	MouseTrackingX10 MouseTracking = 1
	// MouseTrackingNormal corresponds to the Zig tag normal.
	MouseTrackingNormal MouseTracking = 2
	// MouseTrackingButton corresponds to the Zig tag button.
	MouseTrackingButton MouseTracking = 3
	// MouseTrackingAny corresponds to the Zig tag any.
	MouseTrackingAny MouseTracking = 4
)

var zigoMouseTrackingNames = [5]string{
	0: "none",
	1: "x10",
	2: "normal",
	3: "button",
	4: "any",
}

// String returns the Zig tag name.
func (value MouseTracking) String() string {
	if value >= 0 && value <= 4 {
		return zigoMouseTrackingNames[uint64(value)]
	}
	return "MouseTracking(" + strconv.Itoa(int(value)) + ")"
}

// ParseMouseTracking returns the MouseTracking named by text, which is a Zig tag name.
func ParseMouseTracking(text string) (MouseTracking, error) {
	switch text {
	case "none":
		return MouseTrackingNone, nil
	case "x10":
		return MouseTrackingX10, nil
	case "normal":
		return MouseTrackingNormal, nil
	case "button":
		return MouseTrackingButton, nil
	case "any":
		return MouseTrackingAny, nil
	}
	return 0, &EnumParseError{Type: "MouseTracking", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value MouseTracking) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseMouseTracking.
func (value *MouseTracking) UnmarshalText(text []byte) error {
	parsed, err := ParseMouseTracking(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// MouseReportFormat represents the corresponding Zig enum.
type MouseReportFormat uint8

const (
	// MouseReportFormatX10 corresponds to the Zig tag x10.
	MouseReportFormatX10 MouseReportFormat = 0
	// MouseReportFormatUTF8 corresponds to the Zig tag utf8.
	MouseReportFormatUTF8 MouseReportFormat = 1
	// MouseReportFormatSgr corresponds to the Zig tag sgr.
	MouseReportFormatSgr MouseReportFormat = 2
	// MouseReportFormatUrxvt corresponds to the Zig tag urxvt.
	MouseReportFormatUrxvt MouseReportFormat = 3
	// MouseReportFormatSgrPixels corresponds to the Zig tag sgr_pixels.
	MouseReportFormatSgrPixels MouseReportFormat = 4
)

var zigoMouseReportFormatNames = [5]string{
	0: "x10",
	1: "utf8",
	2: "sgr",
	3: "urxvt",
	4: "sgr_pixels",
}

// String returns the Zig tag name.
func (value MouseReportFormat) String() string {
	if value >= 0 && value <= 4 {
		return zigoMouseReportFormatNames[uint64(value)]
	}
	return "MouseReportFormat(" + strconv.Itoa(int(value)) + ")"
}

// ParseMouseReportFormat returns the MouseReportFormat named by text, which is a Zig tag name.
func ParseMouseReportFormat(text string) (MouseReportFormat, error) {
	switch text {
	case "x10":
		return MouseReportFormatX10, nil
	case "utf8":
		return MouseReportFormatUTF8, nil
	case "sgr":
		return MouseReportFormatSgr, nil
	case "urxvt":
		return MouseReportFormatUrxvt, nil
	case "sgr_pixels":
		return MouseReportFormatSgrPixels, nil
	}
	return 0, &EnumParseError{Type: "MouseReportFormat", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value MouseReportFormat) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseMouseReportFormat.
func (value *MouseReportFormat) UnmarshalText(text []byte) error {
	parsed, err := ParseMouseReportFormat(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ModeReport represents the corresponding Zig enum.
type ModeReport uint8

const (
	// ModeReportNotRecognized corresponds to the Zig tag not_recognized.
	ModeReportNotRecognized ModeReport = 0
	// ModeReportSet corresponds to the Zig tag set.
	ModeReportSet ModeReport = 1
	// ModeReportReset corresponds to the Zig tag reset.
	ModeReportReset ModeReport = 2
	// ModeReportPermanentlySet corresponds to the Zig tag permanently_set.
	ModeReportPermanentlySet ModeReport = 3
	// ModeReportPermanentlyReset corresponds to the Zig tag permanently_reset.
	ModeReportPermanentlyReset ModeReport = 4
)

var zigoModeReportNames = [5]string{
	0: "not_recognized",
	1: "set",
	2: "reset",
	3: "permanently_set",
	4: "permanently_reset",
}

// String returns the Zig tag name.
func (value ModeReport) String() string {
	if value >= 0 && value <= 4 {
		return zigoModeReportNames[uint64(value)]
	}
	return "ModeReport(" + strconv.Itoa(int(value)) + ")"
}

// ParseModeReport returns the ModeReport named by text, which is a Zig tag name.
func ParseModeReport(text string) (ModeReport, error) {
	switch text {
	case "not_recognized":
		return ModeReportNotRecognized, nil
	case "set":
		return ModeReportSet, nil
	case "reset":
		return ModeReportReset, nil
	case "permanently_set":
		return ModeReportPermanentlySet, nil
	case "permanently_reset":
		return ModeReportPermanentlyReset, nil
	}
	return 0, &EnumParseError{Type: "ModeReport", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value ModeReport) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseModeReport.
func (value *ModeReport) UnmarshalText(text []byte) error {
	parsed, err := ParseModeReport(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// GestureBehavior represents the corresponding Zig enum.
type GestureBehavior uint8

const (
	// GestureBehaviorCell corresponds to the Zig tag cell.
	GestureBehaviorCell GestureBehavior = 0
	// GestureBehaviorWord corresponds to the Zig tag word.
	GestureBehaviorWord GestureBehavior = 1
	// GestureBehaviorLine corresponds to the Zig tag line.
	GestureBehaviorLine GestureBehavior = 2
	// GestureBehaviorOutput corresponds to the Zig tag output.
	GestureBehaviorOutput GestureBehavior = 3
)

var zigoGestureBehaviorNames = [4]string{
	0: "cell",
	1: "word",
	2: "line",
	3: "output",
}

// String returns the Zig tag name.
func (value GestureBehavior) String() string {
	if value >= 0 && value <= 3 {
		return zigoGestureBehaviorNames[uint64(value)]
	}
	return "GestureBehavior(" + strconv.Itoa(int(value)) + ")"
}

// ParseGestureBehavior returns the GestureBehavior named by text, which is a Zig tag name.
func ParseGestureBehavior(text string) (GestureBehavior, error) {
	switch text {
	case "cell":
		return GestureBehaviorCell, nil
	case "word":
		return GestureBehaviorWord, nil
	case "line":
		return GestureBehaviorLine, nil
	case "output":
		return GestureBehaviorOutput, nil
	}
	return 0, &EnumParseError{Type: "GestureBehavior", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value GestureBehavior) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseGestureBehavior.
func (value *GestureBehavior) UnmarshalText(text []byte) error {
	parsed, err := ParseGestureBehavior(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// GestureAutoscrollDirection represents the corresponding Zig enum.
type GestureAutoscrollDirection uint8

const (
	// GestureAutoscrollDirectionNone corresponds to the Zig tag none.
	GestureAutoscrollDirectionNone GestureAutoscrollDirection = 0
	// GestureAutoscrollDirectionUp corresponds to the Zig tag up.
	GestureAutoscrollDirectionUp GestureAutoscrollDirection = 1
	// GestureAutoscrollDirectionDown corresponds to the Zig tag down.
	GestureAutoscrollDirectionDown GestureAutoscrollDirection = 2
)

var zigoGestureAutoscrollDirectionNames = [3]string{
	0: "none",
	1: "up",
	2: "down",
}

// String returns the Zig tag name.
func (value GestureAutoscrollDirection) String() string {
	if value >= 0 && value <= 2 {
		return zigoGestureAutoscrollDirectionNames[uint64(value)]
	}
	return "GestureAutoscrollDirection(" + strconv.Itoa(int(value)) + ")"
}

// ParseGestureAutoscrollDirection returns the GestureAutoscrollDirection named by text, which is a Zig tag name.
func ParseGestureAutoscrollDirection(text string) (GestureAutoscrollDirection, error) {
	switch text {
	case "none":
		return GestureAutoscrollDirectionNone, nil
	case "up":
		return GestureAutoscrollDirectionUp, nil
	case "down":
		return GestureAutoscrollDirectionDown, nil
	}
	return 0, &EnumParseError{Type: "GestureAutoscrollDirection", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value GestureAutoscrollDirection) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseGestureAutoscrollDirection.
func (value *GestureAutoscrollDirection) UnmarshalText(text []byte) error {
	parsed, err := ParseGestureAutoscrollDirection(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// StreamEvent represents the corresponding Zig enum.
type StreamEvent uint8

const (
	// StreamEventBell corresponds to the Zig tag bell.
	StreamEventBell StreamEvent = 0
	// StreamEventTitleChanged corresponds to the Zig tag title_changed.
	StreamEventTitleChanged StreamEvent = 1
	// StreamEventPwdChanged corresponds to the Zig tag pwd_changed.
	StreamEventPwdChanged StreamEvent = 2
	// StreamEventDesktopNotification corresponds to the Zig tag desktop_notification.
	StreamEventDesktopNotification StreamEvent = 3
	// StreamEventProgressReport corresponds to the Zig tag progress_report.
	StreamEventProgressReport StreamEvent = 4
	// StreamEventUnknownSequence corresponds to the Zig tag unknown_sequence.
	StreamEventUnknownSequence StreamEvent = 5
)

var zigoStreamEventNames = [6]string{
	0: "bell",
	1: "title_changed",
	2: "pwd_changed",
	3: "desktop_notification",
	4: "progress_report",
	5: "unknown_sequence",
}

// String returns the Zig tag name.
func (value StreamEvent) String() string {
	if value >= 0 && value <= 5 {
		return zigoStreamEventNames[uint64(value)]
	}
	return "StreamEvent(" + strconv.Itoa(int(value)) + ")"
}

// ParseStreamEvent returns the StreamEvent named by text, which is a Zig tag name.
func ParseStreamEvent(text string) (StreamEvent, error) {
	switch text {
	case "bell":
		return StreamEventBell, nil
	case "title_changed":
		return StreamEventTitleChanged, nil
	case "pwd_changed":
		return StreamEventPwdChanged, nil
	case "desktop_notification":
		return StreamEventDesktopNotification, nil
	case "progress_report":
		return StreamEventProgressReport, nil
	case "unknown_sequence":
		return StreamEventUnknownSequence, nil
	}
	return 0, &EnumParseError{Type: "StreamEvent", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value StreamEvent) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseStreamEvent.
func (value *StreamEvent) UnmarshalText(text []byte) error {
	parsed, err := ParseStreamEvent(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ProgressState represents the corresponding Zig enum.
type ProgressState uint8

const (
	// ProgressStateRemove corresponds to the Zig tag remove.
	ProgressStateRemove ProgressState = 0
	// ProgressStateSet corresponds to the Zig tag set.
	ProgressStateSet ProgressState = 1
	// ProgressStateError corresponds to the Zig tag error.
	ProgressStateError ProgressState = 2
	// ProgressStateIndeterminate corresponds to the Zig tag indeterminate.
	ProgressStateIndeterminate ProgressState = 3
	// ProgressStatePause corresponds to the Zig tag pause.
	ProgressStatePause ProgressState = 4
)

var zigoProgressStateNames = [5]string{
	0: "remove",
	1: "set",
	2: "error",
	3: "indeterminate",
	4: "pause",
}

// String returns the Zig tag name.
func (value ProgressState) String() string {
	if value >= 0 && value <= 4 {
		return zigoProgressStateNames[uint64(value)]
	}
	return "ProgressState(" + strconv.Itoa(int(value)) + ")"
}

// ParseProgressState returns the ProgressState named by text, which is a Zig tag name.
func ParseProgressState(text string) (ProgressState, error) {
	switch text {
	case "remove":
		return ProgressStateRemove, nil
	case "set":
		return ProgressStateSet, nil
	case "error":
		return ProgressStateError, nil
	case "indeterminate":
		return ProgressStateIndeterminate, nil
	case "pause":
		return ProgressStatePause, nil
	}
	return 0, &EnumParseError{Type: "ProgressState", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value ProgressState) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseProgressState.
func (value *ProgressState) UnmarshalText(text []byte) error {
	parsed, err := ParseProgressState(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ColorScheme represents the corresponding Zig enum.
type ColorScheme uint8

const (
	// ColorSchemeLight corresponds to the Zig tag light.
	ColorSchemeLight ColorScheme = 0
	// ColorSchemeDark corresponds to the Zig tag dark.
	ColorSchemeDark ColorScheme = 1
)

var zigoColorSchemeNames = [2]string{
	0: "light",
	1: "dark",
}

// String returns the Zig tag name.
func (value ColorScheme) String() string {
	if value >= 0 && value <= 1 {
		return zigoColorSchemeNames[uint64(value)]
	}
	return "ColorScheme(" + strconv.Itoa(int(value)) + ")"
}

// ParseColorScheme returns the ColorScheme named by text, which is a Zig tag name.
func ParseColorScheme(text string) (ColorScheme, error) {
	switch text {
	case "light":
		return ColorSchemeLight, nil
	case "dark":
		return ColorSchemeDark, nil
	}
	return 0, &EnumParseError{Type: "ColorScheme", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value ColorScheme) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseColorScheme.
func (value *ColorScheme) UnmarshalText(text []byte) error {
	parsed, err := ParseColorScheme(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// DragEvent represents the corresponding Zig enum.
type DragEvent uint8

const (
	// DragEventRegistration corresponds to the Zig tag registration.
	DragEventRegistration DragEvent = 0
	// DragEventAcceptance corresponds to the Zig tag acceptance.
	DragEventAcceptance DragEvent = 1
	// DragEventConcludedNone corresponds to the Zig tag concluded_none.
	DragEventConcludedNone DragEvent = 2
	// DragEventConcludedCopy corresponds to the Zig tag concluded_copy.
	DragEventConcludedCopy DragEvent = 3
	// DragEventConcludedMove corresponds to the Zig tag concluded_move.
	DragEventConcludedMove DragEvent = 4
)

var zigoDragEventNames = [5]string{
	0: "registration",
	1: "acceptance",
	2: "concluded_none",
	3: "concluded_copy",
	4: "concluded_move",
}

// String returns the Zig tag name.
func (value DragEvent) String() string {
	if value >= 0 && value <= 4 {
		return zigoDragEventNames[uint64(value)]
	}
	return "DragEvent(" + strconv.Itoa(int(value)) + ")"
}

// ParseDragEvent returns the DragEvent named by text, which is a Zig tag name.
func ParseDragEvent(text string) (DragEvent, error) {
	switch text {
	case "registration":
		return DragEventRegistration, nil
	case "acceptance":
		return DragEventAcceptance, nil
	case "concluded_none":
		return DragEventConcludedNone, nil
	case "concluded_copy":
		return DragEventConcludedCopy, nil
	case "concluded_move":
		return DragEventConcludedMove, nil
	}
	return 0, &EnumParseError{Type: "DragEvent", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value DragEvent) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseDragEvent.
func (value *DragEvent) UnmarshalText(text []byte) error {
	parsed, err := ParseDragEvent(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// DragOperation represents the corresponding Zig enum.
type DragOperation uint8

const (
	// DragOperationNone corresponds to the Zig tag none.
	DragOperationNone DragOperation = 0
	// DragOperationCopy corresponds to the Zig tag copy.
	DragOperationCopy DragOperation = 1
	// DragOperationMove corresponds to the Zig tag move.
	DragOperationMove DragOperation = 2
)

var zigoDragOperationNames = [3]string{
	0: "none",
	1: "copy",
	2: "move",
}

// String returns the Zig tag name.
func (value DragOperation) String() string {
	if value >= 0 && value <= 2 {
		return zigoDragOperationNames[uint64(value)]
	}
	return "DragOperation(" + strconv.Itoa(int(value)) + ")"
}

// ParseDragOperation returns the DragOperation named by text, which is a Zig tag name.
func ParseDragOperation(text string) (DragOperation, error) {
	switch text {
	case "none":
		return DragOperationNone, nil
	case "copy":
		return DragOperationCopy, nil
	case "move":
		return DragOperationMove, nil
	}
	return 0, &EnumParseError{Type: "DragOperation", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value DragOperation) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseDragOperation.
func (value *DragOperation) UnmarshalText(text []byte) error {
	parsed, err := ParseDragOperation(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ClipboardLocation represents the corresponding Zig open enum; values outside the named constants are valid.
type ClipboardLocation int32

const (
	// ClipboardLocationStandard corresponds to the Zig tag standard.
	ClipboardLocationStandard ClipboardLocation = 0
	// ClipboardLocationSelection corresponds to the Zig tag selection.
	ClipboardLocationSelection ClipboardLocation = 1
	// ClipboardLocationPrimary corresponds to the Zig tag primary.
	ClipboardLocationPrimary ClipboardLocation = 2
)

var zigoClipboardLocationNames = [3]string{
	0: "standard",
	1: "selection",
	2: "primary",
}

// String returns the Zig tag name.
func (value ClipboardLocation) String() string {
	if value >= 0 && value <= 2 {
		return zigoClipboardLocationNames[uint64(value)]
	}
	return "ClipboardLocation(" + strconv.Itoa(int(value)) + ")"
}

// ParseClipboardLocation returns the ClipboardLocation named by text, which is a Zig tag name.
// Values outside the named constants are accepted in the ClipboardLocation(N) spelling String returns.
func ParseClipboardLocation(text string) (ClipboardLocation, error) {
	switch text {
	case "standard":
		return ClipboardLocationStandard, nil
	case "selection":
		return ClipboardLocationSelection, nil
	case "primary":
		return ClipboardLocationPrimary, nil
	}
	if strings.HasPrefix(text, "ClipboardLocation(") && strings.HasSuffix(text, ")") {
		if number, err := strconv.ParseInt(text[len("ClipboardLocation("):len(text)-1], 10, 32); err == nil {
			return ClipboardLocation(number), nil
		}
	}
	return 0, &EnumParseError{Type: "ClipboardLocation", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value ClipboardLocation) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseClipboardLocation.
func (value *ClipboardLocation) UnmarshalText(text []byte) error {
	parsed, err := ParseClipboardLocation(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// ClipboardLocationValues returns a fresh slice of known values in declaration order.
func ClipboardLocationValues() []ClipboardLocation {
	return []ClipboardLocation{
		ClipboardLocationStandard,
		ClipboardLocationSelection,
		ClipboardLocationPrimary,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value ClipboardLocation) IsKnown() bool {
	return value >= 0 && value <= 2
}

// ClipboardDenial represents the corresponding Zig enum.
type ClipboardDenial uint8

const (
	// ClipboardDenialDenied corresponds to the Zig tag denied.
	ClipboardDenialDenied ClipboardDenial = 0
	// ClipboardDenialUnsupported corresponds to the Zig tag unsupported.
	ClipboardDenialUnsupported ClipboardDenial = 1
	// ClipboardDenialBusy corresponds to the Zig tag busy.
	ClipboardDenialBusy ClipboardDenial = 2
	// ClipboardDenialIoError corresponds to the Zig tag io_error.
	ClipboardDenialIoError ClipboardDenial = 3
)

var zigoClipboardDenialNames = [4]string{
	0: "denied",
	1: "unsupported",
	2: "busy",
	3: "io_error",
}

// String returns the Zig tag name.
func (value ClipboardDenial) String() string {
	if value >= 0 && value <= 3 {
		return zigoClipboardDenialNames[uint64(value)]
	}
	return "ClipboardDenial(" + strconv.Itoa(int(value)) + ")"
}

// OSCCommand represents the corresponding Zig enum.
type OSCCommand uint8

const (
	// OSCCommandInvalid corresponds to the Zig tag invalid.
	OSCCommandInvalid OSCCommand = 0
	// OSCCommandChangeWindowTitle corresponds to the Zig tag change_window_title.
	OSCCommandChangeWindowTitle OSCCommand = 1
	// OSCCommandChangeWindowIcon corresponds to the Zig tag change_window_icon.
	OSCCommandChangeWindowIcon OSCCommand = 2
	// OSCCommandSemanticPrompt corresponds to the Zig tag semantic_prompt.
	OSCCommandSemanticPrompt OSCCommand = 3
	// OSCCommandClipboardContents corresponds to the Zig tag clipboard_contents.
	OSCCommandClipboardContents OSCCommand = 4
	// OSCCommandReportPwd corresponds to the Zig tag report_pwd.
	OSCCommandReportPwd OSCCommand = 5
	// OSCCommandMouseShape corresponds to the Zig tag mouse_shape.
	OSCCommandMouseShape OSCCommand = 6
	// OSCCommandColorOperation corresponds to the Zig tag color_operation.
	OSCCommandColorOperation OSCCommand = 7
	// OSCCommandKittyColorProtocol corresponds to the Zig tag kitty_color_protocol.
	OSCCommandKittyColorProtocol OSCCommand = 8
	// OSCCommandShowDesktopNotification corresponds to the Zig tag show_desktop_notification.
	OSCCommandShowDesktopNotification OSCCommand = 9
	// OSCCommandHyperlinkStart corresponds to the Zig tag hyperlink_start.
	OSCCommandHyperlinkStart OSCCommand = 10
	// OSCCommandHyperlinkEnd corresponds to the Zig tag hyperlink_end.
	OSCCommandHyperlinkEnd OSCCommand = 11
	// OSCCommandConemuSleep corresponds to the Zig tag conemu_sleep.
	OSCCommandConemuSleep OSCCommand = 12
	// OSCCommandConemuShowMessageBox corresponds to the Zig tag conemu_show_message_box.
	OSCCommandConemuShowMessageBox OSCCommand = 13
	// OSCCommandConemuChangeTabTitle corresponds to the Zig tag conemu_change_tab_title.
	OSCCommandConemuChangeTabTitle OSCCommand = 14
	// OSCCommandConemuProgressReport corresponds to the Zig tag conemu_progress_report.
	OSCCommandConemuProgressReport OSCCommand = 15
	// OSCCommandConemuWaitInput corresponds to the Zig tag conemu_wait_input.
	OSCCommandConemuWaitInput OSCCommand = 16
	// OSCCommandConemuGuimacro corresponds to the Zig tag conemu_guimacro.
	OSCCommandConemuGuimacro OSCCommand = 17
	// OSCCommandConemuRunProcess corresponds to the Zig tag conemu_run_process.
	OSCCommandConemuRunProcess OSCCommand = 18
	// OSCCommandConemuOutputEnvironmentVariable corresponds to the Zig tag conemu_output_environment_variable.
	OSCCommandConemuOutputEnvironmentVariable OSCCommand = 19
	// OSCCommandConemuXtermEmulation corresponds to the Zig tag conemu_xterm_emulation.
	OSCCommandConemuXtermEmulation OSCCommand = 20
	// OSCCommandConemuComment corresponds to the Zig tag conemu_comment.
	OSCCommandConemuComment OSCCommand = 21
	// OSCCommandKittyTextSizing corresponds to the Zig tag kitty_text_sizing.
	OSCCommandKittyTextSizing OSCCommand = 22
	// OSCCommandKittyClipboardProtocol corresponds to the Zig tag kitty_clipboard_protocol.
	OSCCommandKittyClipboardProtocol OSCCommand = 23
	// OSCCommandKittyDndProtocol corresponds to the Zig tag kitty_dnd_protocol.
	OSCCommandKittyDndProtocol OSCCommand = 24
	// OSCCommandContextSignal corresponds to the Zig tag context_signal.
	OSCCommandContextSignal OSCCommand = 25
	// OSCCommandKittyDesktopNotification corresponds to the Zig tag kitty_desktop_notification.
	OSCCommandKittyDesktopNotification OSCCommand = 26
)

var zigoOSCCommandNames = [27]string{
	0:  "invalid",
	1:  "change_window_title",
	2:  "change_window_icon",
	3:  "semantic_prompt",
	4:  "clipboard_contents",
	5:  "report_pwd",
	6:  "mouse_shape",
	7:  "color_operation",
	8:  "kitty_color_protocol",
	9:  "show_desktop_notification",
	10: "hyperlink_start",
	11: "hyperlink_end",
	12: "conemu_sleep",
	13: "conemu_show_message_box",
	14: "conemu_change_tab_title",
	15: "conemu_progress_report",
	16: "conemu_wait_input",
	17: "conemu_guimacro",
	18: "conemu_run_process",
	19: "conemu_output_environment_variable",
	20: "conemu_xterm_emulation",
	21: "conemu_comment",
	22: "kitty_text_sizing",
	23: "kitty_clipboard_protocol",
	24: "kitty_dnd_protocol",
	25: "context_signal",
	26: "kitty_desktop_notification",
}

// String returns the Zig tag name.
func (value OSCCommand) String() string {
	if value >= 0 && value <= 26 {
		return zigoOSCCommandNames[uint64(value)]
	}
	return "OSCCommand(" + strconv.Itoa(int(value)) + ")"
}

// ParseOSCCommand returns the OSCCommand named by text, which is a Zig tag name.
func ParseOSCCommand(text string) (OSCCommand, error) {
	switch text {
	case "invalid":
		return OSCCommandInvalid, nil
	case "change_window_title":
		return OSCCommandChangeWindowTitle, nil
	case "change_window_icon":
		return OSCCommandChangeWindowIcon, nil
	case "semantic_prompt":
		return OSCCommandSemanticPrompt, nil
	case "clipboard_contents":
		return OSCCommandClipboardContents, nil
	case "report_pwd":
		return OSCCommandReportPwd, nil
	case "mouse_shape":
		return OSCCommandMouseShape, nil
	case "color_operation":
		return OSCCommandColorOperation, nil
	case "kitty_color_protocol":
		return OSCCommandKittyColorProtocol, nil
	case "show_desktop_notification":
		return OSCCommandShowDesktopNotification, nil
	case "hyperlink_start":
		return OSCCommandHyperlinkStart, nil
	case "hyperlink_end":
		return OSCCommandHyperlinkEnd, nil
	case "conemu_sleep":
		return OSCCommandConemuSleep, nil
	case "conemu_show_message_box":
		return OSCCommandConemuShowMessageBox, nil
	case "conemu_change_tab_title":
		return OSCCommandConemuChangeTabTitle, nil
	case "conemu_progress_report":
		return OSCCommandConemuProgressReport, nil
	case "conemu_wait_input":
		return OSCCommandConemuWaitInput, nil
	case "conemu_guimacro":
		return OSCCommandConemuGuimacro, nil
	case "conemu_run_process":
		return OSCCommandConemuRunProcess, nil
	case "conemu_output_environment_variable":
		return OSCCommandConemuOutputEnvironmentVariable, nil
	case "conemu_xterm_emulation":
		return OSCCommandConemuXtermEmulation, nil
	case "conemu_comment":
		return OSCCommandConemuComment, nil
	case "kitty_text_sizing":
		return OSCCommandKittyTextSizing, nil
	case "kitty_clipboard_protocol":
		return OSCCommandKittyClipboardProtocol, nil
	case "kitty_dnd_protocol":
		return OSCCommandKittyDndProtocol, nil
	case "context_signal":
		return OSCCommandContextSignal, nil
	case "kitty_desktop_notification":
		return OSCCommandKittyDesktopNotification, nil
	}
	return 0, &EnumParseError{Type: "OSCCommand", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value OSCCommand) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseOSCCommand.
func (value *OSCCommand) UnmarshalText(text []byte) error {
	parsed, err := ParseOSCCommand(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// OSCTerminator represents the corresponding Zig enum.
type OSCTerminator uint8

const (
	// OSCTerminatorSt corresponds to the Zig tag st.
	OSCTerminatorSt OSCTerminator = 0
	// OSCTerminatorBel corresponds to the Zig tag bel.
	OSCTerminatorBel OSCTerminator = 1
)

var zigoOSCTerminatorNames = [2]string{
	0: "st",
	1: "bel",
}

// String returns the Zig tag name.
func (value OSCTerminator) String() string {
	if value >= 0 && value <= 1 {
		return zigoOSCTerminatorNames[uint64(value)]
	}
	return "OSCTerminator(" + strconv.Itoa(int(value)) + ")"
}

// ParseOSCTerminator returns the OSCTerminator named by text, which is a Zig tag name.
func ParseOSCTerminator(text string) (OSCTerminator, error) {
	switch text {
	case "st":
		return OSCTerminatorSt, nil
	case "bel":
		return OSCTerminatorBel, nil
	}
	return 0, &EnumParseError{Type: "OSCTerminator", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value OSCTerminator) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseOSCTerminator.
func (value *OSCTerminator) UnmarshalText(text []byte) error {
	parsed, err := ParseOSCTerminator(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// SemanticPromptAction represents the corresponding Zig enum.
type SemanticPromptAction uint8

const (
	// SemanticPromptActionFreshLine corresponds to the Zig tag fresh_line.
	SemanticPromptActionFreshLine SemanticPromptAction = 0
	// SemanticPromptActionFreshLineNewPrompt corresponds to the Zig tag fresh_line_new_prompt.
	SemanticPromptActionFreshLineNewPrompt SemanticPromptAction = 1
	// SemanticPromptActionNewCommand corresponds to the Zig tag new_command.
	SemanticPromptActionNewCommand SemanticPromptAction = 2
	// SemanticPromptActionPromptStart corresponds to the Zig tag prompt_start.
	SemanticPromptActionPromptStart SemanticPromptAction = 3
	// SemanticPromptActionEndPromptStartInput corresponds to the Zig tag end_prompt_start_input.
	SemanticPromptActionEndPromptStartInput SemanticPromptAction = 4
	// SemanticPromptActionEndPromptStartInputTerminateEol corresponds to the Zig tag end_prompt_start_input_terminate_eol.
	SemanticPromptActionEndPromptStartInputTerminateEol SemanticPromptAction = 5
	// SemanticPromptActionEndInputStartOutput corresponds to the Zig tag end_input_start_output.
	SemanticPromptActionEndInputStartOutput SemanticPromptAction = 6
	// SemanticPromptActionEndCommand corresponds to the Zig tag end_command.
	SemanticPromptActionEndCommand SemanticPromptAction = 7
)

var zigoSemanticPromptActionNames = [8]string{
	0: "fresh_line",
	1: "fresh_line_new_prompt",
	2: "new_command",
	3: "prompt_start",
	4: "end_prompt_start_input",
	5: "end_prompt_start_input_terminate_eol",
	6: "end_input_start_output",
	7: "end_command",
}

// String returns the Zig tag name.
func (value SemanticPromptAction) String() string {
	if value >= 0 && value <= 7 {
		return zigoSemanticPromptActionNames[uint64(value)]
	}
	return "SemanticPromptAction(" + strconv.Itoa(int(value)) + ")"
}

// ParseSemanticPromptAction returns the SemanticPromptAction named by text, which is a Zig tag name.
func ParseSemanticPromptAction(text string) (SemanticPromptAction, error) {
	switch text {
	case "fresh_line":
		return SemanticPromptActionFreshLine, nil
	case "fresh_line_new_prompt":
		return SemanticPromptActionFreshLineNewPrompt, nil
	case "new_command":
		return SemanticPromptActionNewCommand, nil
	case "prompt_start":
		return SemanticPromptActionPromptStart, nil
	case "end_prompt_start_input":
		return SemanticPromptActionEndPromptStartInput, nil
	case "end_prompt_start_input_terminate_eol":
		return SemanticPromptActionEndPromptStartInputTerminateEol, nil
	case "end_input_start_output":
		return SemanticPromptActionEndInputStartOutput, nil
	case "end_command":
		return SemanticPromptActionEndCommand, nil
	}
	return 0, &EnumParseError{Type: "SemanticPromptAction", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value SemanticPromptAction) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseSemanticPromptAction.
func (value *SemanticPromptAction) UnmarshalText(text []byte) error {
	parsed, err := ParseSemanticPromptAction(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// CellWidth represents the corresponding Zig enum.
type CellWidth uint8

const (
	// CellWidthNarrow corresponds to the Zig tag narrow.
	CellWidthNarrow CellWidth = 0
	// CellWidthWide corresponds to the Zig tag wide.
	CellWidthWide CellWidth = 1
	// CellWidthSpacerTail corresponds to the Zig tag spacer_tail.
	CellWidthSpacerTail CellWidth = 2
	// CellWidthSpacerHead corresponds to the Zig tag spacer_head.
	CellWidthSpacerHead CellWidth = 3
)

var zigoCellWidthNames = [4]string{
	0: "narrow",
	1: "wide",
	2: "spacer_tail",
	3: "spacer_head",
}

// String returns the Zig tag name.
func (value CellWidth) String() string {
	if value >= 0 && value <= 3 {
		return zigoCellWidthNames[uint64(value)]
	}
	return "CellWidth(" + strconv.Itoa(int(value)) + ")"
}

// RenderDirty represents the corresponding Zig enum.
type RenderDirty uint8

const (
	// RenderDirtyClean corresponds to the Zig tag clean.
	RenderDirtyClean RenderDirty = 0
	// RenderDirtyPartial corresponds to the Zig tag partial.
	RenderDirtyPartial RenderDirty = 1
	// RenderDirtyFull corresponds to the Zig tag full.
	RenderDirtyFull RenderDirty = 2
)

var zigoRenderDirtyNames = [3]string{
	0: "clean",
	1: "partial",
	2: "full",
}

// String returns the Zig tag name.
func (value RenderDirty) String() string {
	if value >= 0 && value <= 2 {
		return zigoRenderDirtyNames[uint64(value)]
	}
	return "RenderDirty(" + strconv.Itoa(int(value)) + ")"
}

// KittyLayer represents the corresponding Zig enum.
type KittyLayer uint8

const (
	// KittyLayerBelowBg corresponds to the Zig tag below_bg.
	KittyLayerBelowBg KittyLayer = 0
	// KittyLayerBelowText corresponds to the Zig tag below_text.
	KittyLayerBelowText KittyLayer = 1
	// KittyLayerAboveText corresponds to the Zig tag above_text.
	KittyLayerAboveText KittyLayer = 2
)

var zigoKittyLayerNames = [3]string{
	0: "below_bg",
	1: "below_text",
	2: "above_text",
}

// String returns the Zig tag name.
func (value KittyLayer) String() string {
	if value >= 0 && value <= 2 {
		return zigoKittyLayerNames[uint64(value)]
	}
	return "KittyLayer(" + strconv.Itoa(int(value)) + ")"
}

// ParseKittyLayer returns the KittyLayer named by text, which is a Zig tag name.
func ParseKittyLayer(text string) (KittyLayer, error) {
	switch text {
	case "below_bg":
		return KittyLayerBelowBg, nil
	case "below_text":
		return KittyLayerBelowText, nil
	case "above_text":
		return KittyLayerAboveText, nil
	}
	return 0, &EnumParseError{Type: "KittyLayer", Text: text}
}

// MarshalText implements encoding.TextMarshaler with the String spelling.
func (value KittyLayer) MarshalText() ([]byte, error) {
	return []byte(value.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler with ParseKittyLayer.
func (value *KittyLayer) UnmarshalText(text []byte) error {
	parsed, err := ParseKittyLayer(string(text))
	if err != nil {
		return err
	}
	*value = parsed
	return nil
}

// KittyFormat represents the corresponding Zig enum.
type KittyFormat uint8

const (
	// KittyFormatRgb corresponds to the Zig tag rgb.
	KittyFormatRgb KittyFormat = 0
	// KittyFormatRgba corresponds to the Zig tag rgba.
	KittyFormatRgba KittyFormat = 1
	// KittyFormatPng corresponds to the Zig tag png.
	KittyFormatPng KittyFormat = 2
	// KittyFormatGrayAlpha corresponds to the Zig tag gray_alpha.
	KittyFormatGrayAlpha KittyFormat = 3
	// KittyFormatGray corresponds to the Zig tag gray.
	KittyFormatGray KittyFormat = 4
)

var zigoKittyFormatNames = [5]string{
	0: "rgb",
	1: "rgba",
	2: "png",
	3: "gray_alpha",
	4: "gray",
}

// String returns the Zig tag name.
func (value KittyFormat) String() string {
	if value >= 0 && value <= 4 {
		return zigoKittyFormatNames[uint64(value)]
	}
	return "KittyFormat(" + strconv.Itoa(int(value)) + ")"
}

// KittyCompression represents the corresponding Zig enum.
type KittyCompression uint8

const (
	// KittyCompressionNone corresponds to the Zig tag none.
	KittyCompressionNone KittyCompression = 0
	// KittyCompressionZlibDeflate corresponds to the Zig tag zlib_deflate.
	KittyCompressionZlibDeflate KittyCompression = 1
)

var zigoKittyCompressionNames = [2]string{
	0: "none",
	1: "zlib_deflate",
}

// String returns the Zig tag name.
func (value KittyCompression) String() string {
	if value >= 0 && value <= 1 {
		return zigoKittyCompressionNames[uint64(value)]
	}
	return "KittyCompression(" + strconv.Itoa(int(value)) + ")"
}
