// Code generated by zigo. DO NOT EDIT.

package gostty

import "io"

// SnapshotSource is a decoded snapshot: either a Snapshot, restored in one
// call, or a SnapshotDecoder, which restores the screen first and the
// scrollback a page at a time. Close it when the restore is done.
// SnapshotSource is implemented by *Snapshot and *SnapshotDecoder.
type SnapshotSource interface {
	// RestoreInto: Replace `term` with the terminal the snapshot holds: its size, screens,
	// scrollback, modes and colors. The snapshot gives its terminal up once;
	// a second call fails. Streams on `term` keep pointing at it, but their
	// parser state belongs to the old contents, so open a new stream and feed
	// it `continuation` before any new input.
	//
	// zigo allows one constructor per handle and `newTerminal` is it, so a
	// restore fills a terminal the caller made rather than returning one.
	RestoreInto(term *Terminal) error
	// Continuation: The bytes of the unfinished sequence the snapshot was taken in, empty
	// when the stream was at ground. Feed them to the restored terminal's
	// stream before any new input.
	Continuation() ([]byte, error)
	io.Closer
}

var _ SnapshotSource = (*Snapshot)(nil)
var _ SnapshotSource = (*SnapshotDecoder)(nil)
