// Code generated by zigo. DO NOT EDIT.

package sys

import (
	"runtime/cgo"
	"sync/atomic"
	"unsafe"

	lifecycle "github.com/ironpark/gostty/internal/lifecycle"
	"github.com/ironpark/gostty/internal/raw"
)

type zigoHandle = lifecycle.Handle

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return lifecycle.CheckedPointer(operation, value)
}
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	return lifecycle.PoisonAfterPanic(err, handles...)
}

// Handler is the Go callback signature accepted by the generated binding.
// Reentrancy: allowed; the callback may re-enter the binding while it is running.
// Thread: caller; the callback runs on the thread that initiated the native call.
type Handler func(uint)

var zigoActiveCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func zigoNewHandlerHandle(value Handler) zigoCallbackHandle {
	stored := (func(uint))(value)
	handle := cgo.NewHandle(&raw.CallbackState{Fn: stored})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoDeleteCallbackHandle(handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	handle.Delete()
	zigoActiveCallbackHandles.Add(-1)
}

func zigoActiveCallbackHandleCount() int64 { return zigoActiveCallbackHandles.Load() }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}
