// Code generated by zigo. DO NOT EDIT.
// This machine-local file is intentionally excluded from go-check.

package raw

/*
#cgo linux,arm64 LDFLAGS: ${SRCDIR}/../../libs/linux_arm64/libgostty_zigo.a ${SRCDIR}/../../libs/linux_arm64/libsimdutf.a ${SRCDIR}/../../libs/linux_arm64/libhighway.a
#cgo linux,amd64 LDFLAGS: ${SRCDIR}/../../libs/linux_amd64/libgostty_zigo.a ${SRCDIR}/../../libs/linux_amd64/libsimdutf.a ${SRCDIR}/../../libs/linux_amd64/libhighway.a
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/../../libs/darwin_arm64/libgostty_zigo.a ${SRCDIR}/../../libs/darwin_arm64/libsimdutf.a ${SRCDIR}/../../libs/darwin_arm64/libhighway.a
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/../../libs/darwin_amd64/libgostty_zigo.a ${SRCDIR}/../../libs/darwin_amd64/libsimdutf.a ${SRCDIR}/../../libs/darwin_amd64/libhighway.a
#cgo windows,arm64 LDFLAGS: ${SRCDIR}/../../libs/windows_arm64/libgostty_zigo.a ${SRCDIR}/../../libs/windows_arm64/libsimdutf.a ${SRCDIR}/../../libs/windows_arm64/libhighway.a
#cgo windows,amd64 LDFLAGS: ${SRCDIR}/../../libs/windows_amd64/libgostty_zigo.a ${SRCDIR}/../../libs/windows_amd64/libsimdutf.a ${SRCDIR}/../../libs/windows_amd64/libhighway.a
*/
import "C"
