// Code generated by make generate. DO NOT EDIT.
// This machine-local file is intentionally excluded from go-check.
//go:build darwin && amd64

package raw

/*
#cgo LDFLAGS: ${SRCDIR}/../../libs/x86_64-macos_libgostty_zigo.a ${SRCDIR}/../../libs/x86_64-macos_libsimdutf.a ${SRCDIR}/../../libs/x86_64-macos_libhighway.a
*/
import "C"
