// Code generated by make generate. DO NOT EDIT.
// This machine-local file is intentionally excluded from go-check.
//go:build linux && arm64

package raw

/*
#cgo LDFLAGS: ${SRCDIR}/../../libs/aarch64-linux-gnu_libgostty_zigo.a ${SRCDIR}/../../libs/aarch64-linux-gnu_libsimdutf.a ${SRCDIR}/../../libs/aarch64-linux-gnu_libhighway.a
*/
import "C"
