// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_gostty_H
#define ZIGO_gostty_H

#include <stddef.h>
#include <stdint.h>

typedef struct zg_terminal zg_terminal;
typedef struct zg_stream zg_stream;
typedef struct zg_screen zg_screen;
typedef struct zg_search zg_search;
typedef struct zg_key_event zg_key_event;
typedef struct zg_mouse_event zg_mouse_event;
typedef uint8_t zg_cursor_style;
#define ZG_CURSOR_STYLE_BAR 0
#define ZG_CURSOR_STYLE_BLOCK 1
#define ZG_CURSOR_STYLE_UNDERLINE 2
#define ZG_CURSOR_STYLE_BLOCK_HOLLOW 3

typedef uint8_t zg_cursor_style_req;
#define ZG_CURSOR_STYLE_REQ_DEFAULT 0
#define ZG_CURSOR_STYLE_REQ_BLINKING_BLOCK 1
#define ZG_CURSOR_STYLE_REQ_STEADY_BLOCK 2
#define ZG_CURSOR_STYLE_REQ_BLINKING_UNDERLINE 3
#define ZG_CURSOR_STYLE_REQ_STEADY_UNDERLINE 4
#define ZG_CURSOR_STYLE_REQ_BLINKING_BAR 5
#define ZG_CURSOR_STYLE_REQ_STEADY_BAR 6

typedef uint8_t zg_erase_display;
#define ZG_ERASE_DISPLAY_BELOW 0
#define ZG_ERASE_DISPLAY_ABOVE 1
#define ZG_ERASE_DISPLAY_COMPLETE 2
#define ZG_ERASE_DISPLAY_SCROLLBACK 3
#define ZG_ERASE_DISPLAY_SCROLL_COMPLETE 22

typedef uint8_t zg_erase_line;
#define ZG_ERASE_LINE_RIGHT 0
#define ZG_ERASE_LINE_LEFT 1
#define ZG_ERASE_LINE_COMPLETE 2
#define ZG_ERASE_LINE_RIGHT_UNLESS_PENDING_WRAP 4

typedef uint8_t zg_tab_clear;
#define ZG_TAB_CLEAR_CURRENT 0
#define ZG_TAB_CLEAR_ALL 3

typedef uint8_t zg_protected_mode;
#define ZG_PROTECTED_MODE_OFF 0
#define ZG_PROTECTED_MODE_ISO 1
#define ZG_PROTECTED_MODE_DEC 2

typedef uint8_t zg_screen_key;
#define ZG_SCREEN_KEY_PRIMARY 0
#define ZG_SCREEN_KEY_ALTERNATE 1

typedef uint8_t zg_stream_event;
#define ZG_STREAM_EVENT_BELL 0
#define ZG_STREAM_EVENT_TITLE_CHANGED 1
#define ZG_STREAM_EVENT_PWD_CHANGED 2
#define ZG_STREAM_EVENT_DESKTOP_NOTIFICATION 3
#define ZG_STREAM_EVENT_PROGRESS_REPORT 4

typedef uint8_t zg_progress_state;
#define ZG_PROGRESS_STATE_REMOVE 0
#define ZG_PROGRESS_STATE_SET 1
#define ZG_PROGRESS_STATE_ERROR 2
#define ZG_PROGRESS_STATE_INDETERMINATE 3
#define ZG_PROGRESS_STATE_PAUSE 4

typedef int32_t zg_clipboard_location;
#define ZG_CLIPBOARD_LOCATION_STANDARD 0
#define ZG_CLIPBOARD_LOCATION_SELECTION 1
#define ZG_CLIPBOARD_LOCATION_PRIMARY 2

typedef uint8_t zg_clipboard_denial;
#define ZG_CLIPBOARD_DENIAL_DENIED 0
#define ZG_CLIPBOARD_DENIAL_UNSUPPORTED 1
#define ZG_CLIPBOARD_DENIAL_BUSY 2
#define ZG_CLIPBOARD_DENIAL_IO_ERROR 3

typedef uint8_t zg_underline;
#define ZG_UNDERLINE_NONE 0
#define ZG_UNDERLINE_SINGLE 1
#define ZG_UNDERLINE_DOUBLE 2
#define ZG_UNDERLINE_CURLY 3
#define ZG_UNDERLINE_DOTTED 4
#define ZG_UNDERLINE_DASHED 5

typedef uint8_t zg_color_name;
#define ZG_COLOR_NAME_BLACK 0
#define ZG_COLOR_NAME_RED 1
#define ZG_COLOR_NAME_GREEN 2
#define ZG_COLOR_NAME_YELLOW 3
#define ZG_COLOR_NAME_BLUE 4
#define ZG_COLOR_NAME_MAGENTA 5
#define ZG_COLOR_NAME_CYAN 6
#define ZG_COLOR_NAME_WHITE 7
#define ZG_COLOR_NAME_BRIGHT_BLACK 8
#define ZG_COLOR_NAME_BRIGHT_RED 9
#define ZG_COLOR_NAME_BRIGHT_GREEN 10
#define ZG_COLOR_NAME_BRIGHT_YELLOW 11
#define ZG_COLOR_NAME_BRIGHT_BLUE 12
#define ZG_COLOR_NAME_BRIGHT_MAGENTA 13
#define ZG_COLOR_NAME_BRIGHT_CYAN 14
#define ZG_COLOR_NAME_BRIGHT_WHITE 15

typedef uint8_t zg_attribute_tag;
#define ZG_ATTRIBUTE_TAG_UNSET 0
#define ZG_ATTRIBUTE_TAG_BOLD 1
#define ZG_ATTRIBUTE_TAG_RESET_BOLD 2
#define ZG_ATTRIBUTE_TAG_ITALIC 3
#define ZG_ATTRIBUTE_TAG_RESET_ITALIC 4
#define ZG_ATTRIBUTE_TAG_FAINT 5
#define ZG_ATTRIBUTE_TAG_UNDERLINE 6
#define ZG_ATTRIBUTE_TAG_UNDERLINE_COLOR_RGB 7
#define ZG_ATTRIBUTE_TAG_UNDERLINE_COLOR_256 8
#define ZG_ATTRIBUTE_TAG_RESET_UNDERLINE_COLOR 9
#define ZG_ATTRIBUTE_TAG_OVERLINE 10
#define ZG_ATTRIBUTE_TAG_RESET_OVERLINE 11
#define ZG_ATTRIBUTE_TAG_BLINK 12
#define ZG_ATTRIBUTE_TAG_RESET_BLINK 13
#define ZG_ATTRIBUTE_TAG_INVERSE 14
#define ZG_ATTRIBUTE_TAG_RESET_INVERSE 15
#define ZG_ATTRIBUTE_TAG_INVISIBLE 16
#define ZG_ATTRIBUTE_TAG_RESET_INVISIBLE 17
#define ZG_ATTRIBUTE_TAG_STRIKETHROUGH 18
#define ZG_ATTRIBUTE_TAG_RESET_STRIKETHROUGH 19
#define ZG_ATTRIBUTE_TAG_DIRECT_COLOR_FG 20
#define ZG_ATTRIBUTE_TAG_DIRECT_COLOR_BG 21
#define ZG_ATTRIBUTE_TAG_COLOR_256_FG 22
#define ZG_ATTRIBUTE_TAG_COLOR_256_BG 23
#define ZG_ATTRIBUTE_TAG_NAMED_FG 24
#define ZG_ATTRIBUTE_TAG_NAMED_BG 25
#define ZG_ATTRIBUTE_TAG_BRIGHT_NAMED_FG 26
#define ZG_ATTRIBUTE_TAG_BRIGHT_NAMED_BG 27
#define ZG_ATTRIBUTE_TAG_RESET_FG 28
#define ZG_ATTRIBUTE_TAG_RESET_BG 29

typedef uint8_t zg_search_direction;
#define ZG_SEARCH_DIRECTION_NEXT 0
#define ZG_SEARCH_DIRECTION_PREV 1

typedef int32_t zg_key;
#define ZG_KEY_UNIDENTIFIED 0
#define ZG_KEY_BACKQUOTE 1
#define ZG_KEY_BACKSLASH 2
#define ZG_KEY_BRACKET_LEFT 3
#define ZG_KEY_BRACKET_RIGHT 4
#define ZG_KEY_COMMA 5
#define ZG_KEY_DIGIT_0 6
#define ZG_KEY_DIGIT_1 7
#define ZG_KEY_DIGIT_2 8
#define ZG_KEY_DIGIT_3 9
#define ZG_KEY_DIGIT_4 10
#define ZG_KEY_DIGIT_5 11
#define ZG_KEY_DIGIT_6 12
#define ZG_KEY_DIGIT_7 13
#define ZG_KEY_DIGIT_8 14
#define ZG_KEY_DIGIT_9 15
#define ZG_KEY_EQUAL 16
#define ZG_KEY_INTL_BACKSLASH 17
#define ZG_KEY_INTL_RO 18
#define ZG_KEY_INTL_YEN 19
#define ZG_KEY_KEY_A 20
#define ZG_KEY_KEY_B 21
#define ZG_KEY_KEY_C 22
#define ZG_KEY_KEY_D 23
#define ZG_KEY_KEY_E 24
#define ZG_KEY_KEY_F 25
#define ZG_KEY_KEY_G 26
#define ZG_KEY_KEY_H 27
#define ZG_KEY_KEY_I 28
#define ZG_KEY_KEY_J 29
#define ZG_KEY_KEY_K 30
#define ZG_KEY_KEY_L 31
#define ZG_KEY_KEY_M 32
#define ZG_KEY_KEY_N 33
#define ZG_KEY_KEY_O 34
#define ZG_KEY_KEY_P 35
#define ZG_KEY_KEY_Q 36
#define ZG_KEY_KEY_R 37
#define ZG_KEY_KEY_S 38
#define ZG_KEY_KEY_T 39
#define ZG_KEY_KEY_U 40
#define ZG_KEY_KEY_V 41
#define ZG_KEY_KEY_W 42
#define ZG_KEY_KEY_X 43
#define ZG_KEY_KEY_Y 44
#define ZG_KEY_KEY_Z 45
#define ZG_KEY_MINUS 46
#define ZG_KEY_PERIOD 47
#define ZG_KEY_QUOTE 48
#define ZG_KEY_SEMICOLON 49
#define ZG_KEY_SLASH 50
#define ZG_KEY_ALT_LEFT 51
#define ZG_KEY_ALT_RIGHT 52
#define ZG_KEY_BACKSPACE 53
#define ZG_KEY_CAPS_LOCK 54
#define ZG_KEY_CONTEXT_MENU 55
#define ZG_KEY_CONTROL_LEFT 56
#define ZG_KEY_CONTROL_RIGHT 57
#define ZG_KEY_ENTER 58
#define ZG_KEY_META_LEFT 59
#define ZG_KEY_META_RIGHT 60
#define ZG_KEY_SHIFT_LEFT 61
#define ZG_KEY_SHIFT_RIGHT 62
#define ZG_KEY_SPACE 63
#define ZG_KEY_TAB 64
#define ZG_KEY_CONVERT 65
#define ZG_KEY_KANA_MODE 66
#define ZG_KEY_NON_CONVERT 67
#define ZG_KEY_DELETE 68
#define ZG_KEY_END 69
#define ZG_KEY_HELP 70
#define ZG_KEY_HOME 71
#define ZG_KEY_INSERT 72
#define ZG_KEY_PAGE_DOWN 73
#define ZG_KEY_PAGE_UP 74
#define ZG_KEY_ARROW_DOWN 75
#define ZG_KEY_ARROW_LEFT 76
#define ZG_KEY_ARROW_RIGHT 77
#define ZG_KEY_ARROW_UP 78
#define ZG_KEY_NUM_LOCK 79
#define ZG_KEY_NUMPAD_0 80
#define ZG_KEY_NUMPAD_1 81
#define ZG_KEY_NUMPAD_2 82
#define ZG_KEY_NUMPAD_3 83
#define ZG_KEY_NUMPAD_4 84
#define ZG_KEY_NUMPAD_5 85
#define ZG_KEY_NUMPAD_6 86
#define ZG_KEY_NUMPAD_7 87
#define ZG_KEY_NUMPAD_8 88
#define ZG_KEY_NUMPAD_9 89
#define ZG_KEY_NUMPAD_ADD 90
#define ZG_KEY_NUMPAD_BACKSPACE 91
#define ZG_KEY_NUMPAD_CLEAR 92
#define ZG_KEY_NUMPAD_CLEAR_ENTRY 93
#define ZG_KEY_NUMPAD_COMMA 94
#define ZG_KEY_NUMPAD_DECIMAL 95
#define ZG_KEY_NUMPAD_DIVIDE 96
#define ZG_KEY_NUMPAD_ENTER 97
#define ZG_KEY_NUMPAD_EQUAL 98
#define ZG_KEY_NUMPAD_MEMORY_ADD 99
#define ZG_KEY_NUMPAD_MEMORY_CLEAR 100
#define ZG_KEY_NUMPAD_MEMORY_RECALL 101
#define ZG_KEY_NUMPAD_MEMORY_STORE 102
#define ZG_KEY_NUMPAD_MEMORY_SUBTRACT 103
#define ZG_KEY_NUMPAD_MULTIPLY 104
#define ZG_KEY_NUMPAD_PAREN_LEFT 105
#define ZG_KEY_NUMPAD_PAREN_RIGHT 106
#define ZG_KEY_NUMPAD_SUBTRACT 107
#define ZG_KEY_NUMPAD_SEPARATOR 108
#define ZG_KEY_NUMPAD_UP 109
#define ZG_KEY_NUMPAD_DOWN 110
#define ZG_KEY_NUMPAD_RIGHT 111
#define ZG_KEY_NUMPAD_LEFT 112
#define ZG_KEY_NUMPAD_BEGIN 113
#define ZG_KEY_NUMPAD_HOME 114
#define ZG_KEY_NUMPAD_END 115
#define ZG_KEY_NUMPAD_INSERT 116
#define ZG_KEY_NUMPAD_DELETE 117
#define ZG_KEY_NUMPAD_PAGE_UP 118
#define ZG_KEY_NUMPAD_PAGE_DOWN 119
#define ZG_KEY_ESCAPE 120
#define ZG_KEY_F1 121
#define ZG_KEY_F2 122
#define ZG_KEY_F3 123
#define ZG_KEY_F4 124
#define ZG_KEY_F5 125
#define ZG_KEY_F6 126
#define ZG_KEY_F7 127
#define ZG_KEY_F8 128
#define ZG_KEY_F9 129
#define ZG_KEY_F10 130
#define ZG_KEY_F11 131
#define ZG_KEY_F12 132
#define ZG_KEY_F13 133
#define ZG_KEY_F14 134
#define ZG_KEY_F15 135
#define ZG_KEY_F16 136
#define ZG_KEY_F17 137
#define ZG_KEY_F18 138
#define ZG_KEY_F19 139
#define ZG_KEY_F20 140
#define ZG_KEY_F21 141
#define ZG_KEY_F22 142
#define ZG_KEY_F23 143
#define ZG_KEY_F24 144
#define ZG_KEY_F25 145
#define ZG_KEY_FN 146
#define ZG_KEY_FN_LOCK 147
#define ZG_KEY_PRINT_SCREEN 148
#define ZG_KEY_SCROLL_LOCK 149
#define ZG_KEY_PAUSE 150
#define ZG_KEY_BROWSER_BACK 151
#define ZG_KEY_BROWSER_FAVORITES 152
#define ZG_KEY_BROWSER_FORWARD 153
#define ZG_KEY_BROWSER_HOME 154
#define ZG_KEY_BROWSER_REFRESH 155
#define ZG_KEY_BROWSER_SEARCH 156
#define ZG_KEY_BROWSER_STOP 157
#define ZG_KEY_EJECT 158
#define ZG_KEY_LAUNCH_APP_1 159
#define ZG_KEY_LAUNCH_APP_2 160
#define ZG_KEY_LAUNCH_MAIL 161
#define ZG_KEY_MEDIA_PLAY_PAUSE 162
#define ZG_KEY_MEDIA_SELECT 163
#define ZG_KEY_MEDIA_STOP 164
#define ZG_KEY_MEDIA_TRACK_NEXT 165
#define ZG_KEY_MEDIA_TRACK_PREVIOUS 166
#define ZG_KEY_POWER 167
#define ZG_KEY_SLEEP 168
#define ZG_KEY_AUDIO_VOLUME_DOWN 169
#define ZG_KEY_AUDIO_VOLUME_MUTE 170
#define ZG_KEY_AUDIO_VOLUME_UP 171
#define ZG_KEY_WAKE_UP 172
#define ZG_KEY_COPY 173
#define ZG_KEY_CUT 174
#define ZG_KEY_PASTE 175

typedef int32_t zg_key_action;
#define ZG_KEY_ACTION_RELEASE 0
#define ZG_KEY_ACTION_PRESS 1
#define ZG_KEY_ACTION_REPEAT 2

typedef uint8_t zg_key_mod;
#define ZG_KEY_MOD_SHIFT 0
#define ZG_KEY_MOD_CTRL 1
#define ZG_KEY_MOD_ALT 2
#define ZG_KEY_MOD_SUPER 3
#define ZG_KEY_MOD_CAPS_LOCK 4
#define ZG_KEY_MOD_NUM_LOCK 5

typedef uint8_t zg_focus_event;
#define ZG_FOCUS_EVENT_GAINED 0
#define ZG_FOCUS_EVENT_LOST 1

typedef int32_t zg_mouse_action;
#define ZG_MOUSE_ACTION_PRESS 0
#define ZG_MOUSE_ACTION_RELEASE 1
#define ZG_MOUSE_ACTION_MOTION 2

typedef int32_t zg_mouse_button;
#define ZG_MOUSE_BUTTON_UNKNOWN 0
#define ZG_MOUSE_BUTTON_LEFT 1
#define ZG_MOUSE_BUTTON_RIGHT 2
#define ZG_MOUSE_BUTTON_MIDDLE 3
#define ZG_MOUSE_BUTTON_FOUR 4
#define ZG_MOUSE_BUTTON_FIVE 5
#define ZG_MOUSE_BUTTON_SIX 6
#define ZG_MOUSE_BUTTON_SEVEN 7
#define ZG_MOUSE_BUTTON_EIGHT 8
#define ZG_MOUSE_BUTTON_NINE 9
#define ZG_MOUSE_BUTTON_TEN 10
#define ZG_MOUSE_BUTTON_ELEVEN 11

typedef uint8_t zg_charset;
#define ZG_CHARSET_UTF8 0
#define ZG_CHARSET_ASCII 1
#define ZG_CHARSET_BRITISH 2
#define ZG_CHARSET_DEC_SPECIAL 3

typedef uint8_t zg_charset_slot;
#define ZG_CHARSET_SLOT_G0 0
#define ZG_CHARSET_SLOT_G1 1
#define ZG_CHARSET_SLOT_G2 2
#define ZG_CHARSET_SLOT_G3 3

typedef uint8_t zg_charset_active_slot;
#define ZG_CHARSET_ACTIVE_SLOT_GL 0
#define ZG_CHARSET_ACTIVE_SLOT_GR 1

typedef uint8_t zg_deccolm_mode;
#define ZG_DECCOLM_MODE_80_COLS 0
#define ZG_DECCOLM_MODE_132_COLS 1

typedef uint8_t zg_scroll_viewport_tag;
#define ZG_SCROLL_VIEWPORT_TAG_TOP 0
#define ZG_SCROLL_VIEWPORT_TAG_BOTTOM 1
#define ZG_SCROLL_VIEWPORT_TAG_DELTA 2
#define ZG_SCROLL_VIEWPORT_TAG_ROW 3

typedef struct zg_render_state zg_render_state;
typedef uint8_t zg_cell_width;
#define ZG_CELL_WIDTH_NARROW 0
#define ZG_CELL_WIDTH_WIDE 1
#define ZG_CELL_WIDTH_SPACER_TAIL 2
#define ZG_CELL_WIDTH_SPACER_HEAD 3

typedef struct zg_kitty_images zg_kitty_images;
typedef uint8_t zg_kitty_format;
#define ZG_KITTY_FORMAT_RGB 0
#define ZG_KITTY_FORMAT_RGBA 1
#define ZG_KITTY_FORMAT_PNG 2
#define ZG_KITTY_FORMAT_GRAY_ALPHA 3
#define ZG_KITTY_FORMAT_GRAY 4

typedef uint8_t zg_kitty_compression;
#define ZG_KITTY_COMPRESSION_NONE 0
#define ZG_KITTY_COMPRESSION_ZLIB_DEFLATE 1

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

typedef struct zg_render_size {
    uint32_t screen_width;
    uint32_t screen_height;
    uint32_t cell_width;
    uint32_t cell_height;
    uint32_t padding_top;
    uint32_t padding_bottom;
    uint32_t padding_right;
    uint32_t padding_left;
} zg_render_size;

typedef struct zg_render_cell {
    uint32_t codepoint;
    uint32_t fg;
    uint32_t bg;
    uint32_t flags;
} zg_render_cell;

typedef struct zg_kitty_placement {
    uint32_t image_id;
    uint32_t placement_id;
    int32_t viewport_col;
    int32_t viewport_row;
    uint32_t x_offset;
    uint32_t y_offset;
    uint32_t pixel_width;
    uint32_t pixel_height;
    uint32_t grid_cols;
    uint32_t grid_rows;
    uint32_t source_x;
    uint32_t source_y;
    uint32_t source_width;
    uint32_t source_height;
    int32_t z;
} zg_kitty_placement;

typedef struct zg_kitty_image {
    uint64_t generation;
    uint64_t data_len;
    uint32_t width;
    uint32_t height;
    uint8_t format;
    uint8_t compression;
    uint16_t _pad;
} zg_kitty_image;

ZIGO_EXPORT int32_t zg_terminal_cols(const zg_terminal * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_rows(const zg_terminal * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_cursor_x(const zg_terminal * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_cursor_y(const zg_terminal * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_cursor_style(const zg_terminal * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_unicode_codepoint_width(uint32_t p0, uint8_t * out_result);
ZIGO_EXPORT uint8_t zg_grapheme_width(const uint32_t * cps_ptr, size_t cps_len);
ZIGO_EXPORT int32_t zg_new_key_event(zg_key_event * * out_result);
ZIGO_EXPORT int32_t zg_key_event_free_key_event(zg_key_event * self);
ZIGO_EXPORT int32_t zg_key_event_reset(zg_key_event * self);
ZIGO_EXPORT int32_t zg_key_event_set_action(zg_key_event * self, int32_t action);
ZIGO_EXPORT int32_t zg_key_event_set_key(zg_key_event * self, int32_t key);
ZIGO_EXPORT int32_t zg_key_event_set_mod(zg_key_event * self, uint8_t mod, uint8_t value);
ZIGO_EXPORT int32_t zg_key_event_set_consumed_mod(zg_key_event * self, uint8_t mod, uint8_t value);
ZIGO_EXPORT int32_t zg_key_event_set_composing(zg_key_event * self, uint8_t composing);
ZIGO_EXPORT int32_t zg_key_event_set_utf8(zg_key_event * self, const uint8_t * text_ptr, size_t text_len);
ZIGO_EXPORT int32_t zg_key_event_set_unshifted_codepoint(zg_key_event * self, uint32_t cp);
ZIGO_EXPORT int32_t zg_encode_key(size_t writer_userdata, const zg_terminal * terminal, const zg_key_event * event);
ZIGO_EXPORT int32_t zg_new_mouse_event(zg_mouse_event * * out_result);
ZIGO_EXPORT int32_t zg_mouse_event_free_mouse_event(zg_mouse_event * self);
ZIGO_EXPORT int32_t zg_mouse_event_reset(zg_mouse_event * self);
ZIGO_EXPORT int32_t zg_mouse_event_set_action(zg_mouse_event * self, int32_t action);
ZIGO_EXPORT int32_t zg_mouse_event_set_button(zg_mouse_event * self, int32_t button);
ZIGO_EXPORT int32_t zg_mouse_event_clear_button(zg_mouse_event * self);
ZIGO_EXPORT int32_t zg_mouse_event_set_mod(zg_mouse_event * self, uint8_t mod, uint8_t value);
ZIGO_EXPORT int32_t zg_mouse_event_set_position(zg_mouse_event * self, float x, float y);
ZIGO_EXPORT int32_t zg_encode_mouse(size_t writer_userdata, const zg_terminal * terminal, const zg_mouse_event * event, const zg_render_size * size, uint8_t any_button_pressed);
ZIGO_EXPORT int32_t zg_encode_focus(size_t writer_userdata, uint8_t event);
ZIGO_EXPORT uint8_t zg_is_safe_paste(const uint8_t * data_ptr, size_t data_len);
ZIGO_EXPORT int32_t zg_encode_paste(size_t writer_userdata, const zg_terminal * terminal, const uint8_t * data_ptr, size_t data_len);
ZIGO_EXPORT int32_t zg_terminal_new_terminal(uint16_t cols, uint16_t rows, zg_terminal * * out_result);
ZIGO_EXPORT int32_t zg_terminal_deinit(zg_terminal * self);
ZIGO_EXPORT void zg_free_string(const uint8_t * str_ptr, size_t str_len);
ZIGO_EXPORT int32_t zg_terminal_new_stream(zg_terminal * self, size_t continuation_max_bytes, zg_stream * * out_result);
ZIGO_EXPORT int32_t zg_stream_free_stream(zg_stream * self);
ZIGO_EXPORT int32_t zg_stream_feed(zg_stream * self, const uint8_t * bytes_ptr, size_t bytes_len);
ZIGO_EXPORT int32_t zg_stream_failed(zg_stream * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_next_event(zg_stream * self, uint8_t * out_result_has, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_event_title(zg_stream * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_event_body(zg_stream * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_event_progress_state(zg_stream * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_event_progress(zg_stream * self, uint8_t * out_result_has, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_on_clipboard_write_request(zg_stream * self, size_t userdata);
ZIGO_EXPORT int32_t zg_stream_on_clipboard_read_request(zg_stream * self, size_t userdata);
ZIGO_EXPORT int32_t zg_stream_clipboard_location(zg_stream * self, int32_t * out_result);
ZIGO_EXPORT int32_t zg_stream_clipboard_name(zg_stream * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_clipboard_granted(zg_stream * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_clipboard_can_remember(zg_stream * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_clipboard_content_count(zg_stream * self, size_t * out_result);
ZIGO_EXPORT int32_t zg_stream_clipboard_content_mime(zg_stream * self, size_t index, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_clipboard_content_data(zg_stream * self, size_t index, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_clipboard_mime_count(zg_stream * self, size_t * out_result);
ZIGO_EXPORT int32_t zg_stream_clipboard_mime(zg_stream * self, size_t index, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_stream_allow_clipboard(zg_stream * self, uint8_t remember);
ZIGO_EXPORT int32_t zg_stream_reply_clipboard_text(zg_stream * self, const uint8_t * text_ptr, size_t text_len, uint8_t remember);
ZIGO_EXPORT int32_t zg_stream_deny_clipboard(zg_stream * self, uint8_t reason);
ZIGO_EXPORT int32_t zg_stream_write_continuation(zg_stream * self, size_t writer_userdata);
ZIGO_EXPORT int32_t zg_stream_has_replies(zg_stream * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_stream_write_replies(zg_stream * self, size_t writer_userdata);
ZIGO_EXPORT int32_t zg_terminal_print_string(zg_terminal * self, const uint8_t * str_ptr, size_t str_len);
ZIGO_EXPORT int32_t zg_terminal_plain_string(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_set_cursor_style(zg_terminal * self, uint8_t value);
ZIGO_EXPORT int32_t zg_terminal_set_cursor_pos(zg_terminal * self, size_t row_req, size_t col_req);
ZIGO_EXPORT int32_t zg_terminal_carriage_return(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_linefeed(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_backspace(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_cursor_is_at_prompt(zg_terminal * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_full_reset(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_switch_screen(zg_terminal * self, uint8_t key);
ZIGO_EXPORT int32_t zg_terminal_active_screen_key(zg_terminal * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_active_screen(zg_terminal * self, zg_screen * * out_result);
ZIGO_EXPORT int32_t zg_terminal_screen(zg_terminal * self, uint8_t key, zg_screen * * out_result);
ZIGO_EXPORT int32_t zg_screen_select_all(zg_screen * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_clear_selection(zg_screen * self);
ZIGO_EXPORT int32_t zg_screen_has_selection(zg_screen * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_select_range(zg_screen * self, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint8_t rectangle, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_select_word(zg_screen * self, uint16_t x, uint16_t y, const uint32_t * boundaries_ptr, size_t boundaries_len, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_select_line(zg_screen * self, uint16_t x, uint16_t y, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_select_output(zg_screen * self, uint16_t x, uint16_t y, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_selection_string(zg_screen * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_screen_viewport_is_bottom(const zg_screen * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_screen_new_search(zg_screen * self, const uint8_t * needle_ptr, size_t needle_len, zg_search * * out_result);
ZIGO_EXPORT int32_t zg_search_free_search(zg_search * self);
ZIGO_EXPORT int32_t zg_search_search_all(zg_search * self);
ZIGO_EXPORT int32_t zg_search_match_count(zg_search * self, size_t * out_result);
ZIGO_EXPORT int32_t zg_search_select(zg_search * self, uint8_t to, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_print_attributes_into(zg_terminal * self, uint8_t * dst_ptr, size_t dst_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_history_string(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_screen_string(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_cursor_up(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_cursor_down(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_cursor_left(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_cursor_right(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_save_cursor(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_restore_cursor(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_index(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_reverse_index(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_horizontal_tab(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_horizontal_tab_back(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_tab_set(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_tab_reset(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_tab_clear(zg_terminal * self, uint8_t cmd);
ZIGO_EXPORT int32_t zg_terminal_scroll_up(zg_terminal * self, size_t count);
ZIGO_EXPORT int32_t zg_terminal_scroll_down(zg_terminal * self, size_t count);
ZIGO_EXPORT int32_t zg_terminal_set_top_and_bottom_margin(zg_terminal * self, size_t top_req, size_t bottom_req);
ZIGO_EXPORT int32_t zg_terminal_set_left_and_right_margin(zg_terminal * self, size_t left_req, size_t right_req);
ZIGO_EXPORT int32_t zg_terminal_set_scrollback_max_bytes(zg_terminal * self, const size_t * max);
ZIGO_EXPORT int32_t zg_terminal_set_scrollback_max_lines(zg_terminal * self, const size_t * max);
ZIGO_EXPORT int32_t zg_terminal_insert_lines(zg_terminal * self, size_t count);
ZIGO_EXPORT int32_t zg_terminal_delete_lines(zg_terminal * self, size_t count);
ZIGO_EXPORT int32_t zg_terminal_insert_blanks(zg_terminal * self, size_t count);
ZIGO_EXPORT int32_t zg_terminal_delete_chars(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_erase_chars(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_erase_line(zg_terminal * self, uint8_t mode, uint8_t protected_req);
ZIGO_EXPORT int32_t zg_terminal_erase_display(zg_terminal * self, uint8_t mode, uint8_t protected_req);
ZIGO_EXPORT int32_t zg_terminal_decaln(zg_terminal * self);
ZIGO_EXPORT int32_t zg_terminal_print(zg_terminal * self, uint32_t c);
ZIGO_EXPORT int32_t zg_terminal_print_repeat(zg_terminal * self, size_t count_req);
ZIGO_EXPORT int32_t zg_terminal_print_slice(zg_terminal * self, const uint32_t * cps_ptr, size_t cps_len);
ZIGO_EXPORT int32_t zg_terminal_plain_string_unwrapped(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_set_pwd(zg_terminal * self, const uint8_t * pwd_ptr, size_t pwd_len);
ZIGO_EXPORT int32_t zg_terminal_get_pwd(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_get_title(zg_terminal * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT int32_t zg_terminal_set_title(zg_terminal * self, const uint8_t * t_ptr, size_t t_len);
ZIGO_EXPORT int32_t zg_terminal_set_attribute(zg_terminal * self, uint8_t attr_tag, uint8_t attr_underline, uint32_t attr_underline_color_rgb, uint8_t attr_underline_color_256, uint32_t attr_direct_color_fg, uint32_t attr_direct_color_bg, uint8_t attr_color_256_fg, uint8_t attr_color_256_bg, uint8_t attr_named_fg, uint8_t attr_named_bg, uint8_t attr_bright_named_fg, uint8_t attr_bright_named_bg);
ZIGO_EXPORT int32_t zg_terminal_set_protected_mode(zg_terminal * self, uint8_t mode);
ZIGO_EXPORT int32_t zg_terminal_set_default_cursor_style(zg_terminal * self, uint8_t configured_style);
ZIGO_EXPORT int32_t zg_terminal_set_default_cursor_blink(zg_terminal * self, const uint8_t * blink);
ZIGO_EXPORT int32_t zg_terminal_configure_charset(zg_terminal * self, uint8_t slot, uint8_t set);
ZIGO_EXPORT int32_t zg_terminal_invoke_charset(zg_terminal * self, uint8_t active, uint8_t slot, uint8_t single);
ZIGO_EXPORT int32_t zg_terminal_deccolm(zg_terminal * self, uint8_t mode);
ZIGO_EXPORT int32_t zg_terminal_scroll_viewport(zg_terminal * self, uint8_t behavior_tag, ptrdiff_t behavior_delta, size_t behavior_row);
ZIGO_EXPORT int32_t zg_terminal_compression_activity(zg_terminal * self, uint64_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_resize(zg_terminal * self, uint16_t width, uint16_t height);
ZIGO_EXPORT int32_t zg_terminal_resize_cells(zg_terminal * self, uint16_t width, uint16_t height, uint32_t cell_width, uint32_t cell_height);
ZIGO_EXPORT int32_t zg_new_render_state(zg_render_state * * out_result);
ZIGO_EXPORT int32_t zg_render_state_free_render_state(zg_render_state * self);
ZIGO_EXPORT int32_t zg_render_state_update(zg_render_state * self, zg_terminal * term);
ZIGO_EXPORT int32_t zg_render_state_cell_count(zg_render_state * self, size_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cells(zg_render_state * self, zg_render_cell * dst_ptr, size_t dst_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_rows(zg_render_state * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cols(zg_render_state * self, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_background(zg_render_state * self, uint32_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_foreground(zg_render_state * self, uint32_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cursor_x(zg_render_state * self, uint8_t * out_result_has, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cursor_y(zg_render_state * self, uint8_t * out_result_has, uint16_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cursor_visible(zg_render_state * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_render_state_cursor_style(zg_render_state * self, uint8_t * out_result);
ZIGO_EXPORT int32_t zg_new_kitty_images(zg_kitty_images * * out_result);
ZIGO_EXPORT int32_t zg_kitty_images_free_kitty_images(zg_kitty_images * self);
ZIGO_EXPORT int32_t zg_kitty_images_update(zg_kitty_images * self, zg_terminal * term);
ZIGO_EXPORT int32_t zg_kitty_images_generation(zg_kitty_images * self, uint64_t * out_result);
ZIGO_EXPORT int32_t zg_kitty_images_placement_count(zg_kitty_images * self, size_t * out_result);
ZIGO_EXPORT int32_t zg_kitty_images_placements(zg_kitty_images * self, zg_kitty_placement * dst_ptr, size_t dst_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_terminal_kitty_image(zg_terminal * self, uint32_t image_id, uint8_t * out_result_has, zg_kitty_image * out_result);
ZIGO_EXPORT int32_t zg_terminal_kitty_image_data(zg_terminal * self, uint32_t image_id, uint8_t * dst_ptr, size_t dst_len, size_t * out_result);
ZIGO_EXPORT const char *zg_last_error_message(void);

#endif // ZIGO_gostty_H
